"""Generated by ili2django. Do not edit manually."""

from django.contrib.gis.db import models

from ili2django.decorators import ili_field, interlis_model

@interlis_model(oid='CoordSys.CoordsysTopic.GeoHeight.System_ENUM', qname='odmav_coord_sys.GeoHeightSystemEnum')
class GeoHeightSystemEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='CoordSys.CoordsysTopic.GeoHeight.System_ENUM.code', qname='odmav_coord_sys.GeoHeightSystemEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='CoordSys.CoordsysTopic.GeoHeight.System_ENUM.label', qname='odmav_coord_sys.GeoHeightSystemEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['normal', 'orthometric', 'ellipsoidal', 'other']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_coord_sys__geo_height_system_enum_value'

@interlis_model(oid='CoordSys.CoordsysTopic.Ellipsoid', qname='odmav_coord_sys.Ellipsoid')
class Ellipsoid(models.Model):
    ellipsoid_alias = ili_field(models.CharField(max_length=70, null=True, blank=True), oid='CoordSys.CoordsysTopic.Ellipsoid.EllipsoidAlias', qname='odmav_coord_sys.Ellipsoid.EllipsoidAlias')
    semi_major_axis = ili_field(models.FloatField(null=False, blank=False), oid='CoordSys.CoordsysTopic.Ellipsoid.SemiMajorAxis', qname='odmav_coord_sys.Ellipsoid.SemiMajorAxis')
    inverse_flattening = ili_field(models.FloatField(null=False, blank=False), oid='CoordSys.CoordsysTopic.Ellipsoid.InverseFlattening', qname='odmav_coord_sys.Ellipsoid.InverseFlattening')
    remarks = ili_field(models.CharField(max_length=70, null=True, blank=True), oid='CoordSys.CoordsysTopic.Ellipsoid.Remarks', qname='odmav_coord_sys.Ellipsoid.Remarks')

    class Meta:
        db_table = 'odmav_coord_sys__ellipsoid'

@interlis_model(oid='CoordSys.CoordsysTopic.GravityModel', qname='odmav_coord_sys.GravityModel')
class GravityModel(models.Model):
    gravity_mod_alias = ili_field(models.CharField(max_length=70, null=True, blank=True), oid='CoordSys.CoordsysTopic.GravityModel.GravityModAlias', qname='odmav_coord_sys.GravityModel.GravityModAlias')
    definition = ili_field(models.CharField(max_length=70, null=True, blank=True), oid='CoordSys.CoordsysTopic.GravityModel.Definition', qname='odmav_coord_sys.GravityModel.Definition')

    class Meta:
        db_table = 'odmav_coord_sys__gravity_model'

@interlis_model(oid='CoordSys.CoordsysTopic.GeoidModel', qname='odmav_coord_sys.GeoidModel')
class GeoidModel(models.Model):
    geoid_mod_alias = ili_field(models.CharField(max_length=70, null=True, blank=True), oid='CoordSys.CoordsysTopic.GeoidModel.GeoidModAlias', qname='odmav_coord_sys.GeoidModel.GeoidModAlias')
    definition = ili_field(models.CharField(max_length=70, null=True, blank=True), oid='CoordSys.CoordsysTopic.GeoidModel.Definition', qname='odmav_coord_sys.GeoidModel.Definition')

    class Meta:
        db_table = 'odmav_coord_sys__geoid_model'

@interlis_model(oid='CoordSys.CoordsysTopic.LengthAXIS', qname='odmav_coord_sys.LengthAXIS')
class LengthAXIS(models.Model):
    unit = ili_field(models.IntegerField(null=True, blank=True), oid='CoordSys.CoordsysTopic.LengthAXIS.Unit', qname='odmav_coord_sys.LengthAXIS.Unit')
    short_name = ili_field(models.CharField(max_length=12, null=True, blank=True), oid='CoordSys.CoordsysTopic.LengthAXIS.ShortName', qname='odmav_coord_sys.LengthAXIS.ShortName')
    description = ili_field(models.CharField(max_length=255, null=True, blank=True), oid='CoordSys.CoordsysTopic.LengthAXIS.Description', qname='odmav_coord_sys.LengthAXIS.Description')

    class Meta:
        db_table = 'odmav_coord_sys__length_axis'

@interlis_model(oid='CoordSys.CoordsysTopic.AngleAXIS', qname='odmav_coord_sys.AngleAXIS')
class AngleAXIS(models.Model):
    unit = ili_field(models.IntegerField(null=True, blank=True), oid='CoordSys.CoordsysTopic.AngleAXIS.Unit', qname='odmav_coord_sys.AngleAXIS.Unit')
    short_name = ili_field(models.CharField(max_length=12, null=True, blank=True), oid='CoordSys.CoordsysTopic.AngleAXIS.ShortName', qname='odmav_coord_sys.AngleAXIS.ShortName')
    description = ili_field(models.CharField(max_length=255, null=True, blank=True), oid='CoordSys.CoordsysTopic.AngleAXIS.Description', qname='odmav_coord_sys.AngleAXIS.Description')

    class Meta:
        db_table = 'odmav_coord_sys__angle_axis'

@interlis_model(oid='CoordSys.CoordsysTopic.GeoCartesian1D', qname='odmav_coord_sys.GeoCartesian1D')
class GeoCartesian1D(models.Model):
    axis = ili_field(models.TextField(null=False, blank=False), oid='CoordSys.CoordsysTopic.GeoCartesian1D.Axis', qname='odmav_coord_sys.GeoCartesian1D.Axis')

    class Meta:
        db_table = 'odmav_coord_sys__geo_cartesian1_d'

@interlis_model(oid='CoordSys.CoordsysTopic.GeoHeight', qname='odmav_coord_sys.GeoHeight')
class GeoHeight(models.Model):
    system = ili_field(models.ForeignKey('odmav_coord_sys.GeoHeightSystemEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='CoordSys.CoordsysTopic.GeoHeight.System', qname='odmav_coord_sys.GeoHeight.System')
    reference_height = ili_field(models.FloatField(null=False, blank=False), oid='CoordSys.CoordsysTopic.GeoHeight.ReferenceHeight', qname='odmav_coord_sys.GeoHeight.ReferenceHeight')
    reference_height_descr = ili_field(models.CharField(max_length=70, null=True, blank=True), oid='CoordSys.CoordsysTopic.GeoHeight.ReferenceHeightDescr', qname='odmav_coord_sys.GeoHeight.ReferenceHeightDescr')
    ellipsoid_ref = ili_field(models.ForeignKey('odmav_coord_sys.Ellipsoid', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='CoordSys.CoordsysTopic.HeightEllips.EllipsoidRef', qname='odmav_coord_sys.GeoHeight.EllipsoidRef')
    gravity_ref = ili_field(models.ForeignKey('odmav_coord_sys.GravityModel', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='CoordSys.CoordsysTopic.HeightGravit.GravityRef', qname='odmav_coord_sys.GeoHeight.GravityRef')
    geoid_ref = ili_field(models.ForeignKey('odmav_coord_sys.GeoidModel', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='CoordSys.CoordsysTopic.HeightGeoid.GeoidRef', qname='odmav_coord_sys.GeoHeight.GeoidRef')

    class Meta:
        db_table = 'odmav_coord_sys__geo_height'

@interlis_model(oid='CoordSys.CoordsysTopic.GeoCartesian2D', qname='odmav_coord_sys.GeoCartesian2D')
class GeoCartesian2D(models.Model):
    axis = ili_field(models.JSONField(default=list, null=False, blank=False), oid='CoordSys.CoordsysTopic.GeoCartesian2D.Axis', qname='odmav_coord_sys.GeoCartesian2D.Axis')
    definition = ili_field(models.CharField(max_length=70, null=True, blank=True), oid='CoordSys.CoordsysTopic.GeoCartesian2D.Definition', qname='odmav_coord_sys.GeoCartesian2D.Definition')

    class Meta:
        db_table = 'odmav_coord_sys__geo_cartesian2_d'

@interlis_model(oid='CoordSys.CoordsysTopic.GeoCartesian3D', qname='odmav_coord_sys.GeoCartesian3D')
class GeoCartesian3D(models.Model):
    axis = ili_field(models.JSONField(default=list, null=False, blank=False), oid='CoordSys.CoordsysTopic.GeoCartesian3D.Axis', qname='odmav_coord_sys.GeoCartesian3D.Axis')
    definition = ili_field(models.CharField(max_length=70, null=True, blank=True), oid='CoordSys.CoordsysTopic.GeoCartesian3D.Definition', qname='odmav_coord_sys.GeoCartesian3D.Definition')

    class Meta:
        db_table = 'odmav_coord_sys__geo_cartesian3_d'

@interlis_model(oid='CoordSys.CoordsysTopic.GeoEllipsoidal', qname='odmav_coord_sys.GeoEllipsoidal')
class GeoEllipsoidal(models.Model):
    axis = ili_field(models.JSONField(default=list, null=False, blank=False), oid='CoordSys.CoordsysTopic.GeoEllipsoidal.Axis', qname='odmav_coord_sys.GeoEllipsoidal.Axis')
    definition = ili_field(models.CharField(max_length=70, null=True, blank=True), oid='CoordSys.CoordsysTopic.GeoEllipsoidal.Definition', qname='odmav_coord_sys.GeoEllipsoidal.Definition')
    ellipsoid_ref = ili_field(models.ForeignKey('odmav_coord_sys.Ellipsoid', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='CoordSys.CoordsysTopic.EllCSEllips.EllipsoidRef', qname='odmav_coord_sys.GeoEllipsoidal.EllipsoidRef')

    class Meta:
        db_table = 'odmav_coord_sys__geo_ellipsoidal'

@interlis_model(oid='CoordSys.CoordsysTopic.ToGeoEllipsoidal', qname='odmav_coord_sys.ToGeoEllipsoidal')
class ToGeoEllipsoidal(models.Model):
    from_field = ili_field(models.JSONField(default=list, null=True, blank=True), oid='CoordSys.CoordsysTopic.ToGeoEllipsoidal.From', qname='odmav_coord_sys.ToGeoEllipsoidal.From')
    to = ili_field(models.JSONField(default=list, null=True, blank=True), oid='CoordSys.CoordsysTopic.ToGeoEllipsoidal.To', qname='odmav_coord_sys.ToGeoEllipsoidal.To')
    to_height = ili_field(models.JSONField(default=list, null=True, blank=True), oid='CoordSys.CoordsysTopic.ToGeoEllipsoidal.ToHeight', qname='odmav_coord_sys.ToGeoEllipsoidal.ToHeight')

    class Meta:
        db_table = 'odmav_coord_sys__to_geo_ellipsoidal'

@interlis_model(oid='CoordSys.CoordsysTopic.ToGeoCartesian3D', qname='odmav_coord_sys.ToGeoCartesian3D')
class ToGeoCartesian3D(models.Model):
    from2 = ili_field(models.JSONField(default=list, null=True, blank=True), oid='CoordSys.CoordsysTopic.ToGeoCartesian3D.From2', qname='odmav_coord_sys.ToGeoCartesian3D.From2')
    from_height = ili_field(models.JSONField(default=list, null=True, blank=True), oid='CoordSys.CoordsysTopic.ToGeoCartesian3D.FromHeight', qname='odmav_coord_sys.ToGeoCartesian3D.FromHeight')
    to3 = ili_field(models.JSONField(default=list, null=True, blank=True), oid='CoordSys.CoordsysTopic.ToGeoCartesian3D.To3', qname='odmav_coord_sys.ToGeoCartesian3D.To3')

    class Meta:
        db_table = 'odmav_coord_sys__to_geo_cartesian3_d'

@interlis_model(oid='CoordSys.CoordsysTopic.BidirectGeoCartesian2D', qname='odmav_coord_sys.BidirectGeoCartesian2D')
class BidirectGeoCartesian2D(models.Model):
    from_field = ili_field(models.JSONField(default=list, null=True, blank=True), oid='CoordSys.CoordsysTopic.BidirectGeoCartesian2D.From', qname='odmav_coord_sys.BidirectGeoCartesian2D.From')
    to = ili_field(models.JSONField(default=list, null=True, blank=True), oid='CoordSys.CoordsysTopic.BidirectGeoCartesian2D.To', qname='odmav_coord_sys.BidirectGeoCartesian2D.To')

    class Meta:
        db_table = 'odmav_coord_sys__bidirect_geo_cartesian2_d'

@interlis_model(oid='CoordSys.CoordsysTopic.BidirectGeoCartesian3D', qname='odmav_coord_sys.BidirectGeoCartesian3D')
class BidirectGeoCartesian3D(models.Model):
    from_field = ili_field(models.JSONField(default=list, null=True, blank=True), oid='CoordSys.CoordsysTopic.BidirectGeoCartesian3D.From', qname='odmav_coord_sys.BidirectGeoCartesian3D.From')
    to2 = ili_field(models.JSONField(default=list, null=True, blank=True), oid='CoordSys.CoordsysTopic.BidirectGeoCartesian3D.To2', qname='odmav_coord_sys.BidirectGeoCartesian3D.To2')

    class Meta:
        db_table = 'odmav_coord_sys__bidirect_geo_cartesian3_d'

@interlis_model(oid='CoordSys.CoordsysTopic.BidirectGeoEllipsoidal', qname='odmav_coord_sys.BidirectGeoEllipsoidal')
class BidirectGeoEllipsoidal(models.Model):
    from4 = ili_field(models.JSONField(default=list, null=True, blank=True), oid='CoordSys.CoordsysTopic.BidirectGeoEllipsoidal.From4', qname='odmav_coord_sys.BidirectGeoEllipsoidal.From4')
    to4 = ili_field(models.JSONField(default=list, null=True, blank=True), oid='CoordSys.CoordsysTopic.BidirectGeoEllipsoidal.To4', qname='odmav_coord_sys.BidirectGeoEllipsoidal.To4')

    class Meta:
        db_table = 'odmav_coord_sys__bidirect_geo_ellipsoidal'

@interlis_model(oid='CoordSys.CoordsysTopic.MapProjection', qname='odmav_coord_sys.MapProjection')
class MapProjection(models.Model):
    from5 = ili_field(models.JSONField(default=list, null=True, blank=True), oid='CoordSys.CoordsysTopic.MapProjection.From5', qname='odmav_coord_sys.MapProjection.From5')
    to5 = ili_field(models.JSONField(default=list, null=True, blank=True), oid='CoordSys.CoordsysTopic.MapProjection.To5', qname='odmav_coord_sys.MapProjection.To5')

    class Meta:
        abstract = True
        db_table = 'odmav_coord_sys__map_projection'

@interlis_model(oid='CoordSys.CoordsysTopic.TransverseMercator', qname='odmav_coord_sys.TransverseMercator')
class TransverseMercator(models.Model):
    pass

    class Meta:
        db_table = 'odmav_coord_sys__transverse_mercator'

@interlis_model(oid='CoordSys.CoordsysTopic.SwissProjection', qname='odmav_coord_sys.SwissProjection')
class SwissProjection(models.Model):
    pass

    class Meta:
        db_table = 'odmav_coord_sys__swiss_projection'

@interlis_model(oid='CoordSys.CoordsysTopic.Mercator', qname='odmav_coord_sys.Mercator')
class Mercator(models.Model):
    pass

    class Meta:
        db_table = 'odmav_coord_sys__mercator'

@interlis_model(oid='CoordSys.CoordsysTopic.ObliqueMercator', qname='odmav_coord_sys.ObliqueMercator')
class ObliqueMercator(models.Model):
    pass

    class Meta:
        db_table = 'odmav_coord_sys__oblique_mercator'

@interlis_model(oid='CoordSys.CoordsysTopic.Lambert', qname='odmav_coord_sys.Lambert')
class Lambert(models.Model):
    pass

    class Meta:
        db_table = 'odmav_coord_sys__lambert'

@interlis_model(oid='CoordSys.CoordsysTopic.Polyconic', qname='odmav_coord_sys.Polyconic')
class Polyconic(models.Model):
    pass

    class Meta:
        db_table = 'odmav_coord_sys__polyconic'

@interlis_model(oid='CoordSys.CoordsysTopic.Albus', qname='odmav_coord_sys.Albus')
class Albus(models.Model):
    pass

    class Meta:
        db_table = 'odmav_coord_sys__albus'

@interlis_model(oid='CoordSys.CoordsysTopic.Azimutal', qname='odmav_coord_sys.Azimutal')
class Azimutal(models.Model):
    pass

    class Meta:
        db_table = 'odmav_coord_sys__azimutal'

@interlis_model(oid='CoordSys.CoordsysTopic.Stereographic', qname='odmav_coord_sys.Stereographic')
class Stereographic(models.Model):
    pass

    class Meta:
        db_table = 'odmav_coord_sys__stereographic'

@interlis_model(oid='CoordSys.CoordsysTopic.HeightConversion', qname='odmav_coord_sys.HeightConversion')
class HeightConversion(models.Model):
    from_height = ili_field(models.JSONField(default=list, null=True, blank=True), oid='CoordSys.CoordsysTopic.HeightConversion.FromHeight', qname='odmav_coord_sys.HeightConversion.FromHeight')
    to_height = ili_field(models.JSONField(default=list, null=True, blank=True), oid='CoordSys.CoordsysTopic.HeightConversion.ToHeight', qname='odmav_coord_sys.HeightConversion.ToHeight')

    class Meta:
        db_table = 'odmav_coord_sys__height_conversion'
