"""Generated by ili2django. Do not edit manually."""

from django.contrib.gis.db import models
from django.utils.translation import gettext_lazy as _

from ili2django.choices import IliChoice, IliChoices
from ili2django.decorators import ili_field, interlis_model

@interlis_model(oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.Bezirksgrenzabschnitt.Gueltigkeit_ENUM', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.BezirksgrenzabschnittGueltigkeitEnum')
class BezirksgrenzabschnittGueltigkeitEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.Bezirksgrenzabschnitt.Gueltigkeit_ENUM.code', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.BezirksgrenzabschnittGueltigkeitEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.Bezirksgrenzabschnitt.Gueltigkeit_ENUM.label', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.BezirksgrenzabschnittGueltigkeitEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['rechtskraeftig', 'streitig', 'provisorisch', 'undefiniert']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_hoheitsgrenzen_av_v1_0__bezirksgrenzabsch_910a8eb003'

class BezirksgrenzabschnittGueltigkeitEnumValueChoices(IliChoices):
    RECHTSKRAEFTIG = IliChoice('rechtskraeftig', _('rechtskraeftig'), order=0)
    STREITIG = IliChoice('streitig', _('streitig'), order=1)
    PROVISORISCH = IliChoice('provisorisch', _('provisorisch'), order=2)
    UNDEFINIERT = IliChoice('undefiniert', _('undefiniert'), order=3)

@interlis_model(oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.Kantonsgrenzabschnitt.Gueltigkeit_ENUM', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.KantonsgrenzabschnittGueltigkeitEnum')
class KantonsgrenzabschnittGueltigkeitEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.Kantonsgrenzabschnitt.Gueltigkeit_ENUM.code', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.KantonsgrenzabschnittGueltigkeitEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.Kantonsgrenzabschnitt.Gueltigkeit_ENUM.label', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.KantonsgrenzabschnittGueltigkeitEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['rechtskraeftig', 'streitig', 'provisorisch', 'undefiniert']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_hoheitsgrenzen_av_v1_0__kantonsgrenzabsch_f244fb953c'

class KantonsgrenzabschnittGueltigkeitEnumValueChoices(IliChoices):
    RECHTSKRAEFTIG = IliChoice('rechtskraeftig', _('rechtskraeftig'), order=0)
    STREITIG = IliChoice('streitig', _('streitig'), order=1)
    PROVISORISCH = IliChoice('provisorisch', _('provisorisch'), order=2)
    UNDEFINIERT = IliChoice('undefiniert', _('undefiniert'), order=3)

@interlis_model(oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.HHGNachfuehrung', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.HHGNachfuehrung')
class HHGNachfuehrung(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.HHGNachfuehrung.tid', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.HHGNachfuehrung.tid')
    nbident = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.HHGNachfuehrung.NBIdent', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.HHGNachfuehrung.NBIdent')
    identifikator = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.HHGNachfuehrung.Identifikator', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.HHGNachfuehrung.Identifikator')
    beschreibung = ili_field(models.CharField(max_length=60, null=False, blank=False), oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.HHGNachfuehrung.Beschreibung', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.HHGNachfuehrung.Beschreibung')
    perimeter = ili_field(models.CurvePolygonField(srid=2056, null=True, blank=True), oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.HHGNachfuehrung.Perimeter', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.HHGNachfuehrung.Perimeter')
    gueltiger_eintrag = ili_field(models.CharField(max_length=255, null=False, blank=False), oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.HHGNachfuehrung.GueltigerEintrag', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.HHGNachfuehrung.GueltigerEintrag')
    genehmigt_am = ili_field(models.CharField(max_length=255, null=True, blank=True), oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.HHGNachfuehrung.GenehmigtAm', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.HHGNachfuehrung.GenehmigtAm')

    class Meta:
        db_table = 'odmav_dmav_hoheitsgrenzen_av_v1_0__hhgnachfuehrung'

@interlis_model(oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.Gemeinde', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.Gemeinde')
class Gemeinde(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.Gemeinde.tid', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.Gemeinde.tid')
    name = ili_field(models.CharField(max_length=60, null=False, blank=False), oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.Gemeinde.Name', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.Gemeinde.Name')
    bfsnummer = ili_field(models.IntegerField(null=False, blank=False), oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.Gemeinde.BFSNummer', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.Gemeinde.BFSNummer')
    fiktiv = ili_field(models.BooleanField(default=False), oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.Gemeinde.Fiktiv', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.Gemeinde.Fiktiv')
    entstehung = ili_field(models.ForeignKey('odmav_dmav_hoheitsgrenzen_av_v1_0.HHGNachfuehrung', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.Entstehung_Gemeinde.Entstehung', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.Gemeinde.Entstehung')
    untergang = ili_field(models.ForeignKey('odmav_dmav_hoheitsgrenzen_av_v1_0.HHGNachfuehrung', on_delete=models.PROTECT, related_name='+', null=True, blank=True), oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.Untergang_Gemeinde.Untergang', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.Gemeinde.Untergang')
    vorgaenger = ili_field(models.ForeignKey('odmav_dmav_hoheitsgrenzen_av_v1_0.Gemeinde', on_delete=models.PROTECT, related_name='+', null=True, blank=True), oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.Vorgaenger_Nachfolger_Gemeinde.Vorgaenger', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.Gemeinde.Vorgaenger')

    class Meta:
        db_table = 'odmav_dmav_hoheitsgrenzen_av_v1_0__gemeinde'

@interlis_model(oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.Gemeindegrenze', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.Gemeindegrenze')
class Gemeindegrenze(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.Gemeindegrenze.tid', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.Gemeindegrenze.tid')
    geometrie = ili_field(models.CurvePolygonField(srid=2056, null=False, blank=False), oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.Gemeindegrenze.Geometrie', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.Gemeindegrenze.Geometrie')
    fiktiv = ili_field(models.BooleanField(default=False), oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.Gemeindegrenze.Fiktiv', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.Gemeindegrenze.Fiktiv')
    streitig = ili_field(models.MultiLineStringField(srid=2056, null=True, blank=True), oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.Gemeindegrenze.Streitig', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.Gemeindegrenze.Streitig')
    provisorisch = ili_field(models.MultiLineStringField(srid=2056, null=True, blank=True), oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.Gemeindegrenze.Provisorisch', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.Gemeindegrenze.Provisorisch')
    undefiniert = ili_field(models.MultiLineStringField(srid=2056, null=True, blank=True), oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.Gemeindegrenze.Undefiniert', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.Gemeindegrenze.Undefiniert')
    entstehung = ili_field(models.ForeignKey('odmav_dmav_hoheitsgrenzen_av_v1_0.HHGNachfuehrung', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.Entstehung_Gemeindegrenze.Entstehung', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.Gemeindegrenze.Entstehung')
    untergang = ili_field(models.ForeignKey('odmav_dmav_hoheitsgrenzen_av_v1_0.HHGNachfuehrung', on_delete=models.PROTECT, related_name='+', null=True, blank=True), oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.Untergang_Gemeindegrenze.Untergang', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.Gemeindegrenze.Untergang')
    vorgaenger = ili_field(models.ForeignKey('odmav_dmav_hoheitsgrenzen_av_v1_0.Gemeindegrenze', on_delete=models.PROTECT, related_name='+', null=True, blank=True), oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.Vorgaenger_Nachfolger_Gemeindegrenze.Vorgaenger', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.Gemeindegrenze.Vorgaenger')
    gemeinde = ili_field(models.ForeignKey('odmav_dmav_hoheitsgrenzen_av_v1_0.Gemeinde', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.GemeindeGemeindegrenze.Gemeinde', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.Gemeindegrenze.Gemeinde')

    class Meta:
        db_table = 'odmav_dmav_hoheitsgrenzen_av_v1_0__gemeindegrenze'

@interlis_model(oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.ProjGemeindegrenzabschnitt', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.ProjGemeindegrenzabschnitt')
class ProjGemeindegrenzabschnitt(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.ProjGemeindegrenzabschnitt.tid', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.ProjGemeindegrenzabschnitt.tid')
    geometrie = ili_field(models.LineStringField(srid=2056, null=False, blank=False), oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.ProjGemeindegrenzabschnitt.Geometrie', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.ProjGemeindegrenzabschnitt.Geometrie')
    entstehung = ili_field(models.ForeignKey('odmav_dmav_hoheitsgrenzen_av_v1_0.HHGNachfuehrung', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.Entstehung_ProjGemeindegrenzabschnitt.Entstehung', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.ProjGemeindegrenzabschnitt.Entstehung')
    untergang = ili_field(models.ForeignKey('odmav_dmav_hoheitsgrenzen_av_v1_0.HHGNachfuehrung', on_delete=models.PROTECT, related_name='+', null=True, blank=True), oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.Untergang_ProjGemeindegrenzabschnitt.Untergang', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.ProjGemeindegrenzabschnitt.Untergang')
    gemeinde = ili_field(models.ForeignKey('odmav_dmav_hoheitsgrenzen_av_v1_0.Gemeinde', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.GemeindeProjGemeindegrenzabschnitt.Gemeinde', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.ProjGemeindegrenzabschnitt.Gemeinde')
    vorgaenger = ili_field(models.ForeignKey('odmav_dmav_hoheitsgrenzen_av_v1_0.ProjGemeindegrenzabschnitt', on_delete=models.PROTECT, related_name='+', null=True, blank=True), oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.Vorgaenger_Nachfolger_ProjGemeindegrenzabschnitt.Vorgaenger', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.ProjGemeindegrenzabschnitt.Vorgaenger')

    class Meta:
        db_table = 'odmav_dmav_hoheitsgrenzen_av_v1_0__proj_gemeindegrenzabschnitt'

@interlis_model(oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.Bezirksgrenzabschnitt', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.Bezirksgrenzabschnitt')
class Bezirksgrenzabschnitt(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.Bezirksgrenzabschnitt.tid', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.Bezirksgrenzabschnitt.tid')
    geometrie = ili_field(models.LineStringField(srid=2056, null=False, blank=False), oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.Bezirksgrenzabschnitt.Geometrie', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.Bezirksgrenzabschnitt.Geometrie')
    gueltigkeit = ili_field(models.ForeignKey('odmav_dmav_hoheitsgrenzen_av_v1_0.BezirksgrenzabschnittGueltigkeitEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.Bezirksgrenzabschnitt.Gueltigkeit', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.Bezirksgrenzabschnitt.Gueltigkeit')
    entstehung = ili_field(models.ForeignKey('odmav_dmav_hoheitsgrenzen_av_v1_0.HHGNachfuehrung', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.Entstehung_Bezirksgrenzabschnitt.Entstehung', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.Bezirksgrenzabschnitt.Entstehung')
    untergang = ili_field(models.ForeignKey('odmav_dmav_hoheitsgrenzen_av_v1_0.HHGNachfuehrung', on_delete=models.PROTECT, related_name='+', null=True, blank=True), oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.Untergang_Bezirksgrenzabschnitt.Untergang', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.Bezirksgrenzabschnitt.Untergang')
    vorgaenger = ili_field(models.ForeignKey('odmav_dmav_hoheitsgrenzen_av_v1_0.Bezirksgrenzabschnitt', on_delete=models.PROTECT, related_name='+', null=True, blank=True), oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.Vorgaenger_Nachfolger_Bezirksgrenzabschnitt.Vorgaenger', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.Bezirksgrenzabschnitt.Vorgaenger')

    class Meta:
        db_table = 'odmav_dmav_hoheitsgrenzen_av_v1_0__bezirksgrenzabschnitt'

@interlis_model(oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.Kantonsgrenzabschnitt', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.Kantonsgrenzabschnitt')
class Kantonsgrenzabschnitt(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.Kantonsgrenzabschnitt.tid', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.Kantonsgrenzabschnitt.tid')
    geometrie = ili_field(models.LineStringField(srid=2056, null=False, blank=False), oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.Kantonsgrenzabschnitt.Geometrie', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.Kantonsgrenzabschnitt.Geometrie')
    gueltigkeit = ili_field(models.ForeignKey('odmav_dmav_hoheitsgrenzen_av_v1_0.KantonsgrenzabschnittGueltigkeitEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.Kantonsgrenzabschnitt.Gueltigkeit', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.Kantonsgrenzabschnitt.Gueltigkeit')
    entstehung = ili_field(models.ForeignKey('odmav_dmav_hoheitsgrenzen_av_v1_0.HHGNachfuehrung', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.Entstehung_Kantonsgrenzabschnitt.Entstehung', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.Kantonsgrenzabschnitt.Entstehung')
    untergang = ili_field(models.ForeignKey('odmav_dmav_hoheitsgrenzen_av_v1_0.HHGNachfuehrung', on_delete=models.PROTECT, related_name='+', null=True, blank=True), oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.Untergang_Kantonsgrenzabschnitt.Untergang', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.Kantonsgrenzabschnitt.Untergang')
    vorgaenger = ili_field(models.ForeignKey('odmav_dmav_hoheitsgrenzen_av_v1_0.Kantonsgrenzabschnitt', on_delete=models.PROTECT, related_name='+', null=True, blank=True), oid='DMAV_HoheitsgrenzenAV_V1_0.HoheitsgrenzenAV.Vorgaenger_Nachfolger_Kantonsgrenzabschnitt.Vorgaenger', qname='odmav_dmav_hoheitsgrenzen_av_v1_0.Kantonsgrenzabschnitt.Vorgaenger')

    class Meta:
        db_table = 'odmav_dmav_hoheitsgrenzen_av_v1_0__kantonsgrenzabschnitt'
