"""Generated by ili2django. Do not edit manually."""

from django.contrib.gis.db import models
from django.utils.translation import gettext_lazy as _

from ili2django.choices import IliChoice, IliChoices
from ili2django.decorators import ili_field, interlis_model

@interlis_model(oid='OfficialIndexOfLocalities_V1_0.OfficialIndexOfLocalities.Locality.Language_ENUM', qname='odmav_official_index_of_localities_v1_0.LocalityLanguageEnum')
class LocalityLanguageEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='OfficialIndexOfLocalities_V1_0.OfficialIndexOfLocalities.Locality.Language_ENUM.code', qname='odmav_official_index_of_localities_v1_0.LocalityLanguageEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='OfficialIndexOfLocalities_V1_0.OfficialIndexOfLocalities.Locality.Language_ENUM.label', qname='odmav_official_index_of_localities_v1_0.LocalityLanguageEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['de', 'fr', 'it', 'rm', 'multiple']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_official_index_of_localities_v1_0__locality_la_f659c86253'

class LocalityLanguageEnumValueChoices(IliChoices):
    DE = IliChoice('de', _('de'), order=0)
    FR = IliChoice('fr', _('fr'), order=1)
    IT = IliChoice('it', _('it'), order=2)
    RM = IliChoice('rm', _('rm'), order=3)
    MULTIPLE = IliChoice('multiple', _('multiple'), order=4)

@interlis_model(oid='OfficialIndexOfLocalities_V1_0.OfficialIndexOfLocalities.Locality.Status_ENUM', qname='odmav_official_index_of_localities_v1_0.LocalityStatusEnum')
class LocalityStatusEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='OfficialIndexOfLocalities_V1_0.OfficialIndexOfLocalities.Locality.Status_ENUM.code', qname='odmav_official_index_of_localities_v1_0.LocalityStatusEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='OfficialIndexOfLocalities_V1_0.OfficialIndexOfLocalities.Locality.Status_ENUM.label', qname='odmav_official_index_of_localities_v1_0.LocalityStatusEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['planned', 'real', 'outdated']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_official_index_of_localities_v1_0__locality_st_12d76449b2'

class LocalityStatusEnumValueChoices(IliChoices):
    PLANNED = IliChoice('planned', _('planned'), order=0)
    REAL = IliChoice('real', _('real'), order=1)
    OUTDATED = IliChoice('outdated', _('outdated'), order=2)

@interlis_model(oid='OfficialIndexOfLocalities_V1_0.OfficialIndexOfLocalities.ZIP.Status_ENUM', qname='odmav_official_index_of_localities_v1_0.ZIPStatusEnum')
class ZIPStatusEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='OfficialIndexOfLocalities_V1_0.OfficialIndexOfLocalities.ZIP.Status_ENUM.code', qname='odmav_official_index_of_localities_v1_0.ZIPStatusEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='OfficialIndexOfLocalities_V1_0.OfficialIndexOfLocalities.ZIP.Status_ENUM.label', qname='odmav_official_index_of_localities_v1_0.ZIPStatusEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['planned', 'real', 'outdated']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_official_index_of_localities_v1_0__zipstatus_enum_value'

class ZIPStatusEnumValueChoices(IliChoices):
    PLANNED = IliChoice('planned', _('planned'), order=0)
    REAL = IliChoice('real', _('real'), order=1)
    OUTDATED = IliChoice('outdated', _('outdated'), order=2)

@interlis_model(oid='OfficialIndexOfLocalities_V1_0.OfficialIndexOfLocalities.Locality', qname='odmav_official_index_of_localities_v1_0.Locality')
class Locality(models.Model):
    locality_id = ili_field(models.CharField(max_length=36, null=True, blank=True), oid='OfficialIndexOfLocalities_V1_0.OfficialIndexOfLocalities.Locality.LocalityID', qname='odmav_official_index_of_localities_v1_0.Locality.LocalityID')
    locality_name = ili_field(models.CharField(max_length=40, null=False, blank=False), oid='OfficialIndexOfLocalities_V1_0.OfficialIndexOfLocalities.Locality.LocalityName', qname='odmav_official_index_of_localities_v1_0.Locality.LocalityName')
    locality_short_name = ili_field(models.CharField(max_length=20, null=True, blank=True), oid='OfficialIndexOfLocalities_V1_0.OfficialIndexOfLocalities.Locality.LocalityShortName', qname='odmav_official_index_of_localities_v1_0.Locality.LocalityShortName')
    locality_index_name = ili_field(models.CharField(max_length=20, null=True, blank=True), oid='OfficialIndexOfLocalities_V1_0.OfficialIndexOfLocalities.Locality.LocalityIndexName', qname='odmav_official_index_of_localities_v1_0.Locality.LocalityIndexName')
    language = ili_field(models.ForeignKey('odmav_official_index_of_localities_v1_0.LocalityLanguageEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='OfficialIndexOfLocalities_V1_0.OfficialIndexOfLocalities.Locality.Language', qname='odmav_official_index_of_localities_v1_0.Locality.Language')
    status = ili_field(models.ForeignKey('odmav_official_index_of_localities_v1_0.LocalityStatusEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='OfficialIndexOfLocalities_V1_0.OfficialIndexOfLocalities.Locality.Status', qname='odmav_official_index_of_localities_v1_0.Locality.Status')
    in_modification = ili_field(models.BooleanField(default=False), oid='OfficialIndexOfLocalities_V1_0.OfficialIndexOfLocalities.Locality.InModification', qname='odmav_official_index_of_localities_v1_0.Locality.InModification')
    validity = ili_field(models.CharField(max_length=255, null=False, blank=False), oid='OfficialIndexOfLocalities_V1_0.OfficialIndexOfLocalities.Locality.Validity', qname='odmav_official_index_of_localities_v1_0.Locality.Validity')
    modified = ili_field(models.CharField(max_length=255, null=False, blank=False), oid='OfficialIndexOfLocalities_V1_0.OfficialIndexOfLocalities.Locality.Modified', qname='odmav_official_index_of_localities_v1_0.Locality.Modified')
    geometry = ili_field(models.MultiPolygonField(srid=2056, null=False, blank=False), oid='OfficialIndexOfLocalities_V1_0.OfficialIndexOfLocalities.Locality.Geometry', qname='odmav_official_index_of_localities_v1_0.Locality.Geometry')

    class Meta:
        db_table = 'odmav_official_index_of_localities_v1_0__locality'

@interlis_model(oid='OfficialIndexOfLocalities_V1_0.OfficialIndexOfLocalities.ZIP', qname='odmav_official_index_of_localities_v1_0.ZIP')
class ZIP(models.Model):
    zip_id = ili_field(models.IntegerField(null=True, blank=True), oid='OfficialIndexOfLocalities_V1_0.OfficialIndexOfLocalities.ZIP.ZIP_ID', qname='odmav_official_index_of_localities_v1_0.ZIP.ZIP_ID')
    zip4 = ili_field(models.IntegerField(null=True, blank=True), oid='OfficialIndexOfLocalities_V1_0.OfficialIndexOfLocalities.ZIP.ZIP4', qname='odmav_official_index_of_localities_v1_0.ZIP.ZIP4')
    additional_number = ili_field(models.CharField(max_length=2, null=True, blank=True), oid='OfficialIndexOfLocalities_V1_0.OfficialIndexOfLocalities.ZIP.AdditionalNumber', qname='odmav_official_index_of_localities_v1_0.ZIP.AdditionalNumber')
    status = ili_field(models.ForeignKey('odmav_official_index_of_localities_v1_0.ZIPStatusEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='OfficialIndexOfLocalities_V1_0.OfficialIndexOfLocalities.ZIP.Status', qname='odmav_official_index_of_localities_v1_0.ZIP.Status')
    in_modification = ili_field(models.BooleanField(default=False), oid='OfficialIndexOfLocalities_V1_0.OfficialIndexOfLocalities.ZIP.InModification', qname='odmav_official_index_of_localities_v1_0.ZIP.InModification')
    modified = ili_field(models.CharField(max_length=255, null=False, blank=False), oid='OfficialIndexOfLocalities_V1_0.OfficialIndexOfLocalities.ZIP.Modified', qname='odmav_official_index_of_localities_v1_0.ZIP.Modified')
    geometry = ili_field(models.MultiPolygonField(srid=2056, null=False, blank=False), oid='OfficialIndexOfLocalities_V1_0.OfficialIndexOfLocalities.ZIP.Geometry', qname='odmav_official_index_of_localities_v1_0.ZIP.Geometry')
    locality = ili_field(models.ForeignKey('odmav_official_index_of_localities_v1_0.Locality', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='OfficialIndexOfLocalities_V1_0.OfficialIndexOfLocalities.LocalityZIP.Locality', qname='odmav_official_index_of_localities_v1_0.ZIP.Locality')

    class Meta:
        db_table = 'odmav_official_index_of_localities_v1_0__zip'
