"""Generated by ili2django. Do not edit manually."""

from django.contrib.gis.db import models
from django.utils.translation import gettext_lazy as _

from ili2django.choices import IliChoice, IliChoices
from ili2django.decorators import ili_field, interlis_model

@interlis_model(oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Einzelobjektart', qname='odmav_dmav_einzelobjekte_v1_1.Einzelobjektart')
class EinzelobjektartValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Einzelobjektart.code', qname='odmav_dmav_einzelobjekte_v1_1.Einzelobjektart.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Einzelobjektart.label', qname='odmav_dmav_einzelobjekte_v1_1.Einzelobjektart.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['Mauer', 'unterirdisches_Gebaeude', 'uebriger_Gebaeudeteil', 'eingedoltes_oeffentliches_Gewaesser', 'wichtige_Treppe', 'Tunnel_Unterfuehrung_Galerie', 'Bruecke_Passerelle', 'Bahnsteig', 'Brunnen', 'Reservoir', 'Pfeiler', 'Unterstand', 'Silo_Turm_Gasometer', 'Hochkamin', 'Denkmal', 'Mast_Antenne', 'Aussichtsturm', 'Uferverbauung', 'Schwelle', 'Lawinenverbauung', 'massiver_Sockel', 'Ruine_archaeologisches_Objekt', 'Landungssteg', 'einzelner_Fels', 'schmale_bestockte_Flaeche', 'Rinnsal', 'schmaler_Weg', 'Hochspannungsfreileitung', 'Druckleitung', 'Bahngeleise', 'Luftseilbahn', 'Gondelbahn_Sesselbahn', 'Materialseilbahn', 'Skilift', 'Faehre', 'Grotte_Hoehleneingang', 'Achse', 'wichtiger_Einzelbaum', 'Bildstock_Kruzifix', 'Quelle', 'Bezugspunkt', 'Jauchengrube_Mistlege']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_einzelobjekte_v1_1__einzelobjektart_value'

class EinzelobjektartValueChoices(IliChoices):
    MAUER = IliChoice('Mauer', _('Mauer'), order=0)
    UNTERIRDISCHES_GEBAEUDE = IliChoice('unterirdisches_Gebaeude', _('unterirdisches_Gebaeude'), order=1)
    UEBRIGER_GEBAEUDETEIL = IliChoice('uebriger_Gebaeudeteil', _('uebriger_Gebaeudeteil'), order=2)
    EINGEDOLTES_OEFFENTLICHES_GEWAESSER = IliChoice('eingedoltes_oeffentliches_Gewaesser', _('eingedoltes_oeffentliches_Gewaesser'), order=3)
    WICHTIGE_TREPPE = IliChoice('wichtige_Treppe', _('wichtige_Treppe'), order=4)
    TUNNEL_UNTERFUEHRUNG_GALERIE = IliChoice('Tunnel_Unterfuehrung_Galerie', _('Tunnel_Unterfuehrung_Galerie'), order=5)
    BRUECKE_PASSERELLE = IliChoice('Bruecke_Passerelle', _('Bruecke_Passerelle'), order=6)
    BAHNSTEIG = IliChoice('Bahnsteig', _('Bahnsteig'), order=7)
    BRUNNEN = IliChoice('Brunnen', _('Brunnen'), order=8)
    RESERVOIR = IliChoice('Reservoir', _('Reservoir'), order=9)
    PFEILER = IliChoice('Pfeiler', _('Pfeiler'), order=10)
    UNTERSTAND = IliChoice('Unterstand', _('Unterstand'), order=11)
    SILO_TURM_GASOMETER = IliChoice('Silo_Turm_Gasometer', _('Silo_Turm_Gasometer'), order=12)
    HOCHKAMIN = IliChoice('Hochkamin', _('Hochkamin'), order=13)
    DENKMAL = IliChoice('Denkmal', _('Denkmal'), order=14)
    MAST_ANTENNE = IliChoice('Mast_Antenne', _('Mast_Antenne'), order=15)
    AUSSICHTSTURM = IliChoice('Aussichtsturm', _('Aussichtsturm'), order=16)
    UFERVERBAUUNG = IliChoice('Uferverbauung', _('Uferverbauung'), order=17)
    SCHWELLE = IliChoice('Schwelle', _('Schwelle'), order=18)
    LAWINENVERBAUUNG = IliChoice('Lawinenverbauung', _('Lawinenverbauung'), order=19)
    MASSIVER_SOCKEL = IliChoice('massiver_Sockel', _('massiver_Sockel'), order=20)
    RUINE_ARCHAEOLOGISCHES_OBJEKT = IliChoice('Ruine_archaeologisches_Objekt', _('Ruine_archaeologisches_Objekt'), order=21)
    LANDUNGSSTEG = IliChoice('Landungssteg', _('Landungssteg'), order=22)
    EINZELNER_FELS = IliChoice('einzelner_Fels', _('einzelner_Fels'), order=23)
    SCHMALE_BESTOCKTE_FLAECHE = IliChoice('schmale_bestockte_Flaeche', _('schmale_bestockte_Flaeche'), order=24)
    RINNSAL = IliChoice('Rinnsal', _('Rinnsal'), order=25)
    SCHMALER_WEG = IliChoice('schmaler_Weg', _('schmaler_Weg'), order=26)
    HOCHSPANNUNGSFREILEITUNG = IliChoice('Hochspannungsfreileitung', _('Hochspannungsfreileitung'), order=27)
    DRUCKLEITUNG = IliChoice('Druckleitung', _('Druckleitung'), order=28)
    BAHNGELEISE = IliChoice('Bahngeleise', _('Bahngeleise'), order=29)
    LUFTSEILBAHN = IliChoice('Luftseilbahn', _('Luftseilbahn'), order=30)
    GONDELBAHN_SESSELBAHN = IliChoice('Gondelbahn_Sesselbahn', _('Gondelbahn_Sesselbahn'), order=31)
    MATERIALSEILBAHN = IliChoice('Materialseilbahn', _('Materialseilbahn'), order=32)
    SKILIFT = IliChoice('Skilift', _('Skilift'), order=33)
    FAEHRE = IliChoice('Faehre', _('Faehre'), order=34)
    GROTTE_HOEHLENEINGANG = IliChoice('Grotte_Hoehleneingang', _('Grotte_Hoehleneingang'), order=35)
    ACHSE = IliChoice('Achse', _('Achse'), order=36)
    WICHTIGER_EINZELBAUM = IliChoice('wichtiger_Einzelbaum', _('wichtiger_Einzelbaum'), order=37)
    BILDSTOCK_KRUZIFIX = IliChoice('Bildstock_Kruzifix', _('Bildstock_Kruzifix'), order=38)
    QUELLE = IliChoice('Quelle', _('Quelle'), order=39)
    BEZUGSPUNKT = IliChoice('Bezugspunkt', _('Bezugspunkt'), order=40)
    JAUCHENGRUBE_MISTLEGE = IliChoice('Jauchengrube_Mistlege', _('Jauchengrube_Mistlege'), order=41)

@interlis_model(oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Einzelobjekt.Qualitaetsstandard_ENUM', qname='odmav_dmav_einzelobjekte_v1_1.EinzelobjektQualitaetsstandardEnum')
class EinzelobjektQualitaetsstandardEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Einzelobjekt.Qualitaetsstandard_ENUM.code', qname='odmav_dmav_einzelobjekte_v1_1.EinzelobjektQualitaetsstandardEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Einzelobjekt.Qualitaetsstandard_ENUM.label', qname='odmav_dmav_einzelobjekte_v1_1.EinzelobjektQualitaetsstandardEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['AV93', 'PN']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_einzelobjekte_v1_1__einzelobjekt_qualitae_8980c02b45'

class EinzelobjektQualitaetsstandardEnumValueChoices(IliChoices):
    AV93 = IliChoice('AV93', _('AV93'), order=0)
    PN = IliChoice('PN', _('PN'), order=1)

@interlis_model(oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Einzelobjekt.Einzelobjektart_ENUM', qname='odmav_dmav_einzelobjekte_v1_1.EinzelobjektEinzelobjektartEnum')
class EinzelobjektEinzelobjektartEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Einzelobjekt.Einzelobjektart_ENUM.code', qname='odmav_dmav_einzelobjekte_v1_1.EinzelobjektEinzelobjektartEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Einzelobjekt.Einzelobjektart_ENUM.label', qname='odmav_dmav_einzelobjekte_v1_1.EinzelobjektEinzelobjektartEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['Mauer', 'unterirdisches_Gebaeude', 'uebriger_Gebaeudeteil', 'eingedoltes_oeffentliches_Gewaesser', 'wichtige_Treppe', 'Tunnel_Unterfuehrung_Galerie', 'Bruecke_Passerelle', 'Bahnsteig', 'Brunnen', 'Reservoir', 'Pfeiler', 'Unterstand', 'Silo_Turm_Gasometer', 'Hochkamin', 'Denkmal', 'Mast_Antenne', 'Aussichtsturm', 'Uferverbauung', 'Schwelle', 'Lawinenverbauung', 'massiver_Sockel', 'Ruine_archaeologisches_Objekt', 'Landungssteg', 'einzelner_Fels', 'schmale_bestockte_Flaeche', 'Rinnsal', 'schmaler_Weg', 'Hochspannungsfreileitung', 'Druckleitung', 'Bahngeleise', 'Luftseilbahn', 'Gondelbahn_Sesselbahn', 'Materialseilbahn', 'Skilift', 'Faehre', 'Grotte_Hoehleneingang', 'Achse', 'wichtiger_Einzelbaum', 'Bildstock_Kruzifix', 'Quelle', 'Bezugspunkt', 'Jauchengrube_Mistlege']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_einzelobjekte_v1_1__einzelobjekt_einzelob_5f22c2a93c'

class EinzelobjektEinzelobjektartEnumValueChoices(IliChoices):
    MAUER = IliChoice('Mauer', _('Mauer'), order=0)
    UNTERIRDISCHES_GEBAEUDE = IliChoice('unterirdisches_Gebaeude', _('unterirdisches_Gebaeude'), order=1)
    UEBRIGER_GEBAEUDETEIL = IliChoice('uebriger_Gebaeudeteil', _('uebriger_Gebaeudeteil'), order=2)
    EINGEDOLTES_OEFFENTLICHES_GEWAESSER = IliChoice('eingedoltes_oeffentliches_Gewaesser', _('eingedoltes_oeffentliches_Gewaesser'), order=3)
    WICHTIGE_TREPPE = IliChoice('wichtige_Treppe', _('wichtige_Treppe'), order=4)
    TUNNEL_UNTERFUEHRUNG_GALERIE = IliChoice('Tunnel_Unterfuehrung_Galerie', _('Tunnel_Unterfuehrung_Galerie'), order=5)
    BRUECKE_PASSERELLE = IliChoice('Bruecke_Passerelle', _('Bruecke_Passerelle'), order=6)
    BAHNSTEIG = IliChoice('Bahnsteig', _('Bahnsteig'), order=7)
    BRUNNEN = IliChoice('Brunnen', _('Brunnen'), order=8)
    RESERVOIR = IliChoice('Reservoir', _('Reservoir'), order=9)
    PFEILER = IliChoice('Pfeiler', _('Pfeiler'), order=10)
    UNTERSTAND = IliChoice('Unterstand', _('Unterstand'), order=11)
    SILO_TURM_GASOMETER = IliChoice('Silo_Turm_Gasometer', _('Silo_Turm_Gasometer'), order=12)
    HOCHKAMIN = IliChoice('Hochkamin', _('Hochkamin'), order=13)
    DENKMAL = IliChoice('Denkmal', _('Denkmal'), order=14)
    MAST_ANTENNE = IliChoice('Mast_Antenne', _('Mast_Antenne'), order=15)
    AUSSICHTSTURM = IliChoice('Aussichtsturm', _('Aussichtsturm'), order=16)
    UFERVERBAUUNG = IliChoice('Uferverbauung', _('Uferverbauung'), order=17)
    SCHWELLE = IliChoice('Schwelle', _('Schwelle'), order=18)
    LAWINENVERBAUUNG = IliChoice('Lawinenverbauung', _('Lawinenverbauung'), order=19)
    MASSIVER_SOCKEL = IliChoice('massiver_Sockel', _('massiver_Sockel'), order=20)
    RUINE_ARCHAEOLOGISCHES_OBJEKT = IliChoice('Ruine_archaeologisches_Objekt', _('Ruine_archaeologisches_Objekt'), order=21)
    LANDUNGSSTEG = IliChoice('Landungssteg', _('Landungssteg'), order=22)
    EINZELNER_FELS = IliChoice('einzelner_Fels', _('einzelner_Fels'), order=23)
    SCHMALE_BESTOCKTE_FLAECHE = IliChoice('schmale_bestockte_Flaeche', _('schmale_bestockte_Flaeche'), order=24)
    RINNSAL = IliChoice('Rinnsal', _('Rinnsal'), order=25)
    SCHMALER_WEG = IliChoice('schmaler_Weg', _('schmaler_Weg'), order=26)
    HOCHSPANNUNGSFREILEITUNG = IliChoice('Hochspannungsfreileitung', _('Hochspannungsfreileitung'), order=27)
    DRUCKLEITUNG = IliChoice('Druckleitung', _('Druckleitung'), order=28)
    BAHNGELEISE = IliChoice('Bahngeleise', _('Bahngeleise'), order=29)
    LUFTSEILBAHN = IliChoice('Luftseilbahn', _('Luftseilbahn'), order=30)
    GONDELBAHN_SESSELBAHN = IliChoice('Gondelbahn_Sesselbahn', _('Gondelbahn_Sesselbahn'), order=31)
    MATERIALSEILBAHN = IliChoice('Materialseilbahn', _('Materialseilbahn'), order=32)
    SKILIFT = IliChoice('Skilift', _('Skilift'), order=33)
    FAEHRE = IliChoice('Faehre', _('Faehre'), order=34)
    GROTTE_HOEHLENEINGANG = IliChoice('Grotte_Hoehleneingang', _('Grotte_Hoehleneingang'), order=35)
    ACHSE = IliChoice('Achse', _('Achse'), order=36)
    WICHTIGER_EINZELBAUM = IliChoice('wichtiger_Einzelbaum', _('wichtiger_Einzelbaum'), order=37)
    BILDSTOCK_KRUZIFIX = IliChoice('Bildstock_Kruzifix', _('Bildstock_Kruzifix'), order=38)
    QUELLE = IliChoice('Quelle', _('Quelle'), order=39)
    BEZUGSPUNKT = IliChoice('Bezugspunkt', _('Bezugspunkt'), order=40)
    JAUCHENGRUBE_MISTLEGE = IliChoice('Jauchengrube_Mistlege', _('Jauchengrube_Mistlege'), order=41)

@interlis_model(oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Einzelobjekt.Objektstatus_ENUM', qname='odmav_dmav_einzelobjekte_v1_1.EinzelobjektObjektstatusEnum')
class EinzelobjektObjektstatusEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Einzelobjekt.Objektstatus_ENUM.code', qname='odmav_dmav_einzelobjekte_v1_1.EinzelobjektObjektstatusEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Einzelobjekt.Objektstatus_ENUM.label', qname='odmav_dmav_einzelobjekte_v1_1.EinzelobjektObjektstatusEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['projektiert', 'real', 'vergangen']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_einzelobjekte_v1_1__einzelobjekt_objektst_353ca2a14e'

class EinzelobjektObjektstatusEnumValueChoices(IliChoices):
    PROJEKTIERT = IliChoice('projektiert', _('projektiert'), order=0)
    REAL = IliChoice('real', _('real'), order=1)
    VERGANGEN = IliChoice('vergangen', _('vergangen'), order=2)

@interlis_model(oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.EONachfuehrung', qname='odmav_dmav_einzelobjekte_v1_1.EONachfuehrung')
class EONachfuehrung(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_Einzelobjekte_V1_1.Einzelobjekte.EONachfuehrung.tid', qname='odmav_dmav_einzelobjekte_v1_1.EONachfuehrung.tid')
    nbident = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.EONachfuehrung.NBIdent', qname='odmav_dmav_einzelobjekte_v1_1.EONachfuehrung.NBIdent')
    identifikator = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.EONachfuehrung.Identifikator', qname='odmav_dmav_einzelobjekte_v1_1.EONachfuehrung.Identifikator')
    beschreibung = ili_field(models.CharField(max_length=60, null=False, blank=False), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.EONachfuehrung.Beschreibung', qname='odmav_dmav_einzelobjekte_v1_1.EONachfuehrung.Beschreibung')
    perimeter = ili_field(models.CurvePolygonField(srid=2056, null=True, blank=True), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.EONachfuehrung.Perimeter', qname='odmav_dmav_einzelobjekte_v1_1.EONachfuehrung.Perimeter')
    gueltiger_eintrag = ili_field(models.CharField(max_length=255, null=False, blank=False), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.EONachfuehrung.GueltigerEintrag', qname='odmav_dmav_einzelobjekte_v1_1.EONachfuehrung.GueltigerEintrag')

    class Meta:
        db_table = 'odmav_dmav_einzelobjekte_v1_1__eonachfuehrung'

@interlis_model(oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Flaechenelement', qname='odmav_dmav_einzelobjekte_v1_1.Flaechenelement')
class Flaechenelement(models.Model):
    geometrie = ili_field(models.CurvePolygonField(srid=2056, null=False, blank=False), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Flaechenelement.Geometrie', qname='odmav_dmav_einzelobjekte_v1_1.Flaechenelement.Geometrie')
    symbolposition = ili_field(models.MultiPointField(srid=2056, null=True, blank=True), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Flaechenelement.Symbolposition', qname='odmav_dmav_einzelobjekte_v1_1.Flaechenelement.Symbolposition')

    class Meta:
        db_table = 'odmav_dmav_einzelobjekte_v1_1__flaechenelement'

@interlis_model(oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Linienelement', qname='odmav_dmav_einzelobjekte_v1_1.Linienelement')
class Linienelement(models.Model):
    geometrie = ili_field(models.LineStringField(srid=2056, null=False, blank=False), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Linienelement.Geometrie', qname='odmav_dmav_einzelobjekte_v1_1.Linienelement.Geometrie')
    symbolposition = ili_field(models.MultiPointField(srid=2056, null=True, blank=True), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Linienelement.Symbolposition', qname='odmav_dmav_einzelobjekte_v1_1.Linienelement.Symbolposition')

    class Meta:
        db_table = 'odmav_dmav_einzelobjekte_v1_1__linienelement'

@interlis_model(oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Punktelement', qname='odmav_dmav_einzelobjekte_v1_1.Punktelement')
class Punktelement(models.Model):
    geometrie = ili_field(models.PointField(srid=2056, null=False, blank=False), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Punktelement.Geometrie', qname='odmav_dmav_einzelobjekte_v1_1.Punktelement.Geometrie')
    symbol_ori = ili_field(models.FloatField(null=True, blank=True), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Punktelement.SymbolOri', qname='odmav_dmav_einzelobjekte_v1_1.Punktelement.SymbolOri')

    class Meta:
        db_table = 'odmav_dmav_einzelobjekte_v1_1__punktelement'

@interlis_model(oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Objektname', qname='odmav_dmav_einzelobjekte_v1_1.Objektname')
class Objektname(models.Model):
    name = ili_field(models.CharField(max_length=60, null=False, blank=False), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Objektname.Name', qname='odmav_dmav_einzelobjekte_v1_1.Objektname.Name')
    textposition = ili_field(models.MultiLineStringField(srid=2056, null=True, blank=True), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Objektname.Textposition', qname='odmav_dmav_einzelobjekte_v1_1.Objektname.Textposition')

    class Meta:
        db_table = 'odmav_dmav_einzelobjekte_v1_1__objektname'

@interlis_model(oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Objektnummer', qname='odmav_dmav_einzelobjekte_v1_1.Objektnummer')
class Objektnummer(models.Model):
    nummer = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Objektnummer.Nummer', qname='odmav_dmav_einzelobjekte_v1_1.Objektnummer.Nummer')
    textposition = ili_field(models.MultiLineStringField(srid=2056, null=True, blank=True), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Objektnummer.Textposition', qname='odmav_dmav_einzelobjekte_v1_1.Objektnummer.Textposition')

    class Meta:
        db_table = 'odmav_dmav_einzelobjekte_v1_1__objektnummer'

@interlis_model(oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Einzelobjekt', qname='odmav_dmav_einzelobjekte_v1_1.Einzelobjekt')
class Einzelobjekt(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_Einzelobjekte_V1_1.Einzelobjekte.Einzelobjekt.tid', qname='odmav_dmav_einzelobjekte_v1_1.Einzelobjekt.tid')
    qualitaetsstandard = ili_field(models.ForeignKey('odmav_dmav_einzelobjekte_v1_1.EinzelobjektQualitaetsstandardEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Einzelobjekt.Qualitaetsstandard', qname='odmav_dmav_einzelobjekte_v1_1.Einzelobjekt.Qualitaetsstandard')
    einzelobjektart = ili_field(models.ForeignKey('odmav_dmav_einzelobjekte_v1_1.EinzelobjektEinzelobjektartEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Einzelobjekt.Einzelobjektart', qname='odmav_dmav_einzelobjekte_v1_1.Einzelobjekt.Einzelobjektart')
    flaechenelement = ili_field(models.MultiSurfaceField(srid=2056, null=True, blank=True), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Einzelobjekt.Flaechenelement', qname='odmav_dmav_einzelobjekte_v1_1.Einzelobjekt.Flaechenelement')
    linienelement = ili_field(models.MultiLineStringField(srid=2056, null=True, blank=True), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Einzelobjekt.Linienelement', qname='odmav_dmav_einzelobjekte_v1_1.Einzelobjekt.Linienelement')
    punktelement = ili_field(models.MultiPointField(srid=2056, null=True, blank=True), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Einzelobjekt.Punktelement', qname='odmav_dmav_einzelobjekte_v1_1.Einzelobjekt.Punktelement')
    objektnummer = ili_field(models.MultiLineStringField(srid=2056, null=True, blank=True), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Einzelobjekt.Objektnummer', qname='odmav_dmav_einzelobjekte_v1_1.Einzelobjekt.Objektnummer')
    objektname = ili_field(models.MultiLineStringField(srid=2056, null=True, blank=True), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Einzelobjekt.Objektname', qname='odmav_dmav_einzelobjekte_v1_1.Einzelobjekt.Objektname')
    egid = ili_field(models.IntegerField(null=True, blank=True), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Einzelobjekt.EGID', qname='odmav_dmav_einzelobjekte_v1_1.Einzelobjekt.EGID')
    objektstatus = ili_field(models.ForeignKey('odmav_dmav_einzelobjekte_v1_1.EinzelobjektObjektstatusEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Einzelobjekt.Objektstatus', qname='odmav_dmav_einzelobjekte_v1_1.Einzelobjekt.Objektstatus')
    entstehung = ili_field(models.ForeignKey('odmav_dmav_einzelobjekte_v1_1.EONachfuehrung', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Entstehung_Einzelobjekt.Entstehung', qname='odmav_dmav_einzelobjekte_v1_1.Einzelobjekt.Entstehung')

    class Meta:
        db_table = 'odmav_dmav_einzelobjekte_v1_1__einzelobjekt'

@interlis_model(oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Messpunkt', qname='odmav_dmav_einzelobjekte_v1_1.Messpunkt')
class Messpunkt(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_Einzelobjekte_V1_1.Einzelobjekte.Messpunkt.tid', qname='odmav_dmav_einzelobjekte_v1_1.Messpunkt.tid')
    nummer = ili_field(models.CharField(max_length=12, null=True, blank=True), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Messpunkt.Nummer', qname='odmav_dmav_einzelobjekte_v1_1.Messpunkt.Nummer')
    geometrie = ili_field(models.PointField(srid=2056, null=False, blank=False), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Messpunkt.Geometrie', qname='odmav_dmav_einzelobjekte_v1_1.Messpunkt.Geometrie')
    hoehengeometrie = ili_field(models.FloatField(null=True, blank=True), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Messpunkt.Hoehengeometrie', qname='odmav_dmav_einzelobjekte_v1_1.Messpunkt.Hoehengeometrie')
    lagegenauigkeit = ili_field(models.FloatField(null=False, blank=False), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Messpunkt.Lagegenauigkeit', qname='odmav_dmav_einzelobjekte_v1_1.Messpunkt.Lagegenauigkeit')
    ist_lagezuverlaessig = ili_field(models.BooleanField(default=False), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Messpunkt.IstLagezuverlaessig', qname='odmav_dmav_einzelobjekte_v1_1.Messpunkt.IstLagezuverlaessig')
    hoehengenauigkeit = ili_field(models.FloatField(null=True, blank=True), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Messpunkt.Hoehengenauigkeit', qname='odmav_dmav_einzelobjekte_v1_1.Messpunkt.Hoehengenauigkeit')
    ist_hoehenzuverlaessig = ili_field(models.BooleanField(null=True, blank=True, default=None), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Messpunkt.IstHoehenzuverlaessig', qname='odmav_dmav_einzelobjekte_v1_1.Messpunkt.IstHoehenzuverlaessig')
    ist_exakt_definiert = ili_field(models.BooleanField(default=False), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Messpunkt.IstExaktDefiniert', qname='odmav_dmav_einzelobjekte_v1_1.Messpunkt.IstExaktDefiniert')
    entstehung = ili_field(models.ForeignKey('odmav_dmav_einzelobjekte_v1_1.EONachfuehrung', on_delete=models.PROTECT, related_name='+', null=True, blank=True), oid='DMAV_Einzelobjekte_V1_1.Einzelobjekte.Entstehung_Messpunkt.Entstehung', qname='odmav_dmav_einzelobjekte_v1_1.Messpunkt.Entstehung')

    class Meta:
        db_table = 'odmav_dmav_einzelobjekte_v1_1__messpunkt'
