"""Generated by ili2django. Do not edit manually."""

from django.contrib.gis.db import models

from ili2django.decorators import ili_field, interlis_model

@interlis_model(oid='KGK_Einzelobjekte_V1_0.Einzelobjekte.EO_Linienart.Art_ENUM', qname='odmav_kgk_einzelobjekte_v1_0.EO_LinienartArtEnum')
class EOLinienartArtEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='KGK_Einzelobjekte_V1_0.Einzelobjekte.EO_Linienart.Art_ENUM.code', qname='odmav_kgk_einzelobjekte_v1_0.EO_LinienartArtEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='KGK_Einzelobjekte_V1_0.Einzelobjekte.EO_Linienart.Art_ENUM.label', qname='odmav_kgk_einzelobjekte_v1_0.EO_LinienartArtEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['sichtbar_geschlossen_abgestuft', 'offen', 'unterirdisch', 'unterdrueckt_virtuell']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_kgk_einzelobjekte_v1_0__eolinienart_art_enum_value'

@interlis_model(oid='KGK_Einzelobjekte_V1_0.Einzelobjekte.Linienelement.Art_ENUM', qname='odmav_kgk_einzelobjekte_v1_0.LinienelementArtEnum')
class LinienelementArtEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='KGK_Einzelobjekte_V1_0.Einzelobjekte.Linienelement.Art_ENUM.code', qname='odmav_kgk_einzelobjekte_v1_0.LinienelementArtEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='KGK_Einzelobjekte_V1_0.Einzelobjekte.Linienelement.Art_ENUM.label', qname='odmav_kgk_einzelobjekte_v1_0.LinienelementArtEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['sichtbar_geschlossen_abgestuft', 'offen', 'unterirdisch', 'unterdrueckt_virtuell']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_kgk_einzelobjekte_v1_0__linienelement_art_enum_value'

@interlis_model(oid='KGK_Einzelobjekte_V1_0.Einzelobjekte.Einzelobjekt.Einzelobjektart_ENUM', qname='odmav_kgk_einzelobjekte_v1_0.EinzelobjektEinzelobjektartEnum')
class EinzelobjektEinzelobjektartEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='KGK_Einzelobjekte_V1_0.Einzelobjekte.Einzelobjekt.Einzelobjektart_ENUM.code', qname='odmav_kgk_einzelobjekte_v1_0.EinzelobjektEinzelobjektartEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='KGK_Einzelobjekte_V1_0.Einzelobjekte.Einzelobjekt.Einzelobjektart_ENUM.label', qname='odmav_kgk_einzelobjekte_v1_0.EinzelobjektEinzelobjektartEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['uebriger_Gebaeudeteil.uebriger_Gebaeudeteil', 'uebriger_Gebaeudeteil.Verladerampe', 'Bruecke_Passerelle.Bruecke_Passerelle', 'Bruecke_Passerelle.Bruecke', 'Bruecke_Passerelle.Passerelle', 'Silo_Turm_Gasometer.Silo_Turm_Gasometer', 'Silo_Turm_Gasometer.Fahrsilo']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_kgk_einzelobjekte_v1_0__einzelobjekt_einzelobj_1f7621c1f3'

@interlis_model(oid='KGK_Einzelobjekte_V1_0.Einzelobjekte.EO_Linienart', qname='odmav_kgk_einzelobjekte_v1_0.EO_Linienart')
class EOLinienart(models.Model):
    verlauf = ili_field(models.LineStringField(srid=2056, null=False, blank=False), oid='KGK_Einzelobjekte_V1_0.Einzelobjekte.EO_Linienart.Verlauf', qname='odmav_kgk_einzelobjekte_v1_0.EO_Linienart.Verlauf')
    art = ili_field(models.ForeignKey('odmav_kgk_einzelobjekte_v1_0.EOLinienartArtEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='KGK_Einzelobjekte_V1_0.Einzelobjekte.EO_Linienart.Art', qname='odmav_kgk_einzelobjekte_v1_0.EO_Linienart.Art')

    class Meta:
        db_table = 'odmav_kgk_einzelobjekte_v1_0__eolinienart'

@interlis_model(oid='KGK_Einzelobjekte_V1_0.Einzelobjekte.Flaechenelement', qname='odmav_kgk_einzelobjekte_v1_0.Flaechenelement')
class Flaechenelement(models.Model):
    linienattribute = ili_field(models.MultiLineStringField(srid=2056, null=True, blank=True), oid='KGK_Einzelobjekte_V1_0.Einzelobjekte.Flaechenelement.Linienattribute', qname='odmav_kgk_einzelobjekte_v1_0.Flaechenelement.Linienattribute')

    class Meta:
        db_table = 'odmav_kgk_einzelobjekte_v1_0__flaechenelement'

@interlis_model(oid='KGK_Einzelobjekte_V1_0.Einzelobjekte.Linienelement', qname='odmav_kgk_einzelobjekte_v1_0.Linienelement')
class Linienelement(models.Model):
    art = ili_field(models.ForeignKey('odmav_kgk_einzelobjekte_v1_0.LinienelementArtEnumValue', on_delete=models.PROTECT, related_name='+', null=True, blank=True), oid='KGK_Einzelobjekte_V1_0.Einzelobjekte.Linienelement.Art', qname='odmav_kgk_einzelobjekte_v1_0.Linienelement.Art')

    class Meta:
        db_table = 'odmav_kgk_einzelobjekte_v1_0__linienelement'

@interlis_model(oid='KGK_Einzelobjekte_V1_0.Einzelobjekte.Einzelobjekt', qname='odmav_kgk_einzelobjekte_v1_0.Einzelobjekt')
class Einzelobjekt(models.Model):
    einzelobjektart = ili_field(models.ForeignKey('odmav_kgk_einzelobjekte_v1_0.EinzelobjektEinzelobjektartEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='KGK_Einzelobjekte_V1_0.Einzelobjekte.Einzelobjekt.Einzelobjektart', qname='odmav_kgk_einzelobjekte_v1_0.Einzelobjekt.Einzelobjektart')
    flaechenelement = ili_field(models.MultiLineStringField(srid=2056, null=True, blank=True), oid='KGK_Einzelobjekte_V1_0.Einzelobjekte.Einzelobjekt.Flaechenelement', qname='odmav_kgk_einzelobjekte_v1_0.Einzelobjekt.Flaechenelement')
    linienelement = ili_field(models.JSONField(default=list, null=True, blank=True), oid='KGK_Einzelobjekte_V1_0.Einzelobjekte.Einzelobjekt.Linienelement', qname='odmav_kgk_einzelobjekte_v1_0.Einzelobjekt.Linienelement')

    class Meta:
        db_table = 'odmav_kgk_einzelobjekte_v1_0__einzelobjekt'
