"""Generated by ili2django. Do not edit manually."""

from django.contrib.gis.db import models

from ili2django.decorators import ili_field, interlis_model

@interlis_model(oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Medium', qname='odmav_dmav_rohrleitungen_v1_1.Medium')
class MediumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Medium.code', qname='odmav_dmav_rohrleitungen_v1_1.Medium.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Medium.label', qname='odmav_dmav_rohrleitungen_v1_1.Medium.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['Oel', 'Gas', 'weitere']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_rohrleitungen_v1_1__medium_value'

@interlis_model(oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Leitungsobjekt.Qualitaetsstandard_ENUM', qname='odmav_dmav_rohrleitungen_v1_1.LeitungsobjektQualitaetsstandardEnum')
class LeitungsobjektQualitaetsstandardEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Leitungsobjekt.Qualitaetsstandard_ENUM.code', qname='odmav_dmav_rohrleitungen_v1_1.LeitungsobjektQualitaetsstandardEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Leitungsobjekt.Qualitaetsstandard_ENUM.label', qname='odmav_dmav_rohrleitungen_v1_1.LeitungsobjektQualitaetsstandardEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['AV93', 'PN']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_rohrleitungen_v1_1__leitungsobjekt_qualit_df64c88ae4'

@interlis_model(oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Leitungsobjekt.Medium_ENUM', qname='odmav_dmav_rohrleitungen_v1_1.LeitungsobjektMediumEnum')
class LeitungsobjektMediumEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Leitungsobjekt.Medium_ENUM.code', qname='odmav_dmav_rohrleitungen_v1_1.LeitungsobjektMediumEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Leitungsobjekt.Medium_ENUM.label', qname='odmav_dmav_rohrleitungen_v1_1.LeitungsobjektMediumEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['Oel', 'Gas', 'weitere']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_rohrleitungen_v1_1__leitungsobjekt_medium_enum_value'

@interlis_model(oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Leitungsobjekt.Objektstatus_ENUM', qname='odmav_dmav_rohrleitungen_v1_1.LeitungsobjektObjektstatusEnum')
class LeitungsobjektObjektstatusEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Leitungsobjekt.Objektstatus_ENUM.code', qname='odmav_dmav_rohrleitungen_v1_1.LeitungsobjektObjektstatusEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Leitungsobjekt.Objektstatus_ENUM.label', qname='odmav_dmav_rohrleitungen_v1_1.LeitungsobjektObjektstatusEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['projektiert', 'real', 'vergangen']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_rohrleitungen_v1_1__leitungsobjekt_objekt_b9edfca6dd'

@interlis_model(oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Signal.Qualitaetsstandard_ENUM', qname='odmav_dmav_rohrleitungen_v1_1.SignalQualitaetsstandardEnum')
class SignalQualitaetsstandardEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Signal.Qualitaetsstandard_ENUM.code', qname='odmav_dmav_rohrleitungen_v1_1.SignalQualitaetsstandardEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Signal.Qualitaetsstandard_ENUM.label', qname='odmav_dmav_rohrleitungen_v1_1.SignalQualitaetsstandardEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['AV93', 'PN']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_rohrleitungen_v1_1__signal_qualitaetsstan_3c6fc2b95d'

@interlis_model(oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Signal.Medium_ENUM', qname='odmav_dmav_rohrleitungen_v1_1.SignalMediumEnum')
class SignalMediumEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Signal.Medium_ENUM.code', qname='odmav_dmav_rohrleitungen_v1_1.SignalMediumEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Signal.Medium_ENUM.label', qname='odmav_dmav_rohrleitungen_v1_1.SignalMediumEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['Oel', 'Gas', 'weitere']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_rohrleitungen_v1_1__signal_medium_enum_value'

@interlis_model(oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Signal.Objektstatus_ENUM', qname='odmav_dmav_rohrleitungen_v1_1.SignalObjektstatusEnum')
class SignalObjektstatusEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Signal.Objektstatus_ENUM.code', qname='odmav_dmav_rohrleitungen_v1_1.SignalObjektstatusEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Signal.Objektstatus_ENUM.label', qname='odmav_dmav_rohrleitungen_v1_1.SignalObjektstatusEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['projektiert', 'real', 'vergangen']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_rohrleitungen_v1_1__signal_objektstatus_enum_value'

@interlis_model(oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Signal.Signalart_ENUM', qname='odmav_dmav_rohrleitungen_v1_1.SignalSignalartEnum')
class SignalSignalartEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Signal.Signalart_ENUM.code', qname='odmav_dmav_rohrleitungen_v1_1.SignalSignalartEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Signal.Signalart_ENUM.label', qname='odmav_dmav_rohrleitungen_v1_1.SignalSignalartEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['Signal', 'Tafel_Stein', 'weitere']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_rohrleitungen_v1_1__signal_signalart_enum_value'

@interlis_model(oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.RLNachfuehrung', qname='odmav_dmav_rohrleitungen_v1_1.RLNachfuehrung')
class RLNachfuehrung(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_Rohrleitungen_V1_1.Rohrleitungen.RLNachfuehrung.tid', qname='odmav_dmav_rohrleitungen_v1_1.RLNachfuehrung.tid')
    nbident = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.RLNachfuehrung.NBIdent', qname='odmav_dmav_rohrleitungen_v1_1.RLNachfuehrung.NBIdent')
    identifikator = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.RLNachfuehrung.Identifikator', qname='odmav_dmav_rohrleitungen_v1_1.RLNachfuehrung.Identifikator')
    beschreibung = ili_field(models.CharField(max_length=60, null=False, blank=False), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.RLNachfuehrung.Beschreibung', qname='odmav_dmav_rohrleitungen_v1_1.RLNachfuehrung.Beschreibung')
    perimeter = ili_field(models.CurvePolygonField(srid=2056, null=True, blank=True), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.RLNachfuehrung.Perimeter', qname='odmav_dmav_rohrleitungen_v1_1.RLNachfuehrung.Perimeter')
    gueltiger_eintrag = ili_field(models.CharField(max_length=255, null=False, blank=False), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.RLNachfuehrung.GueltigerEintrag', qname='odmav_dmav_rohrleitungen_v1_1.RLNachfuehrung.GueltigerEintrag')

    class Meta:
        db_table = 'odmav_dmav_rohrleitungen_v1_1__rlnachfuehrung'

@interlis_model(oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Flaechenelement', qname='odmav_dmav_rohrleitungen_v1_1.Flaechenelement')
class Flaechenelement(models.Model):
    geometrie = ili_field(models.CurvePolygonField(srid=2056, null=False, blank=False), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Flaechenelement.Geometrie', qname='odmav_dmav_rohrleitungen_v1_1.Flaechenelement.Geometrie')
    sichtbar = ili_field(models.MultiLineStringField(srid=2056, null=True, blank=True), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Flaechenelement.Sichtbar', qname='odmav_dmav_rohrleitungen_v1_1.Flaechenelement.Sichtbar')

    class Meta:
        db_table = 'odmav_dmav_rohrleitungen_v1_1__flaechenelement'

@interlis_model(oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Linienelement', qname='odmav_dmav_rohrleitungen_v1_1.Linienelement')
class Linienelement(models.Model):
    geometrie = ili_field(models.LineStringField(srid=2056, null=False, blank=False), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Linienelement.Geometrie', qname='odmav_dmav_rohrleitungen_v1_1.Linienelement.Geometrie')
    ist_sichtbar = ili_field(models.BooleanField(default=False), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Linienelement.IstSichtbar', qname='odmav_dmav_rohrleitungen_v1_1.Linienelement.IstSichtbar')

    class Meta:
        db_table = 'odmav_dmav_rohrleitungen_v1_1__linienelement'

@interlis_model(oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Punktelement', qname='odmav_dmav_rohrleitungen_v1_1.Punktelement')
class Punktelement(models.Model):
    geometrie = ili_field(models.PointField(srid=2056, null=False, blank=False), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Punktelement.Geometrie', qname='odmav_dmav_rohrleitungen_v1_1.Punktelement.Geometrie')
    hoehengeometrie = ili_field(models.FloatField(null=True, blank=True), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Punktelement.Hoehengeometrie', qname='odmav_dmav_rohrleitungen_v1_1.Punktelement.Hoehengeometrie')
    symbol_ori = ili_field(models.FloatField(null=False, blank=False), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Punktelement.SymbolOri', qname='odmav_dmav_rohrleitungen_v1_1.Punktelement.SymbolOri')

    class Meta:
        db_table = 'odmav_dmav_rohrleitungen_v1_1__punktelement'

@interlis_model(oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Leitungsobjekt', qname='odmav_dmav_rohrleitungen_v1_1.Leitungsobjekt')
class Leitungsobjekt(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_Rohrleitungen_V1_1.Rohrleitungen.Leitungsobjekt.tid', qname='odmav_dmav_rohrleitungen_v1_1.Leitungsobjekt.tid')
    betreiber = ili_field(models.CharField(max_length=30, null=False, blank=False), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Leitungsobjekt.Betreiber', qname='odmav_dmav_rohrleitungen_v1_1.Leitungsobjekt.Betreiber')
    qualitaetsstandard = ili_field(models.ForeignKey('odmav_dmav_rohrleitungen_v1_1.LeitungsobjektQualitaetsstandardEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Leitungsobjekt.Qualitaetsstandard', qname='odmav_dmav_rohrleitungen_v1_1.Leitungsobjekt.Qualitaetsstandard')
    medium = ili_field(models.ForeignKey('odmav_dmav_rohrleitungen_v1_1.LeitungsobjektMediumEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Leitungsobjekt.Medium', qname='odmav_dmav_rohrleitungen_v1_1.Leitungsobjekt.Medium')
    objektstatus = ili_field(models.ForeignKey('odmav_dmav_rohrleitungen_v1_1.LeitungsobjektObjektstatusEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Leitungsobjekt.Objektstatus', qname='odmav_dmav_rohrleitungen_v1_1.Leitungsobjekt.Objektstatus')
    flaechenelement = ili_field(models.MultiSurfaceField(srid=2056, null=True, blank=True), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Leitungsobjekt.Flaechenelement', qname='odmav_dmav_rohrleitungen_v1_1.Leitungsobjekt.Flaechenelement')
    linienelement = ili_field(models.MultiLineStringField(srid=2056, null=True, blank=True), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Leitungsobjekt.Linienelement', qname='odmav_dmav_rohrleitungen_v1_1.Leitungsobjekt.Linienelement')
    punktelement = ili_field(models.MultiPointField(srid=2056, null=True, blank=True), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Leitungsobjekt.Punktelement', qname='odmav_dmav_rohrleitungen_v1_1.Leitungsobjekt.Punktelement')
    textposition = ili_field(models.MultiLineStringField(srid=2056, null=True, blank=True), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Leitungsobjekt.Textposition', qname='odmav_dmav_rohrleitungen_v1_1.Leitungsobjekt.Textposition')
    entstehung = ili_field(models.ForeignKey('odmav_dmav_rohrleitungen_v1_1.RLNachfuehrung', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Entstehung_Leitungsobjekt.Entstehung', qname='odmav_dmav_rohrleitungen_v1_1.Leitungsobjekt.Entstehung')

    class Meta:
        db_table = 'odmav_dmav_rohrleitungen_v1_1__leitungsobjekt'

@interlis_model(oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Signal', qname='odmav_dmav_rohrleitungen_v1_1.Signal')
class Signal(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_Rohrleitungen_V1_1.Rohrleitungen.Signal.tid', qname='odmav_dmav_rohrleitungen_v1_1.Signal.tid')
    nummer = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Signal.Nummer', qname='odmav_dmav_rohrleitungen_v1_1.Signal.Nummer')
    betreiber = ili_field(models.CharField(max_length=30, null=False, blank=False), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Signal.Betreiber', qname='odmav_dmav_rohrleitungen_v1_1.Signal.Betreiber')
    geometrie = ili_field(models.PointField(srid=2056, null=False, blank=False), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Signal.Geometrie', qname='odmav_dmav_rohrleitungen_v1_1.Signal.Geometrie')
    qualitaetsstandard = ili_field(models.ForeignKey('odmav_dmav_rohrleitungen_v1_1.SignalQualitaetsstandardEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Signal.Qualitaetsstandard', qname='odmav_dmav_rohrleitungen_v1_1.Signal.Qualitaetsstandard')
    medium = ili_field(models.ForeignKey('odmav_dmav_rohrleitungen_v1_1.SignalMediumEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Signal.Medium', qname='odmav_dmav_rohrleitungen_v1_1.Signal.Medium')
    objektstatus = ili_field(models.ForeignKey('odmav_dmav_rohrleitungen_v1_1.SignalObjektstatusEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Signal.Objektstatus', qname='odmav_dmav_rohrleitungen_v1_1.Signal.Objektstatus')
    signalart = ili_field(models.ForeignKey('odmav_dmav_rohrleitungen_v1_1.SignalSignalartEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Signal.Signalart', qname='odmav_dmav_rohrleitungen_v1_1.Signal.Signalart')
    symbol_ori = ili_field(models.FloatField(null=True, blank=True), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Signal.SymbolOri', qname='odmav_dmav_rohrleitungen_v1_1.Signal.SymbolOri')
    textposition = ili_field(models.MultiLineStringField(srid=2056, null=True, blank=True), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Signal.Textposition', qname='odmav_dmav_rohrleitungen_v1_1.Signal.Textposition')
    entstehung = ili_field(models.ForeignKey('odmav_dmav_rohrleitungen_v1_1.RLNachfuehrung', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Entstehung_Signal.Entstehung', qname='odmav_dmav_rohrleitungen_v1_1.Signal.Entstehung')

    class Meta:
        db_table = 'odmav_dmav_rohrleitungen_v1_1__signal'

@interlis_model(oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Messpunkt', qname='odmav_dmav_rohrleitungen_v1_1.Messpunkt')
class Messpunkt(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_Rohrleitungen_V1_1.Rohrleitungen.Messpunkt.tid', qname='odmav_dmav_rohrleitungen_v1_1.Messpunkt.tid')
    nummer = ili_field(models.CharField(max_length=12, null=True, blank=True), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Messpunkt.Nummer', qname='odmav_dmav_rohrleitungen_v1_1.Messpunkt.Nummer')
    geometrie = ili_field(models.PointField(srid=2056, null=False, blank=False), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Messpunkt.Geometrie', qname='odmav_dmav_rohrleitungen_v1_1.Messpunkt.Geometrie')
    hoehengeometrie = ili_field(models.FloatField(null=True, blank=True), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Messpunkt.Hoehengeometrie', qname='odmav_dmav_rohrleitungen_v1_1.Messpunkt.Hoehengeometrie')
    lagegenauigkeit = ili_field(models.FloatField(null=False, blank=False), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Messpunkt.Lagegenauigkeit', qname='odmav_dmav_rohrleitungen_v1_1.Messpunkt.Lagegenauigkeit')
    ist_lagezuverlaessig = ili_field(models.BooleanField(default=False), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Messpunkt.IstLagezuverlaessig', qname='odmav_dmav_rohrleitungen_v1_1.Messpunkt.IstLagezuverlaessig')
    hoehengenauigkeit = ili_field(models.FloatField(null=True, blank=True), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Messpunkt.Hoehengenauigkeit', qname='odmav_dmav_rohrleitungen_v1_1.Messpunkt.Hoehengenauigkeit')
    ist_hoehenzuverlaessig = ili_field(models.BooleanField(null=True, blank=True, default=None), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Messpunkt.IstHoehenzuverlaessig', qname='odmav_dmav_rohrleitungen_v1_1.Messpunkt.IstHoehenzuverlaessig')
    ist_exakt_definiert = ili_field(models.BooleanField(default=False), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Messpunkt.IstExaktDefiniert', qname='odmav_dmav_rohrleitungen_v1_1.Messpunkt.IstExaktDefiniert')
    entstehung = ili_field(models.ForeignKey('odmav_dmav_rohrleitungen_v1_1.RLNachfuehrung', on_delete=models.PROTECT, related_name='+', null=True, blank=True), oid='DMAV_Rohrleitungen_V1_1.Rohrleitungen.Entstehung_Messpunkt.Entstehung', qname='odmav_dmav_rohrleitungen_v1_1.Messpunkt.Entstehung')

    class Meta:
        db_table = 'odmav_dmav_rohrleitungen_v1_1__messpunkt'
