"""Generated by ili2django. Do not edit manually."""

from django.contrib.gis.db import models

from ili2django.decorators import ili_field, interlis_model

@interlis_model(oid='Dictionaries_V2.Dictionaries.Dictionary.Language_ENUM', qname='odmav_dictionaries_v2.DictionaryLanguageEnum')
class DictionaryLanguageEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='Dictionaries_V2.Dictionaries.Dictionary.Language_ENUM.code', qname='odmav_dictionaries_v2.DictionaryLanguageEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='Dictionaries_V2.Dictionaries.Dictionary.Language_ENUM.label', qname='odmav_dictionaries_v2.DictionaryLanguageEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['de', 'fr', 'it', 'rm', 'en', 'aa', 'ab', 'af', 'am', 'ar', 'as', 'ay', 'az', 'ba', 'be', 'bg', 'bh', 'bi', 'bn', 'bo', 'br', 'ca', 'co', 'cs', 'cy', 'da', 'dz', 'el', 'eo', 'es', 'et', 'eu', 'fa', 'fi', 'fj', 'fo', 'fy', 'ga', 'gd', 'gl', 'gn', 'gu', 'ha', 'he', 'hi', 'hr', 'hu', 'hy', 'ia', 'id', 'ie', 'ik', 'is', 'iu', 'ja', 'jw', 'ka', 'kk', 'kl', 'km', 'kn', 'ko', 'ks', 'ku', 'ky', 'la', 'ln', 'lo', 'lt', 'lv', 'mg', 'mi', 'mk', 'ml', 'mn', 'mo', 'mr', 'ms', 'mt', 'my', 'na', 'ne', 'nl', 'no', 'oc', 'om', 'or', 'pa', 'pl', 'ps', 'pt', 'qu', 'rn', 'ro', 'ru', 'rw', 'sa', 'sd', 'sg', 'sh', 'si', 'sk', 'sl', 'sm', 'sn', 'so', 'sq', 'sr', 'ss', 'st', 'su', 'sv', 'sw', 'ta', 'te', 'tg', 'th', 'ti', 'tk', 'tl', 'tn', 'to', 'tr', 'ts', 'tt', 'tw', 'ug', 'uk', 'ur', 'uz', 'vi', 'vo', 'wo', 'xh', 'yi', 'yo', 'za', 'zh', 'zu']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dictionaries_v2__dictionary_language_enum_value'

@interlis_model(oid='Dictionaries_V2.Dictionaries.Entry', qname='odmav_dictionaries_v2.Entry')
class Entry(models.Model):
    text = ili_field(models.CharField(max_length=255, null=False, blank=False), oid='Dictionaries_V2.Dictionaries.Entry.Text', qname='odmav_dictionaries_v2.Entry.Text')

    class Meta:
        abstract = True
        db_table = 'odmav_dictionaries_v2__entry'

@interlis_model(oid='Dictionaries_V2.Dictionaries.Dictionary', qname='odmav_dictionaries_v2.Dictionary')
class Dictionary(models.Model):
    language = ili_field(models.ForeignKey('odmav_dictionaries_v2.DictionaryLanguageEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='Dictionaries_V2.Dictionaries.Dictionary.Language', qname='odmav_dictionaries_v2.Dictionary.Language')
    entries = ili_field(models.JSONField(default=list, null=True, blank=True), oid='Dictionaries_V2.Dictionaries.Dictionary.Entries', qname='odmav_dictionaries_v2.Dictionary.Entries')

    class Meta:
        db_table = 'odmav_dictionaries_v2__dictionary'
