"""Generated by ili2django. Do not edit manually."""

from django.contrib.gis.db import models

from ili2django.decorators import ili_field, interlis_model

@interlis_model(oid='AdministrativeUnits_V2.Countries.Country.Code_ENUM', qname='odmav_administrative_units_v2.CountryCodeEnum')
class CountryCodeEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='AdministrativeUnits_V2.Countries.Country.Code_ENUM.code', qname='odmav_administrative_units_v2.CountryCodeEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='AdministrativeUnits_V2.Countries.Country.Code_ENUM.label', qname='odmav_administrative_units_v2.CountryCodeEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['CHE', 'ABW', 'AFG', 'AGO', 'AIA', 'ALA', 'ALB', 'AND_', 'ANT', 'ARE', 'ARG', 'ARM', 'ASM', 'ATA', 'ATF', 'ATG', 'AUS', 'AUT', 'AZE', 'BDI', 'BEL', 'BEN', 'BFA', 'BGD', 'BGR', 'BHR', 'BHS', 'BIH', 'BLR', 'BLZ', 'BMU', 'BOL', 'BRA', 'BRB', 'BRN', 'BTN', 'BVT', 'BWA', 'CAF', 'CAN', 'CCK', 'CHL', 'CHN', 'CIV', 'CMR', 'COD', 'COG', 'COK', 'COL', 'COM', 'CPV', 'CRI', 'CUB', 'CXR', 'CYM', 'CYP', 'CZE', 'DEU', 'DJI', 'DMA', 'DNK', 'DOM', 'DZA', 'ECU', 'EGY', 'ERI', 'ESH', 'ESP', 'EST', 'ETH', 'FIN', 'FJI', 'FLK', 'FRA', 'FRO', 'FSM', 'GAB', 'GBR', 'GEO', 'GGY', 'GHA', 'GIB', 'GIN', 'GLP', 'GMB', 'GNB', 'GNQ', 'GRC', 'GRD', 'GRL', 'GTM', 'GUF', 'GUM', 'GUY', 'HKG', 'HMD', 'HND', 'HRV', 'HTI', 'HUN', 'IDN', 'IMN', 'IND', 'IOT', 'IRL', 'IRN', 'IRQ', 'ISL', 'ISR', 'ITA', 'JAM', 'JEY', 'JOR', 'JPN', 'KAZ', 'KEN', 'KGZ', 'KHM', 'KIR', 'KNA', 'KOR', 'KWT', 'LAO', 'LBN', 'LBR', 'LBY', 'LCA', 'LIE', 'LKA', 'LSO', 'LTU', 'LUX', 'LVA', 'MAC', 'MAR', 'MCO', 'MDA', 'MDG', 'MDV', 'MEX', 'MHL', 'MKD', 'MLI', 'MLT', 'MMR', 'MNE', 'MNG', 'MNP', 'MOZ', 'MRT', 'MSR', 'MTQ', 'MUS', 'MWI', 'MYS', 'MYT', 'NAM', 'NCL', 'NER', 'NFK', 'NGA', 'NIC', 'NIU', 'NLD', 'NOR', 'NPL', 'NRU', 'NZL', 'OMN', 'PAK', 'PAN', 'PCN', 'PER', 'PHL', 'PLW', 'PNG', 'POL', 'PRI', 'PRK', 'PRT', 'PRY', 'PSE', 'PYF', 'QAT', 'REU', 'ROU', 'RUS', 'RWA', 'SAU', 'SDN', 'SEN', 'SGP', 'SGS', 'SHN', 'SJM', 'SLB', 'SLE', 'SLV', 'SMR', 'SOM', 'SPM', 'SRB', 'STP', 'SUR', 'SVK', 'SVN', 'SWE', 'SWZ', 'SYC', 'SYR', 'TCA', 'TCD', 'TGO', 'THA', 'TJK', 'TKL', 'TKM', 'TLS', 'TON', 'TTO', 'TUN', 'TUR', 'TUV', 'TWN', 'TZA', 'UGA', 'UKR', 'UMI', 'URY', 'USA', 'UZB', 'VAT', 'VCT', 'VEN', 'VGB', 'VIR', 'VNM', 'VUT', 'WLF', 'WSM', 'YEM', 'ZAF', 'ZMB', 'ZWE']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_administrative_units_v2__country_code_enum_value'

@interlis_model(oid='AdministrativeUnits_V2.CountryNames.CountryName.Code_ENUM', qname='odmav_administrative_units_v2.CountryNameCodeEnum')
class CountryNameCodeEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='AdministrativeUnits_V2.CountryNames.CountryName.Code_ENUM.code', qname='odmav_administrative_units_v2.CountryNameCodeEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='AdministrativeUnits_V2.CountryNames.CountryName.Code_ENUM.label', qname='odmav_administrative_units_v2.CountryNameCodeEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['CHE', 'ABW', 'AFG', 'AGO', 'AIA', 'ALA', 'ALB', 'AND_', 'ANT', 'ARE', 'ARG', 'ARM', 'ASM', 'ATA', 'ATF', 'ATG', 'AUS', 'AUT', 'AZE', 'BDI', 'BEL', 'BEN', 'BFA', 'BGD', 'BGR', 'BHR', 'BHS', 'BIH', 'BLR', 'BLZ', 'BMU', 'BOL', 'BRA', 'BRB', 'BRN', 'BTN', 'BVT', 'BWA', 'CAF', 'CAN', 'CCK', 'CHL', 'CHN', 'CIV', 'CMR', 'COD', 'COG', 'COK', 'COL', 'COM', 'CPV', 'CRI', 'CUB', 'CXR', 'CYM', 'CYP', 'CZE', 'DEU', 'DJI', 'DMA', 'DNK', 'DOM', 'DZA', 'ECU', 'EGY', 'ERI', 'ESH', 'ESP', 'EST', 'ETH', 'FIN', 'FJI', 'FLK', 'FRA', 'FRO', 'FSM', 'GAB', 'GBR', 'GEO', 'GGY', 'GHA', 'GIB', 'GIN', 'GLP', 'GMB', 'GNB', 'GNQ', 'GRC', 'GRD', 'GRL', 'GTM', 'GUF', 'GUM', 'GUY', 'HKG', 'HMD', 'HND', 'HRV', 'HTI', 'HUN', 'IDN', 'IMN', 'IND', 'IOT', 'IRL', 'IRN', 'IRQ', 'ISL', 'ISR', 'ITA', 'JAM', 'JEY', 'JOR', 'JPN', 'KAZ', 'KEN', 'KGZ', 'KHM', 'KIR', 'KNA', 'KOR', 'KWT', 'LAO', 'LBN', 'LBR', 'LBY', 'LCA', 'LIE', 'LKA', 'LSO', 'LTU', 'LUX', 'LVA', 'MAC', 'MAR', 'MCO', 'MDA', 'MDG', 'MDV', 'MEX', 'MHL', 'MKD', 'MLI', 'MLT', 'MMR', 'MNE', 'MNG', 'MNP', 'MOZ', 'MRT', 'MSR', 'MTQ', 'MUS', 'MWI', 'MYS', 'MYT', 'NAM', 'NCL', 'NER', 'NFK', 'NGA', 'NIC', 'NIU', 'NLD', 'NOR', 'NPL', 'NRU', 'NZL', 'OMN', 'PAK', 'PAN', 'PCN', 'PER', 'PHL', 'PLW', 'PNG', 'POL', 'PRI', 'PRK', 'PRT', 'PRY', 'PSE', 'PYF', 'QAT', 'REU', 'ROU', 'RUS', 'RWA', 'SAU', 'SDN', 'SEN', 'SGP', 'SGS', 'SHN', 'SJM', 'SLB', 'SLE', 'SLV', 'SMR', 'SOM', 'SPM', 'SRB', 'STP', 'SUR', 'SVK', 'SVN', 'SWE', 'SWZ', 'SYC', 'SYR', 'TCA', 'TCD', 'TGO', 'THA', 'TJK', 'TKL', 'TKM', 'TLS', 'TON', 'TTO', 'TUN', 'TUR', 'TUV', 'TWN', 'TZA', 'UGA', 'UKR', 'UMI', 'URY', 'USA', 'UZB', 'VAT', 'VCT', 'VEN', 'VGB', 'VIR', 'VNM', 'VUT', 'WLF', 'WSM', 'YEM', 'ZAF', 'ZMB', 'ZWE']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_administrative_units_v2__country_name_code_enum_value'

@interlis_model(oid='AdministrativeUnits_V2.AdministrativeUnits.AdministrativeElement', qname='odmav_administrative_units_v2.AdministrativeElement')
class AdministrativeElement(models.Model):
    pass

    class Meta:
        abstract = True
        db_table = 'odmav_administrative_units_v2__administrative_element'

@interlis_model(oid='AdministrativeUnits_V2.AdministrativeUnits.AdministrativeUnit', qname='odmav_administrative_units_v2.AdministrativeUnit')
class AdministrativeUnit(models.Model):
    upper_level_unit = ili_field(models.ForeignKey('odmav_administrative_units_v2.AdministrativeUnit', on_delete=models.PROTECT, related_name='+', null=True, blank=True), oid='AdministrativeUnits_V2.AdministrativeUnits.Hierarchy.UpperLevelUnit', qname='odmav_administrative_units_v2.AdministrativeUnit.UpperLevelUnit')

    class Meta:
        db_table = 'odmav_administrative_units_v2__administrative_unit'

@interlis_model(oid='AdministrativeUnits_V2.AdministrativeUnits.AdministrativeUnion', qname='odmav_administrative_units_v2.AdministrativeUnion')
class AdministrativeUnion(models.Model):
    pass

    class Meta:
        db_table = 'odmav_administrative_units_v2__administrative_union'

@interlis_model(oid='AdministrativeUnits_V2.AdministrativeUnits.Hierarchy', qname='odmav_administrative_units_v2.Hierarchy')
class Hierarchy(models.Model):
    upper_level_unit = ili_field(models.ForeignKey('odmav_administrative_units_v2.AdministrativeUnit', on_delete=models.PROTECT, related_name='+', null=True, blank=True), oid='AdministrativeUnits_V2.AdministrativeUnits.Hierarchy.UpperLevelUnit', qname='odmav_administrative_units_v2.Hierarchy.UpperLevelUnit')
    lower_level_unit = ili_field(models.JSONField(default=list, null=True, blank=True), oid='AdministrativeUnits_V2.AdministrativeUnits.Hierarchy.LowerLevelUnit', qname='odmav_administrative_units_v2.Hierarchy.LowerLevelUnit')

    class Meta:
        db_table = 'odmav_administrative_units_v2__hierarchy'

@interlis_model(oid='AdministrativeUnits_V2.AdministrativeUnits.UnionMembers', qname='odmav_administrative_units_v2.UnionMembers')
class UnionMembers(models.Model):
    union = ili_field(models.JSONField(default=list, null=True, blank=True), oid='AdministrativeUnits_V2.AdministrativeUnits.UnionMembers.Union', qname='odmav_administrative_units_v2.UnionMembers.Union')
    member = ili_field(models.JSONField(default=list, null=True, blank=True), oid='AdministrativeUnits_V2.AdministrativeUnits.UnionMembers.Member', qname='odmav_administrative_units_v2.UnionMembers.Member')

    class Meta:
        db_table = 'odmav_administrative_units_v2__union_members'

@interlis_model(oid='AdministrativeUnits_V2.Countries.Country', qname='odmav_administrative_units_v2.Country')
class Country(models.Model):
    code = ili_field(models.ForeignKey('odmav_administrative_units_v2.CountryCodeEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='AdministrativeUnits_V2.Countries.Country.Code', qname='odmav_administrative_units_v2.Country.Code')

    class Meta:
        db_table = 'odmav_administrative_units_v2__country'

@interlis_model(oid='AdministrativeUnits_V2.CountryNames.CountryName', qname='odmav_administrative_units_v2.CountryName')
class CountryName(models.Model):
    code = ili_field(models.ForeignKey('odmav_administrative_units_v2.CountryNameCodeEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='AdministrativeUnits_V2.CountryNames.CountryName.Code', qname='odmav_administrative_units_v2.CountryName.Code')

    class Meta:
        db_table = 'odmav_administrative_units_v2__country_name'

@interlis_model(oid='AdministrativeUnits_V2.CountryNames.CountryNamesTranslation', qname='odmav_administrative_units_v2.CountryNamesTranslation')
class CountryNamesTranslation(models.Model):
    entries = ili_field(models.JSONField(default=list, null=True, blank=True), oid='AdministrativeUnits_V2.CountryNames.CountryNamesTranslation.Entries', qname='odmav_administrative_units_v2.CountryNamesTranslation.Entries')

    class Meta:
        db_table = 'odmav_administrative_units_v2__country_names_translation'

@interlis_model(oid='AdministrativeUnits_V2.Agencies.Agency', qname='odmav_administrative_units_v2.Agency')
class Agency(models.Model):
    supervisor = ili_field(models.CharField(max_length=255, null=False, blank=False), oid='AdministrativeUnits_V2.Agencies.Authority.Supervisor', qname='odmav_administrative_units_v2.Agency.Supervisor')

    class Meta:
        abstract = True
        db_table = 'odmav_administrative_units_v2__agency'

@interlis_model(oid='AdministrativeUnits_V2.Agencies.Authority', qname='odmav_administrative_units_v2.Authority')
class Authority(models.Model):
    supervisor = ili_field(models.CharField(max_length=255, null=False, blank=False), oid='AdministrativeUnits_V2.Agencies.Authority.Supervisor', qname='odmav_administrative_units_v2.Authority.Supervisor')
    agency = ili_field(models.JSONField(default=list, null=True, blank=True), oid='AdministrativeUnits_V2.Agencies.Authority.Agency', qname='odmav_administrative_units_v2.Authority.Agency')

    class Meta:
        db_table = 'odmav_administrative_units_v2__authority'

@interlis_model(oid='AdministrativeUnits_V2.Agencies.Organisation', qname='odmav_administrative_units_v2.Organisation')
class Organisation(models.Model):
    orderer = ili_field(models.JSONField(default=list, null=True, blank=True), oid='AdministrativeUnits_V2.Agencies.Organisation.Orderer', qname='odmav_administrative_units_v2.Organisation.Orderer')
    executor = ili_field(models.JSONField(default=list, null=True, blank=True), oid='AdministrativeUnits_V2.Agencies.Organisation.Executor', qname='odmav_administrative_units_v2.Organisation.Executor')

    class Meta:
        db_table = 'odmav_administrative_units_v2__organisation'
