"""Generated by ili2django. Do not edit manually."""

from django.contrib.gis.db import models

from ili2django.decorators import ili_field, interlis_model

@interlis_model(oid='HoheitsgrenzenLV_V1_0.HoheitsgrenzenLV.Landesgrenze.Gueltigkeit_ENUM', qname='odmav_hoheitsgrenzen_lv_v1_0.LandesgrenzeGueltigkeitEnum')
class LandesgrenzeGueltigkeitEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='HoheitsgrenzenLV_V1_0.HoheitsgrenzenLV.Landesgrenze.Gueltigkeit_ENUM.code', qname='odmav_hoheitsgrenzen_lv_v1_0.LandesgrenzeGueltigkeitEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='HoheitsgrenzenLV_V1_0.HoheitsgrenzenLV.Landesgrenze.Gueltigkeit_ENUM.label', qname='odmav_hoheitsgrenzen_lv_v1_0.LandesgrenzeGueltigkeitEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['provisorisch', 'streitig', 'festgelegt', 'rechtskraeftig']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_hoheitsgrenzen_lv_v1_0__landesgrenze_gueltigke_b741045579'

@interlis_model(oid='HoheitsgrenzenLV_V1_0.HoheitsgrenzenLV.Landesgrenze', qname='odmav_hoheitsgrenzen_lv_v1_0.Landesgrenze')
class Landesgrenze(models.Model):
    geometrie = ili_field(models.LineStringField(srid=2056, null=False, blank=False), oid='HoheitsgrenzenLV_V1_0.HoheitsgrenzenLV.Landesgrenze.Geometrie', qname='odmav_hoheitsgrenzen_lv_v1_0.Landesgrenze.Geometrie')
    gueltigkeit = ili_field(models.ForeignKey('odmav_hoheitsgrenzen_lv_v1_0.LandesgrenzeGueltigkeitEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='HoheitsgrenzenLV_V1_0.HoheitsgrenzenLV.Landesgrenze.Gueltigkeit', qname='odmav_hoheitsgrenzen_lv_v1_0.Landesgrenze.Gueltigkeit')

    class Meta:
        db_table = 'odmav_hoheitsgrenzen_lv_v1_0__landesgrenze'
