"""Generated by ili2django. Do not edit manually."""

from django.contrib.gis.db import models

from ili2django.decorators import ili_field, interlis_model

@interlis_model(oid='FixpunkteLV_V1_0.FixpunkteLV.LFP1.Status_ENUM', qname='odmav_fixpunkte_lv_v1_0.LFP1StatusEnum')
class LFP1StatusEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='FixpunkteLV_V1_0.FixpunkteLV.LFP1.Status_ENUM.code', qname='odmav_fixpunkte_lv_v1_0.LFP1StatusEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='FixpunkteLV_V1_0.FixpunkteLV.LFP1.Status_ENUM.label', qname='odmav_fixpunkte_lv_v1_0.LFP1StatusEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['Aktiv', 'Deklassiert', 'Geloescht', 'Ersetzt', 'Zerstoert']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_fixpunkte_lv_v1_0__lfp1_status_enum_value'

@interlis_model(oid='FixpunkteLV_V1_0.FixpunkteLV.LFP1.Ordnung_ENUM', qname='odmav_fixpunkte_lv_v1_0.LFP1OrdnungEnum')
class LFP1OrdnungEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='FixpunkteLV_V1_0.FixpunkteLV.LFP1.Ordnung_ENUM.code', qname='odmav_fixpunkte_lv_v1_0.LFP1OrdnungEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='FixpunkteLV_V1_0.FixpunkteLV.LFP1.Ordnung_ENUM.label', qname='odmav_fixpunkte_lv_v1_0.LFP1OrdnungEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['LFP1_1_Ordnung', 'LFP1_2_Ordnung', 'LFP1_3_Ordnung', 'LV95_Hauptpunkt', 'LV95_Verdichtungspunkt']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_fixpunkte_lv_v1_0__lfp1_ordnung_enum_value'

@interlis_model(oid='FixpunkteLV_V1_0.FixpunkteLV.HFP1.Ordnung_ENUM', qname='odmav_fixpunkte_lv_v1_0.HFP1OrdnungEnum')
class HFP1OrdnungEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='FixpunkteLV_V1_0.FixpunkteLV.HFP1.Ordnung_ENUM.code', qname='odmav_fixpunkte_lv_v1_0.HFP1OrdnungEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='FixpunkteLV_V1_0.FixpunkteLV.HFP1.Ordnung_ENUM.label', qname='odmav_fixpunkte_lv_v1_0.HFP1OrdnungEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['HFP1']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_fixpunkte_lv_v1_0__hfp1_ordnung_enum_value'

@interlis_model(oid='FixpunkteLV_V1_0.FixpunkteLV.HFP1.ZustHaupt_ENUM', qname='odmav_fixpunkte_lv_v1_0.HFP1ZustHauptEnum')
class HFP1ZustHauptEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='FixpunkteLV_V1_0.FixpunkteLV.HFP1.ZustHaupt_ENUM.code', qname='odmav_fixpunkte_lv_v1_0.HFP1ZustHauptEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='FixpunkteLV_V1_0.FixpunkteLV.HFP1.ZustHaupt_ENUM.label', qname='odmav_fixpunkte_lv_v1_0.HFP1ZustHauptEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['CH']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_fixpunkte_lv_v1_0__hfp1_zust_haupt_enum_value'

@interlis_model(oid='FixpunkteLV_V1_0.FixpunkteLV.HFP1.Zustaendig_ENUM', qname='odmav_fixpunkte_lv_v1_0.HFP1ZustaendigEnum')
class HFP1ZustaendigEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='FixpunkteLV_V1_0.FixpunkteLV.HFP1.Zustaendig_ENUM.code', qname='odmav_fixpunkte_lv_v1_0.HFP1ZustaendigEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='FixpunkteLV_V1_0.FixpunkteLV.HFP1.Zustaendig_ENUM.label', qname='odmav_fixpunkte_lv_v1_0.HFP1ZustaendigEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['CH']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_fixpunkte_lv_v1_0__hfp1_zustaendig_enum_value'

@interlis_model(oid='FixpunkteLV_V1_0.FixpunkteLV.LSN.Ordnung_ENUM', qname='odmav_fixpunkte_lv_v1_0.LSNOrdnungEnum')
class LSNOrdnungEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='FixpunkteLV_V1_0.FixpunkteLV.LSN.Ordnung_ENUM.code', qname='odmav_fixpunkte_lv_v1_0.LSNOrdnungEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='FixpunkteLV_V1_0.FixpunkteLV.LSN.Ordnung_ENUM.label', qname='odmav_fixpunkte_lv_v1_0.LSNOrdnungEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['Absolutstation', 'Ordnung1', 'Ordnung2', 'Ordnung3', 'Exzenter_Absolutstation']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_fixpunkte_lv_v1_0__lsnordnung_enum_value'

@interlis_model(oid='FixpunkteLV_V1_0.FixpunkteLV.LFP1', qname='odmav_fixpunkte_lv_v1_0.LFP1')
class LFP1(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.FixpunkteLV_V1_0.FixpunkteLV.LFP1.tid', qname='odmav_fixpunkte_lv_v1_0.LFP1.tid')
    nbident = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='FixpunkteLV_V1_0.FixpunkteLV.LFP1.NBIDENT', qname='odmav_fixpunkte_lv_v1_0.LFP1.NBIDENT')
    nummer = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='FixpunkteLV_V1_0.FixpunkteLV.LFP1.Nummer', qname='odmav_fixpunkte_lv_v1_0.LFP1.Nummer')
    geometrie = ili_field(models.PointField(srid=2056, null=False, blank=False), oid='FixpunkteLV_V1_0.FixpunkteLV.LFP1.Geometrie', qname='odmav_fixpunkte_lv_v1_0.LFP1.Geometrie')
    hoehengeometrie = ili_field(models.FloatField(null=True, blank=True), oid='FixpunkteLV_V1_0.FixpunkteLV.LFP1.Hoehengeometrie', qname='odmav_fixpunkte_lv_v1_0.LFP1.Hoehengeometrie')
    lagegenauigkeit = ili_field(models.FloatField(null=False, blank=False), oid='FixpunkteLV_V1_0.FixpunkteLV.LFP1.Lagegenauigkeit', qname='odmav_fixpunkte_lv_v1_0.LFP1.Lagegenauigkeit')
    ist_lagezuverlaessig = ili_field(models.BooleanField(default=False), oid='FixpunkteLV_V1_0.FixpunkteLV.LFP1.IstLagezuverlaessig', qname='odmav_fixpunkte_lv_v1_0.LFP1.IstLagezuverlaessig')
    hoehengenauigkeit = ili_field(models.FloatField(null=True, blank=True), oid='FixpunkteLV_V1_0.FixpunkteLV.LFP1.Hoehengenauigkeit', qname='odmav_fixpunkte_lv_v1_0.LFP1.Hoehengenauigkeit')
    ist_hoehenzuverlaessig = ili_field(models.BooleanField(null=True, blank=True, default=None), oid='FixpunkteLV_V1_0.FixpunkteLV.LFP1.IstHoehenzuverlaessig', qname='odmav_fixpunkte_lv_v1_0.LFP1.IstHoehenzuverlaessig')
    begehbar = ili_field(models.BooleanField(default=False), oid='FixpunkteLV_V1_0.FixpunkteLV.LFP1.Begehbar', qname='odmav_fixpunkte_lv_v1_0.LFP1.Begehbar')
    punktzeichen = ili_field(models.CharField(max_length=50, null=True, blank=True), oid='FixpunkteLV_V1_0.FixpunkteLV.LFP1.Punktzeichen', qname='odmav_fixpunkte_lv_v1_0.LFP1.Punktzeichen')
    punktname = ili_field(models.CharField(max_length=30, null=True, blank=True), oid='FixpunkteLV_V1_0.FixpunkteLV.LFP1.Punktname', qname='odmav_fixpunkte_lv_v1_0.LFP1.Punktname')
    status = ili_field(models.ForeignKey('odmav_fixpunkte_lv_v1_0.LFP1StatusEnumValue', on_delete=models.PROTECT, related_name='+', null=True, blank=True), oid='FixpunkteLV_V1_0.FixpunkteLV.LFP1.Status', qname='odmav_fixpunkte_lv_v1_0.LFP1.Status')
    zugang = ili_field(models.CharField(max_length=255, null=True, blank=True), oid='FixpunkteLV_V1_0.FixpunkteLV.LFP1.Zugang', qname='odmav_fixpunkte_lv_v1_0.LFP1.Zugang')
    ordnung = ili_field(models.ForeignKey('odmav_fixpunkte_lv_v1_0.LFP1OrdnungEnumValue', on_delete=models.PROTECT, related_name='+', null=True, blank=True), oid='FixpunkteLV_V1_0.FixpunkteLV.LFP1.Ordnung', qname='odmav_fixpunkte_lv_v1_0.LFP1.Ordnung')

    class Meta:
        db_table = 'odmav_fixpunkte_lv_v1_0__lfp1'

@interlis_model(oid='FixpunkteLV_V1_0.FixpunkteLV.HFP1', qname='odmav_fixpunkte_lv_v1_0.HFP1')
class HFP1(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.FixpunkteLV_V1_0.FixpunkteLV.HFP1.tid', qname='odmav_fixpunkte_lv_v1_0.HFP1.tid')
    nbident = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='FixpunkteLV_V1_0.FixpunkteLV.HFP1.NBIDENT', qname='odmav_fixpunkte_lv_v1_0.HFP1.NBIDENT')
    nummer = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='FixpunkteLV_V1_0.FixpunkteLV.HFP1.Nummer', qname='odmav_fixpunkte_lv_v1_0.HFP1.Nummer')
    geometrie = ili_field(models.PointField(srid=2056, null=False, blank=False), oid='FixpunkteLV_V1_0.FixpunkteLV.HFP1.Geometrie', qname='odmav_fixpunkte_lv_v1_0.HFP1.Geometrie')
    hoehengeometrie = ili_field(models.FloatField(null=False, blank=False), oid='FixpunkteLV_V1_0.FixpunkteLV.HFP1.Hoehengeometrie', qname='odmav_fixpunkte_lv_v1_0.HFP1.Hoehengeometrie')
    lagegenauigkeit = ili_field(models.FloatField(null=False, blank=False), oid='FixpunkteLV_V1_0.FixpunkteLV.HFP1.Lagegenauigkeit', qname='odmav_fixpunkte_lv_v1_0.HFP1.Lagegenauigkeit')
    ist_lagezuverlaessig = ili_field(models.BooleanField(default=False), oid='FixpunkteLV_V1_0.FixpunkteLV.HFP1.IstLagezuverlaessig', qname='odmav_fixpunkte_lv_v1_0.HFP1.IstLagezuverlaessig')
    hoehengenauigkeit = ili_field(models.FloatField(null=False, blank=False), oid='FixpunkteLV_V1_0.FixpunkteLV.HFP1.Hoehengenauigkeit', qname='odmav_fixpunkte_lv_v1_0.HFP1.Hoehengenauigkeit')
    ist_hoehenzuverlaessig = ili_field(models.BooleanField(default=False), oid='FixpunkteLV_V1_0.FixpunkteLV.HFP1.IstHoehenzuverlaessig', qname='odmav_fixpunkte_lv_v1_0.HFP1.IstHoehenzuverlaessig')
    zugang = ili_field(models.CharField(max_length=255, null=True, blank=True), oid='FixpunkteLV_V1_0.FixpunkteLV.HFP1.Zugang', qname='odmav_fixpunkte_lv_v1_0.HFP1.Zugang')
    ordnung = ili_field(models.ForeignKey('odmav_fixpunkte_lv_v1_0.HFP1OrdnungEnumValue', on_delete=models.PROTECT, related_name='+', null=True, blank=True), oid='FixpunkteLV_V1_0.FixpunkteLV.HFP1.Ordnung', qname='odmav_fixpunkte_lv_v1_0.HFP1.Ordnung')
    punktname = ili_field(models.CharField(max_length=30, null=True, blank=True), oid='FixpunkteLV_V1_0.FixpunkteLV.HFP1.Punktname', qname='odmav_fixpunkte_lv_v1_0.HFP1.Punktname')
    h95_ell = ili_field(models.FloatField(null=True, blank=True), oid='FixpunkteLV_V1_0.FixpunkteLV.HFP1.H95Ell', qname='odmav_fixpunkte_lv_v1_0.HFP1.H95Ell')
    zust_haupt = ili_field(models.ForeignKey('odmav_fixpunkte_lv_v1_0.HFP1ZustHauptEnumValue', on_delete=models.PROTECT, related_name='+', null=True, blank=True), oid='FixpunkteLV_V1_0.FixpunkteLV.HFP1.ZustHaupt', qname='odmav_fixpunkte_lv_v1_0.HFP1.ZustHaupt')
    zustaendig = ili_field(models.ForeignKey('odmav_fixpunkte_lv_v1_0.HFP1ZustaendigEnumValue', on_delete=models.PROTECT, related_name='+', null=True, blank=True), oid='FixpunkteLV_V1_0.FixpunkteLV.HFP1.Zustaendig', qname='odmav_fixpunkte_lv_v1_0.HFP1.Zustaendig')
    punktzeichen = ili_field(models.CharField(max_length=50, null=True, blank=True), oid='FixpunkteLV_V1_0.FixpunkteLV.HFP1.Punktzeichen', qname='odmav_fixpunkte_lv_v1_0.HFP1.Punktzeichen')
    begehbar = ili_field(models.BooleanField(null=True, blank=True, default=None), oid='FixpunkteLV_V1_0.FixpunkteLV.HFP1.Begehbar', qname='odmav_fixpunkte_lv_v1_0.HFP1.Begehbar')

    class Meta:
        db_table = 'odmav_fixpunkte_lv_v1_0__hfp1'

@interlis_model(oid='FixpunkteLV_V1_0.FixpunkteLV.LSN', qname='odmav_fixpunkte_lv_v1_0.LSN')
class LSN(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.FixpunkteLV_V1_0.FixpunkteLV.LSN.tid', qname='odmav_fixpunkte_lv_v1_0.LSN.tid')
    nummer = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='FixpunkteLV_V1_0.FixpunkteLV.LSN.Nummer', qname='odmav_fixpunkte_lv_v1_0.LSN.Nummer')
    geometrie = ili_field(models.PointField(srid=2056, null=False, blank=False), oid='FixpunkteLV_V1_0.FixpunkteLV.LSN.Geometrie', qname='odmav_fixpunkte_lv_v1_0.LSN.Geometrie')
    hoehengeometrie = ili_field(models.FloatField(null=False, blank=False), oid='FixpunkteLV_V1_0.FixpunkteLV.LSN.Hoehengeometrie', qname='odmav_fixpunkte_lv_v1_0.LSN.Hoehengeometrie')
    lat_etrs = ili_field(models.FloatField(null=True, blank=True), oid='FixpunkteLV_V1_0.FixpunkteLV.LSN.LatEtrs', qname='odmav_fixpunkte_lv_v1_0.LSN.LatEtrs')
    lon_etrs = ili_field(models.FloatField(null=True, blank=True), oid='FixpunkteLV_V1_0.FixpunkteLV.LSN.LonEtrs', qname='odmav_fixpunkte_lv_v1_0.LSN.LonEtrs')
    vert_grad = ili_field(models.FloatField(null=True, blank=True), oid='FixpunkteLV_V1_0.FixpunkteLV.LSN.VertGrad', qname='odmav_fixpunkte_lv_v1_0.LSN.VertGrad')
    gravity = ili_field(models.FloatField(null=True, blank=True), oid='FixpunkteLV_V1_0.FixpunkteLV.LSN.Gravity', qname='odmav_fixpunkte_lv_v1_0.LSN.Gravity')
    rms = ili_field(models.FloatField(null=True, blank=True), oid='FixpunkteLV_V1_0.FixpunkteLV.LSN.RMS', qname='odmav_fixpunkte_lv_v1_0.LSN.RMS')
    punktname = ili_field(models.CharField(max_length=30, null=True, blank=True), oid='FixpunkteLV_V1_0.FixpunkteLV.LSN.Punktname', qname='odmav_fixpunkte_lv_v1_0.LSN.Punktname')
    ordnung = ili_field(models.ForeignKey('odmav_fixpunkte_lv_v1_0.LSNOrdnungEnumValue', on_delete=models.PROTECT, related_name='+', null=True, blank=True), oid='FixpunkteLV_V1_0.FixpunkteLV.LSN.Ordnung', qname='odmav_fixpunkte_lv_v1_0.LSN.Ordnung')

    class Meta:
        db_table = 'odmav_fixpunkte_lv_v1_0__lsn'
