"""Generated by ili2django. Do not edit manually."""

from django.contrib.gis.db import models
from django.utils.translation import gettext_lazy as _

from ili2django.choices import IliChoice, IliChoices
from ili2django.decorators import ili_field, interlis_model

@interlis_model(oid='DMAVSUP_UntereinheitGrundbuch_V1_1.UntereinheitGrundbuch.GrundbuchKreis.Kanton_ENUM', qname='odmav_dmavsup_untereinheit_grundbuch_v1_1.GrundbuchKreisKantonEnum')
class GrundbuchKreisKantonEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAVSUP_UntereinheitGrundbuch_V1_1.UntereinheitGrundbuch.GrundbuchKreis.Kanton_ENUM.code', qname='odmav_dmavsup_untereinheit_grundbuch_v1_1.GrundbuchKreisKantonEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAVSUP_UntereinheitGrundbuch_V1_1.UntereinheitGrundbuch.GrundbuchKreis.Kanton_ENUM.label', qname='odmav_dmavsup_untereinheit_grundbuch_v1_1.GrundbuchKreisKantonEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['ZH', 'BE', 'LU', 'UR', 'SZ', 'OW', 'NW', 'GL', 'ZG', 'FR', 'SO', 'BS', 'BL', 'SH', 'AR', 'AI', 'SG', 'GR', 'AG', 'TG', 'TI', 'VD', 'VS', 'NE', 'GE', 'JU', 'FL', 'CH']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmavsup_untereinheit_grundbuch_v1_1__grundbuch_b297f6b9b2'

class GrundbuchKreisKantonEnumValueChoices(IliChoices):
    ZH = IliChoice('ZH', _('ZH'), order=0)
    BE = IliChoice('BE', _('BE'), order=1)
    LU = IliChoice('LU', _('LU'), order=2)
    UR = IliChoice('UR', _('UR'), order=3)
    SZ = IliChoice('SZ', _('SZ'), order=4)
    OW = IliChoice('OW', _('OW'), order=5)
    NW = IliChoice('NW', _('NW'), order=6)
    GL = IliChoice('GL', _('GL'), order=7)
    ZG = IliChoice('ZG', _('ZG'), order=8)
    FR = IliChoice('FR', _('FR'), order=9)
    SO = IliChoice('SO', _('SO'), order=10)
    BS = IliChoice('BS', _('BS'), order=11)
    BL = IliChoice('BL', _('BL'), order=12)
    SH = IliChoice('SH', _('SH'), order=13)
    AR = IliChoice('AR', _('AR'), order=14)
    AI = IliChoice('AI', _('AI'), order=15)
    SG = IliChoice('SG', _('SG'), order=16)
    GR = IliChoice('GR', _('GR'), order=17)
    AG = IliChoice('AG', _('AG'), order=18)
    TG = IliChoice('TG', _('TG'), order=19)
    TI = IliChoice('TI', _('TI'), order=20)
    VD = IliChoice('VD', _('VD'), order=21)
    VS = IliChoice('VS', _('VS'), order=22)
    NE = IliChoice('NE', _('NE'), order=23)
    GE = IliChoice('GE', _('GE'), order=24)
    JU = IliChoice('JU', _('JU'), order=25)
    FL = IliChoice('FL', _('FL'), order=26)
    CH = IliChoice('CH', _('CH'), order=27)

@interlis_model(oid='DMAVSUP_UntereinheitGrundbuch_V1_1.UntereinheitGrundbuch.GrundbuchKreis', qname='odmav_dmavsup_untereinheit_grundbuch_v1_1.GrundbuchKreis')
class GrundbuchKreis(models.Model):
    kanton = ili_field(models.ForeignKey('odmav_dmavsup_untereinheit_grundbuch_v1_1.GrundbuchKreisKantonEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAVSUP_UntereinheitGrundbuch_V1_1.UntereinheitGrundbuch.GrundbuchKreis.Kanton', qname='odmav_dmavsup_untereinheit_grundbuch_v1_1.GrundbuchKreis.Kanton')
    gemeinde = ili_field(models.IntegerField(null=False, blank=False), oid='DMAVSUP_UntereinheitGrundbuch_V1_1.UntereinheitGrundbuch.GrundbuchKreis.Gemeinde', qname='odmav_dmavsup_untereinheit_grundbuch_v1_1.GrundbuchKreis.Gemeinde')
    nbident = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='DMAVSUP_UntereinheitGrundbuch_V1_1.UntereinheitGrundbuch.GrundbuchKreis.NBIdent', qname='odmav_dmavsup_untereinheit_grundbuch_v1_1.GrundbuchKreis.NBIdent')
    name = ili_field(models.CharField(max_length=60, null=False, blank=False), oid='DMAVSUP_UntereinheitGrundbuch_V1_1.UntereinheitGrundbuch.GrundbuchKreis.Name', qname='odmav_dmavsup_untereinheit_grundbuch_v1_1.GrundbuchKreis.Name')
    e_gris_sub_kreis = ili_field(models.CharField(max_length=15, null=True, blank=True), oid='DMAVSUP_UntereinheitGrundbuch_V1_1.UntereinheitGrundbuch.GrundbuchKreis.eGRIS_SubKreis', qname='odmav_dmavsup_untereinheit_grundbuch_v1_1.GrundbuchKreis.eGRIS_SubKreis')
    e_gris_los = ili_field(models.CharField(max_length=15, null=True, blank=True), oid='DMAVSUP_UntereinheitGrundbuch_V1_1.UntereinheitGrundbuch.GrundbuchKreis.eGRIS_Los', qname='odmav_dmavsup_untereinheit_grundbuch_v1_1.GrundbuchKreis.eGRIS_Los')
    geometrie = ili_field(models.MultiSurfaceField(srid=2056, null=True, blank=True), oid='DMAVSUP_UntereinheitGrundbuch_V1_1.UntereinheitGrundbuch.GrundbuchKreis.Geometrie', qname='odmav_dmavsup_untereinheit_grundbuch_v1_1.GrundbuchKreis.Geometrie')

    class Meta:
        db_table = 'odmav_dmavsup_untereinheit_grundbuch_v1_1__grundbuch_kreis'
