"""Generated by ili2django. Do not edit manually."""

from django.contrib.gis.db import models
from django.utils.translation import gettext_lazy as _

from ili2django.choices import IliChoice, IliChoices
from ili2django.decorators import ili_field, interlis_model

@interlis_model(oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Grundstuecksart', qname='odmav_dmav_grundstuecke_v1_1.Grundstuecksart')
class GrundstuecksartValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Grundstuecksart.code', qname='odmav_dmav_grundstuecke_v1_1.Grundstuecksart.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Grundstuecksart.label', qname='odmav_dmav_grundstuecke_v1_1.Grundstuecksart.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['Liegenschaft', 'SelbstaendigesDauerndesRecht', 'Bergwerk']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_grundstuecke_v1_1__grundstuecksart_value'

class GrundstuecksartValueChoices(IliChoices):
    LIEGENSCHAFT = IliChoice('Liegenschaft', _('Liegenschaft'), order=0)
    SELBSTAENDIGES_DAUERNDES_RECHT = IliChoice('SelbstaendigesDauerndesRecht', _('SelbstaendigesDauerndesRecht'), order=1)
    BERGWERK = IliChoice('Bergwerk', _('Bergwerk'), order=2)

@interlis_model(oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Mutationsart', qname='odmav_dmav_grundstuecke_v1_1.Mutationsart')
class MutationsartValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Mutationsart.code', qname='odmav_dmav_grundstuecke_v1_1.Mutationsart.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Mutationsart.label', qname='odmav_dmav_grundstuecke_v1_1.Mutationsart.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['Normal', 'Projektmutation', 'AbschlussProjektmutation']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_grundstuecke_v1_1__mutationsart_value'

class MutationsartValueChoices(IliChoices):
    NORMAL = IliChoice('Normal', _('Normal'), order=0)
    PROJEKTMUTATION = IliChoice('Projektmutation', _('Projektmutation'), order=1)
    ABSCHLUSS_PROJEKTMUTATION = IliChoice('AbschlussProjektmutation', _('AbschlussProjektmutation'), order=2)

@interlis_model(oid='DMAV_Grundstuecke_V1_1.Grundstuecke.GSNachfuehrung.Mutationsart_ENUM', qname='odmav_dmav_grundstuecke_v1_1.GSNachfuehrungMutationsartEnum')
class GSNachfuehrungMutationsartEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.GSNachfuehrung.Mutationsart_ENUM.code', qname='odmav_dmav_grundstuecke_v1_1.GSNachfuehrungMutationsartEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.GSNachfuehrung.Mutationsart_ENUM.label', qname='odmav_dmav_grundstuecke_v1_1.GSNachfuehrungMutationsartEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['Normal', 'Projektmutation', 'AbschlussProjektmutation']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_grundstuecke_v1_1__gsnachfuehrung_mutatio_7ff1ed8f17'

class GSNachfuehrungMutationsartEnumValueChoices(IliChoices):
    NORMAL = IliChoice('Normal', _('Normal'), order=0)
    PROJEKTMUTATION = IliChoice('Projektmutation', _('Projektmutation'), order=1)
    ABSCHLUSS_PROJEKTMUTATION = IliChoice('AbschlussProjektmutation', _('AbschlussProjektmutation'), order=2)

@interlis_model(oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Grenzpunkt.Punktzeichen_ENUM', qname='odmav_dmav_grundstuecke_v1_1.GrenzpunktPunktzeichenEnum')
class GrenzpunktPunktzeichenEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Grenzpunkt.Punktzeichen_ENUM.code', qname='odmav_dmav_grundstuecke_v1_1.GrenzpunktPunktzeichenEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Grenzpunkt.Punktzeichen_ENUM.label', qname='odmav_dmav_grundstuecke_v1_1.GrenzpunktPunktzeichenEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['Stein', 'Kunststoffzeichen', 'Bolzen', 'Rohr', 'Pfahl', 'Kreuz', 'unversichert', 'weitere']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_grundstuecke_v1_1__grenzpunkt_punktzeiche_f7805ef2bc'

class GrenzpunktPunktzeichenEnumValueChoices(IliChoices):
    STEIN = IliChoice('Stein', _('Stein'), order=0)
    KUNSTSTOFFZEICHEN = IliChoice('Kunststoffzeichen', _('Kunststoffzeichen'), order=1)
    BOLZEN = IliChoice('Bolzen', _('Bolzen'), order=2)
    ROHR = IliChoice('Rohr', _('Rohr'), order=3)
    PFAHL = IliChoice('Pfahl', _('Pfahl'), order=4)
    KREUZ = IliChoice('Kreuz', _('Kreuz'), order=5)
    UNVERSICHERT = IliChoice('unversichert', _('unversichert'), order=6)
    WEITERE = IliChoice('weitere', _('weitere'), order=7)

@interlis_model(oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Grundstueck.Grundstuecksart_ENUM', qname='odmav_dmav_grundstuecke_v1_1.GrundstueckGrundstuecksartEnum')
class GrundstueckGrundstuecksartEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Grundstueck.Grundstuecksart_ENUM.code', qname='odmav_dmav_grundstuecke_v1_1.GrundstueckGrundstuecksartEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Grundstueck.Grundstuecksart_ENUM.label', qname='odmav_dmav_grundstuecke_v1_1.GrundstueckGrundstuecksartEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['Liegenschaft', 'SelbstaendigesDauerndesRecht', 'Bergwerk']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_grundstuecke_v1_1__grundstueck_grundstuec_c4140e1a5f'

class GrundstueckGrundstuecksartEnumValueChoices(IliChoices):
    LIEGENSCHAFT = IliChoice('Liegenschaft', _('Liegenschaft'), order=0)
    SELBSTAENDIGES_DAUERNDES_RECHT = IliChoice('SelbstaendigesDauerndesRecht', _('SelbstaendigesDauerndesRecht'), order=1)
    BERGWERK = IliChoice('Bergwerk', _('Bergwerk'), order=2)

@interlis_model(oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Liegenschaft.Qualitaetsstandard_ENUM', qname='odmav_dmav_grundstuecke_v1_1.LiegenschaftQualitaetsstandardEnum')
class LiegenschaftQualitaetsstandardEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Liegenschaft.Qualitaetsstandard_ENUM.code', qname='odmav_dmav_grundstuecke_v1_1.LiegenschaftQualitaetsstandardEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Liegenschaft.Qualitaetsstandard_ENUM.label', qname='odmav_dmav_grundstuecke_v1_1.LiegenschaftQualitaetsstandardEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['AV93', 'PN']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_grundstuecke_v1_1__liegenschaft_qualitaet_0c45984d9a'

class LiegenschaftQualitaetsstandardEnumValueChoices(IliChoices):
    AV93 = IliChoice('AV93', _('AV93'), order=0)
    PN = IliChoice('PN', _('PN'), order=1)

@interlis_model(oid='DMAV_Grundstuecke_V1_1.Grundstuecke.GSNachfuehrung', qname='odmav_dmav_grundstuecke_v1_1.GSNachfuehrung')
class GSNachfuehrung(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_Grundstuecke_V1_1.Grundstuecke.GSNachfuehrung.tid', qname='odmav_dmav_grundstuecke_v1_1.GSNachfuehrung.tid')
    nbident = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.GSNachfuehrung.NBIdent', qname='odmav_dmav_grundstuecke_v1_1.GSNachfuehrung.NBIdent')
    identifikator = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.GSNachfuehrung.Identifikator', qname='odmav_dmav_grundstuecke_v1_1.GSNachfuehrung.Identifikator')
    beschreibung = ili_field(models.CharField(max_length=60, null=False, blank=False), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.GSNachfuehrung.Beschreibung', qname='odmav_dmav_grundstuecke_v1_1.GSNachfuehrung.Beschreibung')
    perimeter = ili_field(models.CurvePolygonField(srid=2056, null=True, blank=True), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.GSNachfuehrung.Perimeter', qname='odmav_dmav_grundstuecke_v1_1.GSNachfuehrung.Perimeter')
    mutationsart = ili_field(models.ForeignKey('odmav_dmav_grundstuecke_v1_1.GSNachfuehrungMutationsartEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.GSNachfuehrung.Mutationsart', qname='odmav_dmav_grundstuecke_v1_1.GSNachfuehrung.Mutationsart')
    gueltiger_eintrag = ili_field(models.CharField(max_length=255, null=False, blank=False), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.GSNachfuehrung.GueltigerEintrag', qname='odmav_dmav_grundstuecke_v1_1.GSNachfuehrung.GueltigerEintrag')
    grundbucheintrag = ili_field(models.CharField(max_length=255, null=True, blank=True), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.GSNachfuehrung.Grundbucheintrag', qname='odmav_dmav_grundstuecke_v1_1.GSNachfuehrung.Grundbucheintrag')

    class Meta:
        db_table = 'odmav_dmav_grundstuecke_v1_1__gsnachfuehrung'

@interlis_model(oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Grenzpunkt', qname='odmav_dmav_grundstuecke_v1_1.Grenzpunkt')
class Grenzpunkt(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_Grundstuecke_V1_1.Grundstuecke.Grenzpunkt.tid', qname='odmav_dmav_grundstuecke_v1_1.Grenzpunkt.tid')
    nbident = ili_field(models.CharField(max_length=12, null=True, blank=True), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Grenzpunkt.NBIdent', qname='odmav_dmav_grundstuecke_v1_1.Grenzpunkt.NBIdent')
    nummer = ili_field(models.CharField(max_length=12, null=True, blank=True), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Grenzpunkt.Nummer', qname='odmav_dmav_grundstuecke_v1_1.Grenzpunkt.Nummer')
    geometrie = ili_field(models.PointField(srid=2056, null=False, blank=False), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Grenzpunkt.Geometrie', qname='odmav_dmav_grundstuecke_v1_1.Grenzpunkt.Geometrie')
    hoehengeometrie = ili_field(models.FloatField(null=True, blank=True), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Grenzpunkt.Hoehengeometrie', qname='odmav_dmav_grundstuecke_v1_1.Grenzpunkt.Hoehengeometrie')
    lagegenauigkeit = ili_field(models.FloatField(null=False, blank=False), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Grenzpunkt.Lagegenauigkeit', qname='odmav_dmav_grundstuecke_v1_1.Grenzpunkt.Lagegenauigkeit')
    ist_lagezuverlaessig = ili_field(models.BooleanField(default=False), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Grenzpunkt.IstLagezuverlaessig', qname='odmav_dmav_grundstuecke_v1_1.Grenzpunkt.IstLagezuverlaessig')
    hoehengenauigkeit = ili_field(models.FloatField(null=True, blank=True), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Grenzpunkt.Hoehengenauigkeit', qname='odmav_dmav_grundstuecke_v1_1.Grenzpunkt.Hoehengenauigkeit')
    ist_hoehenzuverlaessig = ili_field(models.BooleanField(null=True, blank=True, default=None), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Grenzpunkt.IstHoehenzuverlaessig', qname='odmav_dmav_grundstuecke_v1_1.Grenzpunkt.IstHoehenzuverlaessig')
    punktzeichen = ili_field(models.ForeignKey('odmav_dmav_grundstuecke_v1_1.GrenzpunktPunktzeichenEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Grenzpunkt.Punktzeichen', qname='odmav_dmav_grundstuecke_v1_1.Grenzpunkt.Punktzeichen')
    ist_hoheitsgrenzpunkt = ili_field(models.BooleanField(default=False), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Grenzpunkt.IstHoheitsgrenzpunkt', qname='odmav_dmav_grundstuecke_v1_1.Grenzpunkt.IstHoheitsgrenzpunkt')
    ist_hoheitsgrenzstein_alt = ili_field(models.BooleanField(default=False), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Grenzpunkt.IstHoheitsgrenzsteinAlt', qname='odmav_dmav_grundstuecke_v1_1.Grenzpunkt.IstHoheitsgrenzsteinAlt')
    ist_exakt_definiert = ili_field(models.BooleanField(default=False), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Grenzpunkt.IstExaktDefiniert', qname='odmav_dmav_grundstuecke_v1_1.Grenzpunkt.IstExaktDefiniert')
    symbol_ori = ili_field(models.FloatField(null=True, blank=True), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Grenzpunkt.SymbolOri', qname='odmav_dmav_grundstuecke_v1_1.Grenzpunkt.SymbolOri')
    entstehung = ili_field(models.ForeignKey('odmav_dmav_grundstuecke_v1_1.GSNachfuehrung', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Entstehung_Grenzpunkt.Entstehung', qname='odmav_dmav_grundstuecke_v1_1.Grenzpunkt.Entstehung')
    untergang = ili_field(models.ForeignKey('odmav_dmav_grundstuecke_v1_1.GSNachfuehrung', on_delete=models.PROTECT, related_name='+', null=True, blank=True), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Untergang_Grenzpunkt.Untergang', qname='odmav_dmav_grundstuecke_v1_1.Grenzpunkt.Untergang')

    class Meta:
        db_table = 'odmav_dmav_grundstuecke_v1_1__grenzpunkt'

@interlis_model(oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Grundstueck', qname='odmav_dmav_grundstuecke_v1_1.Grundstueck')
class Grundstueck(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_Grundstuecke_V1_1.Grundstuecke.Grundstueck.tid', qname='odmav_dmav_grundstuecke_v1_1.Grundstueck.tid')
    nbident = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Grundstueck.NBIdent', qname='odmav_dmav_grundstuecke_v1_1.Grundstueck.NBIdent')
    nummer = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Grundstueck.Nummer', qname='odmav_dmav_grundstuecke_v1_1.Grundstueck.Nummer')
    egrid = ili_field(models.CharField(max_length=14, null=True, blank=True), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Grundstueck.EGRID', qname='odmav_dmav_grundstuecke_v1_1.Grundstueck.EGRID')
    ist_streitig = ili_field(models.BooleanField(default=False), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Grundstueck.IstStreitig', qname='odmav_dmav_grundstuecke_v1_1.Grundstueck.IstStreitig')
    ist_vollstaendig = ili_field(models.BooleanField(default=False), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Grundstueck.IstVollstaendig', qname='odmav_dmav_grundstuecke_v1_1.Grundstueck.IstVollstaendig')
    grundstuecksart = ili_field(models.ForeignKey('odmav_dmav_grundstuecke_v1_1.GrundstueckGrundstuecksartEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Grundstueck.Grundstuecksart', qname='odmav_dmav_grundstuecke_v1_1.Grundstueck.Grundstuecksart')
    textposition = ili_field(models.MultiLineStringField(srid=2056, null=True, blank=True), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Grundstueck.Textposition', qname='odmav_dmav_grundstuecke_v1_1.Grundstueck.Textposition')
    fiktiv = ili_field(models.BooleanField(default=False), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Grundstueck.Fiktiv', qname='odmav_dmav_grundstuecke_v1_1.Grundstueck.Fiktiv')
    gesamtflaechenmass = ili_field(models.IntegerField(null=True, blank=True), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Grundstueck.Gesamtflaechenmass', qname='odmav_dmav_grundstuecke_v1_1.Grundstueck.Gesamtflaechenmass')
    entstehung = ili_field(models.ForeignKey('odmav_dmav_grundstuecke_v1_1.GSNachfuehrung', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Entstehung_Grundstueck.Entstehung', qname='odmav_dmav_grundstuecke_v1_1.Grundstueck.Entstehung')
    untergang = ili_field(models.ForeignKey('odmav_dmav_grundstuecke_v1_1.GSNachfuehrung', on_delete=models.PROTECT, related_name='+', null=True, blank=True), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Untergang_Grundstueck.Untergang', qname='odmav_dmav_grundstuecke_v1_1.Grundstueck.Untergang')

    class Meta:
        db_table = 'odmav_dmav_grundstuecke_v1_1__grundstueck'

@interlis_model(oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Liegenschaft', qname='odmav_dmav_grundstuecke_v1_1.Liegenschaft')
class Liegenschaft(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_Grundstuecke_V1_1.Grundstuecke.Liegenschaft.tid', qname='odmav_dmav_grundstuecke_v1_1.Liegenschaft.tid')
    nummer_teilgrundstueck = ili_field(models.CharField(max_length=12, null=True, blank=True), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Liegenschaft.NummerTeilgrundstueck', qname='odmav_dmav_grundstuecke_v1_1.Liegenschaft.NummerTeilgrundstueck')
    geometrie = ili_field(models.CurvePolygonField(srid=2056, null=False, blank=False), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Liegenschaft.Geometrie', qname='odmav_dmav_grundstuecke_v1_1.Liegenschaft.Geometrie')
    fiktiv = ili_field(models.BooleanField(default=False), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Liegenschaft.Fiktiv', qname='odmav_dmav_grundstuecke_v1_1.Liegenschaft.Fiktiv')
    flaechenmass = ili_field(models.IntegerField(null=False, blank=False), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Liegenschaft.Flaechenmass', qname='odmav_dmav_grundstuecke_v1_1.Liegenschaft.Flaechenmass')
    streitig = ili_field(models.MultiLineStringField(srid=2056, null=True, blank=True), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Liegenschaft.Streitig', qname='odmav_dmav_grundstuecke_v1_1.Liegenschaft.Streitig')
    qualitaetsstandard = ili_field(models.ForeignKey('odmav_dmav_grundstuecke_v1_1.LiegenschaftQualitaetsstandardEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Liegenschaft.Qualitaetsstandard', qname='odmav_dmav_grundstuecke_v1_1.Liegenschaft.Qualitaetsstandard')
    grundstueck = ili_field(models.ForeignKey('odmav_dmav_grundstuecke_v1_1.Grundstueck', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.GrundstueckLiegenschaft.Grundstueck', qname='odmav_dmav_grundstuecke_v1_1.Liegenschaft.Grundstueck')

    class Meta:
        db_table = 'odmav_dmav_grundstuecke_v1_1__liegenschaft'

@interlis_model(oid='DMAV_Grundstuecke_V1_1.Grundstuecke.SelbstaendigesDauerndesRecht', qname='odmav_dmav_grundstuecke_v1_1.SelbstaendigesDauerndesRecht')
class SelbstaendigesDauerndesRecht(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_Grundstuecke_V1_1.Grundstuecke.SelbstaendigesDauerndesRecht.tid', qname='odmav_dmav_grundstuecke_v1_1.SelbstaendigesDauerndesRecht.tid')
    nummer_teilgrundstueck = ili_field(models.CharField(max_length=12, null=True, blank=True), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.SelbstaendigesDauerndesRecht.NummerTeilgrundstueck', qname='odmav_dmav_grundstuecke_v1_1.SelbstaendigesDauerndesRecht.NummerTeilgrundstueck')
    geometrie = ili_field(models.CurvePolygonField(srid=2056, null=False, blank=False), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.SelbstaendigesDauerndesRecht.Geometrie', qname='odmav_dmav_grundstuecke_v1_1.SelbstaendigesDauerndesRecht.Geometrie')
    flaechenmass = ili_field(models.IntegerField(null=False, blank=False), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.SelbstaendigesDauerndesRecht.Flaechenmass', qname='odmav_dmav_grundstuecke_v1_1.SelbstaendigesDauerndesRecht.Flaechenmass')
    streitig = ili_field(models.MultiLineStringField(srid=2056, null=True, blank=True), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.SelbstaendigesDauerndesRecht.Streitig', qname='odmav_dmav_grundstuecke_v1_1.SelbstaendigesDauerndesRecht.Streitig')
    ist_baurecht = ili_field(models.BooleanField(null=True, blank=True, default=None), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.SelbstaendigesDauerndesRecht.IstBaurecht', qname='odmav_dmav_grundstuecke_v1_1.SelbstaendigesDauerndesRecht.IstBaurecht')
    grundstueck = ili_field(models.ForeignKey('odmav_dmav_grundstuecke_v1_1.Grundstueck', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.GrundstueckSelbstaendigesDauerndesRecht.Grundstueck', qname='odmav_dmav_grundstuecke_v1_1.SelbstaendigesDauerndesRecht.Grundstueck')

    class Meta:
        db_table = 'odmav_dmav_grundstuecke_v1_1__selbstaendiges_dauerndes_recht'

@interlis_model(oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Bergwerk', qname='odmav_dmav_grundstuecke_v1_1.Bergwerk')
class Bergwerk(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_Grundstuecke_V1_1.Grundstuecke.Bergwerk.tid', qname='odmav_dmav_grundstuecke_v1_1.Bergwerk.tid')
    nummer_teilgrundstueck = ili_field(models.CharField(max_length=12, null=True, blank=True), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Bergwerk.NummerTeilgrundstueck', qname='odmav_dmav_grundstuecke_v1_1.Bergwerk.NummerTeilgrundstueck')
    geometrie = ili_field(models.CurvePolygonField(srid=2056, null=False, blank=False), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Bergwerk.Geometrie', qname='odmav_dmav_grundstuecke_v1_1.Bergwerk.Geometrie')
    flaechenmass = ili_field(models.IntegerField(null=False, blank=False), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Bergwerk.Flaechenmass', qname='odmav_dmav_grundstuecke_v1_1.Bergwerk.Flaechenmass')
    streitig = ili_field(models.MultiLineStringField(srid=2056, null=True, blank=True), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.Bergwerk.Streitig', qname='odmav_dmav_grundstuecke_v1_1.Bergwerk.Streitig')
    grundstueck = ili_field(models.ForeignKey('odmav_dmav_grundstuecke_v1_1.Grundstueck', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Grundstuecke_V1_1.Grundstuecke.GrundstueckBergwerk.Grundstueck', qname='odmav_dmav_grundstuecke_v1_1.Bergwerk.Grundstueck')

    class Meta:
        db_table = 'odmav_dmav_grundstuecke_v1_1__bergwerk'
