"""Generated by ili2django. Do not edit manually."""

from django.contrib.gis.db import models

from ili2django.decorators import ili_field, interlis_model

@interlis_model(oid='DMAV_Nomenklatur_V1_1.Nomenklatur.NKNachfuehrung', qname='odmav_dmav_nomenklatur_v1_1.NKNachfuehrung')
class NKNachfuehrung(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_Nomenklatur_V1_1.Nomenklatur.NKNachfuehrung.tid', qname='odmav_dmav_nomenklatur_v1_1.NKNachfuehrung.tid')
    nbident = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='DMAV_Nomenklatur_V1_1.Nomenklatur.NKNachfuehrung.NBIdent', qname='odmav_dmav_nomenklatur_v1_1.NKNachfuehrung.NBIdent')
    identifikator = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='DMAV_Nomenklatur_V1_1.Nomenklatur.NKNachfuehrung.Identifikator', qname='odmav_dmav_nomenklatur_v1_1.NKNachfuehrung.Identifikator')
    beschreibung = ili_field(models.CharField(max_length=60, null=False, blank=False), oid='DMAV_Nomenklatur_V1_1.Nomenklatur.NKNachfuehrung.Beschreibung', qname='odmav_dmav_nomenklatur_v1_1.NKNachfuehrung.Beschreibung')
    perimeter = ili_field(models.CurvePolygonField(srid=2056, null=True, blank=True), oid='DMAV_Nomenklatur_V1_1.Nomenklatur.NKNachfuehrung.Perimeter', qname='odmav_dmav_nomenklatur_v1_1.NKNachfuehrung.Perimeter')
    gueltiger_eintrag = ili_field(models.CharField(max_length=255, null=False, blank=False), oid='DMAV_Nomenklatur_V1_1.Nomenklatur.NKNachfuehrung.GueltigerEintrag', qname='odmav_dmav_nomenklatur_v1_1.NKNachfuehrung.GueltigerEintrag')

    class Meta:
        db_table = 'odmav_dmav_nomenklatur_v1_1__nknachfuehrung'

@interlis_model(oid='DMAV_Nomenklatur_V1_1.Nomenklatur.Flurname', qname='odmav_dmav_nomenklatur_v1_1.Flurname')
class Flurname(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_Nomenklatur_V1_1.Nomenklatur.Flurname.tid', qname='odmav_dmav_nomenklatur_v1_1.Flurname.tid')
    name = ili_field(models.CharField(max_length=60, null=False, blank=False), oid='DMAV_Nomenklatur_V1_1.Nomenklatur.Flurname.Name', qname='odmav_dmav_nomenklatur_v1_1.Flurname.Name')
    geometrie = ili_field(models.CurvePolygonField(srid=2056, null=False, blank=False), oid='DMAV_Nomenklatur_V1_1.Nomenklatur.Flurname.Geometrie', qname='odmav_dmav_nomenklatur_v1_1.Flurname.Geometrie')
    fiktiv = ili_field(models.BooleanField(default=False), oid='DMAV_Nomenklatur_V1_1.Nomenklatur.Flurname.Fiktiv', qname='odmav_dmav_nomenklatur_v1_1.Flurname.Fiktiv')
    textposition = ili_field(models.MultiLineStringField(srid=2056, null=True, blank=True), oid='DMAV_Nomenklatur_V1_1.Nomenklatur.Flurname.Textposition', qname='odmav_dmav_nomenklatur_v1_1.Flurname.Textposition')
    entstehung = ili_field(models.ForeignKey('odmav_dmav_nomenklatur_v1_1.NKNachfuehrung', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Nomenklatur_V1_1.Nomenklatur.Entstehung_Flurname.Entstehung', qname='odmav_dmav_nomenklatur_v1_1.Flurname.Entstehung')

    class Meta:
        db_table = 'odmav_dmav_nomenklatur_v1_1__flurname'

@interlis_model(oid='DMAV_Nomenklatur_V1_1.Nomenklatur.Ortsname', qname='odmav_dmav_nomenklatur_v1_1.Ortsname')
class Ortsname(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_Nomenklatur_V1_1.Nomenklatur.Ortsname.tid', qname='odmav_dmav_nomenklatur_v1_1.Ortsname.tid')
    name = ili_field(models.CharField(max_length=60, null=False, blank=False), oid='DMAV_Nomenklatur_V1_1.Nomenklatur.Ortsname.Name', qname='odmav_dmav_nomenklatur_v1_1.Ortsname.Name')
    geometrie = ili_field(models.CurvePolygonField(srid=2056, null=False, blank=False), oid='DMAV_Nomenklatur_V1_1.Nomenklatur.Ortsname.Geometrie', qname='odmav_dmav_nomenklatur_v1_1.Ortsname.Geometrie')
    typ = ili_field(models.CharField(max_length=30, null=True, blank=True), oid='DMAV_Nomenklatur_V1_1.Nomenklatur.Ortsname.Typ', qname='odmav_dmav_nomenklatur_v1_1.Ortsname.Typ')
    textposition = ili_field(models.MultiLineStringField(srid=2056, null=True, blank=True), oid='DMAV_Nomenklatur_V1_1.Nomenklatur.Ortsname.Textposition', qname='odmav_dmav_nomenklatur_v1_1.Ortsname.Textposition')
    entstehung = ili_field(models.ForeignKey('odmav_dmav_nomenklatur_v1_1.NKNachfuehrung', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Nomenklatur_V1_1.Nomenklatur.Entstehung_Ortsname.Entstehung', qname='odmav_dmav_nomenklatur_v1_1.Ortsname.Entstehung')

    class Meta:
        db_table = 'odmav_dmav_nomenklatur_v1_1__ortsname'

@interlis_model(oid='DMAV_Nomenklatur_V1_1.Nomenklatur.Gelaendename', qname='odmav_dmav_nomenklatur_v1_1.Gelaendename')
class Gelaendename(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_Nomenklatur_V1_1.Nomenklatur.Gelaendename.tid', qname='odmav_dmav_nomenklatur_v1_1.Gelaendename.tid')
    name = ili_field(models.CharField(max_length=60, null=False, blank=False), oid='DMAV_Nomenklatur_V1_1.Nomenklatur.Gelaendename.Name', qname='odmav_dmav_nomenklatur_v1_1.Gelaendename.Name')
    geometrie = ili_field(models.PointField(srid=2056, null=False, blank=False), oid='DMAV_Nomenklatur_V1_1.Nomenklatur.Gelaendename.Geometrie', qname='odmav_dmav_nomenklatur_v1_1.Gelaendename.Geometrie')
    textposition = ili_field(models.MultiLineStringField(srid=2056, null=True, blank=True), oid='DMAV_Nomenklatur_V1_1.Nomenklatur.Gelaendename.Textposition', qname='odmav_dmav_nomenklatur_v1_1.Gelaendename.Textposition')
    entstehung = ili_field(models.ForeignKey('odmav_dmav_nomenklatur_v1_1.NKNachfuehrung', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Nomenklatur_V1_1.Nomenklatur.Entstehung_Gelaendename.Entstehung', qname='odmav_dmav_nomenklatur_v1_1.Gelaendename.Entstehung')

    class Meta:
        db_table = 'odmav_dmav_nomenklatur_v1_1__gelaendename'
