"""Generated by ili2django. Do not edit manually."""

from django.contrib.gis.db import models
from django.utils.translation import gettext_lazy as _

from ili2django.choices import IliChoice, IliChoices
from ili2django.decorators import ili_field, interlis_model

@interlis_model(oid='DMAV_Dienstbarkeitsgrenzen_V1_1.Dienstbarkeitsgrenzen.Herkunft', qname='odmav_dmav_dienstbarkeitsgrenzen_v1_1.Herkunft')
class HerkunftValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_Dienstbarkeitsgrenzen_V1_1.Dienstbarkeitsgrenzen.Herkunft.code', qname='odmav_dmav_dienstbarkeitsgrenzen_v1_1.Herkunft.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_Dienstbarkeitsgrenzen_V1_1.Dienstbarkeitsgrenzen.Herkunft.label', qname='odmav_dmav_dienstbarkeitsgrenzen_v1_1.Herkunft.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['numerisch', 'grafisch', 'unbestimmt']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_dienstbarkeitsgrenzen_v1_1__herkunft_value'

class HerkunftValueChoices(IliChoices):
    NUMERISCH = IliChoice('numerisch', _('numerisch'), order=0)
    GRAFISCH = IliChoice('grafisch', _('grafisch'), order=1)
    UNBESTIMMT = IliChoice('unbestimmt', _('unbestimmt'), order=2)

@interlis_model(oid='DMAV_Dienstbarkeitsgrenzen_V1_1.Dienstbarkeitsgrenzen.DiBNachfuehrung', qname='odmav_dmav_dienstbarkeitsgrenzen_v1_1.DiBNachfuehrung')
class DiBNachfuehrung(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_Dienstbarkeitsgrenzen_V1_1.Dienstbarkeitsgrenzen.DiBNachfuehrung.tid', qname='odmav_dmav_dienstbarkeitsgrenzen_v1_1.DiBNachfuehrung.tid')
    nbident = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='DMAV_Dienstbarkeitsgrenzen_V1_1.Dienstbarkeitsgrenzen.DiBNachfuehrung.NBIdent', qname='odmav_dmav_dienstbarkeitsgrenzen_v1_1.DiBNachfuehrung.NBIdent')
    identifikator = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='DMAV_Dienstbarkeitsgrenzen_V1_1.Dienstbarkeitsgrenzen.DiBNachfuehrung.Identifikator', qname='odmav_dmav_dienstbarkeitsgrenzen_v1_1.DiBNachfuehrung.Identifikator')
    beschreibung = ili_field(models.CharField(max_length=60, null=False, blank=False), oid='DMAV_Dienstbarkeitsgrenzen_V1_1.Dienstbarkeitsgrenzen.DiBNachfuehrung.Beschreibung', qname='odmav_dmav_dienstbarkeitsgrenzen_v1_1.DiBNachfuehrung.Beschreibung')
    perimeter = ili_field(models.CurvePolygonField(srid=2056, null=True, blank=True), oid='DMAV_Dienstbarkeitsgrenzen_V1_1.Dienstbarkeitsgrenzen.DiBNachfuehrung.Perimeter', qname='odmav_dmav_dienstbarkeitsgrenzen_v1_1.DiBNachfuehrung.Perimeter')
    gueltiger_eintrag = ili_field(models.CharField(max_length=255, null=False, blank=False), oid='DMAV_Dienstbarkeitsgrenzen_V1_1.Dienstbarkeitsgrenzen.DiBNachfuehrung.GueltigerEintrag', qname='odmav_dmav_dienstbarkeitsgrenzen_v1_1.DiBNachfuehrung.GueltigerEintrag')
    grundbucheintrag = ili_field(models.CharField(max_length=255, null=True, blank=True), oid='DMAV_Dienstbarkeitsgrenzen_V1_1.Dienstbarkeitsgrenzen.DiBNachfuehrung.Grundbucheintrag', qname='odmav_dmav_dienstbarkeitsgrenzen_v1_1.DiBNachfuehrung.Grundbucheintrag')

    class Meta:
        db_table = 'odmav_dmav_dienstbarkeitsgrenzen_v1_1__di_bnachfuehrung'

@interlis_model(oid='DMAV_Dienstbarkeitsgrenzen_V1_1.Dienstbarkeitsgrenzen.Flaechenelement', qname='odmav_dmav_dienstbarkeitsgrenzen_v1_1.Flaechenelement')
class Flaechenelement(models.Model):
    geometrie = ili_field(models.CurvePolygonField(srid=2056, null=False, blank=False), oid='DMAV_Dienstbarkeitsgrenzen_V1_1.Dienstbarkeitsgrenzen.Flaechenelement.Geometrie', qname='odmav_dmav_dienstbarkeitsgrenzen_v1_1.Flaechenelement.Geometrie')

    class Meta:
        db_table = 'odmav_dmav_dienstbarkeitsgrenzen_v1_1__flaechenelement'

@interlis_model(oid='DMAV_Dienstbarkeitsgrenzen_V1_1.Dienstbarkeitsgrenzen.Linienelement', qname='odmav_dmav_dienstbarkeitsgrenzen_v1_1.Linienelement')
class Linienelement(models.Model):
    geometrie = ili_field(models.LineStringField(srid=2056, null=False, blank=False), oid='DMAV_Dienstbarkeitsgrenzen_V1_1.Dienstbarkeitsgrenzen.Linienelement.Geometrie', qname='odmav_dmav_dienstbarkeitsgrenzen_v1_1.Linienelement.Geometrie')

    class Meta:
        db_table = 'odmav_dmav_dienstbarkeitsgrenzen_v1_1__linienelement'

@interlis_model(oid='DMAV_Dienstbarkeitsgrenzen_V1_1.Dienstbarkeitsgrenzen.Punktelement', qname='odmav_dmav_dienstbarkeitsgrenzen_v1_1.Punktelement')
class Punktelement(models.Model):
    geometrie = ili_field(models.PointField(srid=2056, null=False, blank=False), oid='DMAV_Dienstbarkeitsgrenzen_V1_1.Dienstbarkeitsgrenzen.Punktelement.Geometrie', qname='odmav_dmav_dienstbarkeitsgrenzen_v1_1.Punktelement.Geometrie')
    symbol_ori = ili_field(models.FloatField(null=True, blank=True), oid='DMAV_Dienstbarkeitsgrenzen_V1_1.Dienstbarkeitsgrenzen.Punktelement.SymbolOri', qname='odmav_dmav_dienstbarkeitsgrenzen_v1_1.Punktelement.SymbolOri')

    class Meta:
        db_table = 'odmav_dmav_dienstbarkeitsgrenzen_v1_1__punktelement'

@interlis_model(oid='DMAV_Dienstbarkeitsgrenzen_V1_1.Dienstbarkeitsgrenzen.Dienstbarkeitsgrenze', qname='odmav_dmav_dienstbarkeitsgrenzen_v1_1.Dienstbarkeitsgrenze')
class Dienstbarkeitsgrenze(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_Dienstbarkeitsgrenzen_V1_1.Dienstbarkeitsgrenzen.Dienstbarkeitsgrenze.tid', qname='odmav_dmav_dienstbarkeitsgrenzen_v1_1.Dienstbarkeitsgrenze.tid')
    ereid = ili_field(models.CharField(max_length=22, null=True, blank=True), oid='DMAV_Dienstbarkeitsgrenzen_V1_1.Dienstbarkeitsgrenzen.Dienstbarkeitsgrenze.EREID', qname='odmav_dmav_dienstbarkeitsgrenzen_v1_1.Dienstbarkeitsgrenze.EREID')
    nbident = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='DMAV_Dienstbarkeitsgrenzen_V1_1.Dienstbarkeitsgrenzen.Dienstbarkeitsgrenze.NBIdent', qname='odmav_dmav_dienstbarkeitsgrenzen_v1_1.Dienstbarkeitsgrenze.NBIdent')
    dienstbarkeitsnummer = ili_field(models.CharField(max_length=12, null=True, blank=True), oid='DMAV_Dienstbarkeitsgrenzen_V1_1.Dienstbarkeitsgrenzen.Dienstbarkeitsgrenze.Dienstbarkeitsnummer', qname='odmav_dmav_dienstbarkeitsgrenzen_v1_1.Dienstbarkeitsgrenze.Dienstbarkeitsnummer')
    dienstbarkeitsart = ili_field(models.CharField(max_length=60, null=True, blank=True), oid='DMAV_Dienstbarkeitsgrenzen_V1_1.Dienstbarkeitsgrenzen.Dienstbarkeitsgrenze.Dienstbarkeitsart', qname='odmav_dmav_dienstbarkeitsgrenzen_v1_1.Dienstbarkeitsgrenze.Dienstbarkeitsart')
    hoehe = ili_field(models.FloatField(null=True, blank=True), oid='DMAV_Dienstbarkeitsgrenzen_V1_1.Dienstbarkeitsgrenzen.Dienstbarkeitsgrenze.Hoehe', qname='odmav_dmav_dienstbarkeitsgrenzen_v1_1.Dienstbarkeitsgrenze.Hoehe')
    ist_vollstaendig = ili_field(models.BooleanField(default=False), oid='DMAV_Dienstbarkeitsgrenzen_V1_1.Dienstbarkeitsgrenzen.Dienstbarkeitsgrenze.IstVollstaendig', qname='odmav_dmav_dienstbarkeitsgrenzen_v1_1.Dienstbarkeitsgrenze.IstVollstaendig')
    herkunft = ili_field(models.ForeignKey('odmav_dmav_dienstbarkeitsgrenzen_v1_1.HerkunftValue', on_delete=models.PROTECT, related_name='+', null=True, blank=True), oid='DMAV_Dienstbarkeitsgrenzen_V1_1.Dienstbarkeitsgrenzen.Dienstbarkeitsgrenze.Herkunft', qname='odmav_dmav_dienstbarkeitsgrenzen_v1_1.Dienstbarkeitsgrenze.Herkunft')
    flaechenelement = ili_field(models.MultiSurfaceField(srid=2056, null=True, blank=True), oid='DMAV_Dienstbarkeitsgrenzen_V1_1.Dienstbarkeitsgrenzen.Dienstbarkeitsgrenze.Flaechenelement', qname='odmav_dmav_dienstbarkeitsgrenzen_v1_1.Dienstbarkeitsgrenze.Flaechenelement')
    linienelement = ili_field(models.MultiLineStringField(srid=2056, null=True, blank=True), oid='DMAV_Dienstbarkeitsgrenzen_V1_1.Dienstbarkeitsgrenzen.Dienstbarkeitsgrenze.Linienelement', qname='odmav_dmav_dienstbarkeitsgrenzen_v1_1.Dienstbarkeitsgrenze.Linienelement')
    punktelement = ili_field(models.MultiPointField(srid=2056, null=True, blank=True), oid='DMAV_Dienstbarkeitsgrenzen_V1_1.Dienstbarkeitsgrenzen.Dienstbarkeitsgrenze.Punktelement', qname='odmav_dmav_dienstbarkeitsgrenzen_v1_1.Dienstbarkeitsgrenze.Punktelement')
    textposition = ili_field(models.MultiLineStringField(srid=2056, null=True, blank=True), oid='DMAV_Dienstbarkeitsgrenzen_V1_1.Dienstbarkeitsgrenzen.Dienstbarkeitsgrenze.Textposition', qname='odmav_dmav_dienstbarkeitsgrenzen_v1_1.Dienstbarkeitsgrenze.Textposition')
    entstehung = ili_field(models.ForeignKey('odmav_dmav_dienstbarkeitsgrenzen_v1_1.DiBNachfuehrung', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Dienstbarkeitsgrenzen_V1_1.Dienstbarkeitsgrenzen.Entstehung_Dienstbarkeitsgrenze.Entstehung', qname='odmav_dmav_dienstbarkeitsgrenzen_v1_1.Dienstbarkeitsgrenze.Entstehung')
    untergang = ili_field(models.ForeignKey('odmav_dmav_dienstbarkeitsgrenzen_v1_1.DiBNachfuehrung', on_delete=models.PROTECT, related_name='+', null=True, blank=True), oid='DMAV_Dienstbarkeitsgrenzen_V1_1.Dienstbarkeitsgrenzen.Untergang_Dienstbarkeitsgrenze.Untergang', qname='odmav_dmav_dienstbarkeitsgrenzen_v1_1.Dienstbarkeitsgrenze.Untergang')

    class Meta:
        db_table = 'odmav_dmav_dienstbarkeitsgrenzen_v1_1__dienstbarkeitsgrenze'
