"""Generated by ili2django. Do not edit manually."""

from django.contrib.gis.db import models

from ili2django.decorators import ili_field, interlis_model

@interlis_model(oid='DMAV_Toleranzstufen_V1_1.Toleranzstufen.Toleranzstufe.Toleranzstufe_ENUM', qname='odmav_dmav_toleranzstufen_v1_1.ToleranzstufeToleranzstufeEnum')
class ToleranzstufeToleranzstufeEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_Toleranzstufen_V1_1.Toleranzstufen.Toleranzstufe.Toleranzstufe_ENUM.code', qname='odmav_dmav_toleranzstufen_v1_1.ToleranzstufeToleranzstufeEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_Toleranzstufen_V1_1.Toleranzstufen.Toleranzstufe.Toleranzstufe_ENUM.label', qname='odmav_dmav_toleranzstufen_v1_1.ToleranzstufeToleranzstufeEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['TS1', 'TS2', 'TS3', 'TS4', 'TS5']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_toleranzstufen_v1_1__toleranzstufe_tolera_65133b6b7f'

@interlis_model(oid='DMAV_Toleranzstufen_V1_1.Toleranzstufen.TSNachfuehrung', qname='odmav_dmav_toleranzstufen_v1_1.TSNachfuehrung')
class TSNachfuehrung(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_Toleranzstufen_V1_1.Toleranzstufen.TSNachfuehrung.tid', qname='odmav_dmav_toleranzstufen_v1_1.TSNachfuehrung.tid')
    nbident = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='DMAV_Toleranzstufen_V1_1.Toleranzstufen.TSNachfuehrung.NBIdent', qname='odmav_dmav_toleranzstufen_v1_1.TSNachfuehrung.NBIdent')
    identifikator = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='DMAV_Toleranzstufen_V1_1.Toleranzstufen.TSNachfuehrung.Identifikator', qname='odmav_dmav_toleranzstufen_v1_1.TSNachfuehrung.Identifikator')
    beschreibung = ili_field(models.CharField(max_length=60, null=False, blank=False), oid='DMAV_Toleranzstufen_V1_1.Toleranzstufen.TSNachfuehrung.Beschreibung', qname='odmav_dmav_toleranzstufen_v1_1.TSNachfuehrung.Beschreibung')
    perimeter = ili_field(models.CurvePolygonField(srid=2056, null=True, blank=True), oid='DMAV_Toleranzstufen_V1_1.Toleranzstufen.TSNachfuehrung.Perimeter', qname='odmav_dmav_toleranzstufen_v1_1.TSNachfuehrung.Perimeter')
    gueltiger_eintrag = ili_field(models.CharField(max_length=255, null=False, blank=False), oid='DMAV_Toleranzstufen_V1_1.Toleranzstufen.TSNachfuehrung.GueltigerEintrag', qname='odmav_dmav_toleranzstufen_v1_1.TSNachfuehrung.GueltigerEintrag')

    class Meta:
        db_table = 'odmav_dmav_toleranzstufen_v1_1__tsnachfuehrung'

@interlis_model(oid='DMAV_Toleranzstufen_V1_1.Toleranzstufen.Toleranzstufe', qname='odmav_dmav_toleranzstufen_v1_1.Toleranzstufe')
class Toleranzstufe(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_Toleranzstufen_V1_1.Toleranzstufen.Toleranzstufe.tid', qname='odmav_dmav_toleranzstufen_v1_1.Toleranzstufe.tid')
    nbident = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='DMAV_Toleranzstufen_V1_1.Toleranzstufen.Toleranzstufe.NBIdent', qname='odmav_dmav_toleranzstufen_v1_1.Toleranzstufe.NBIdent')
    identifikator = ili_field(models.CharField(max_length=12, null=True, blank=True), oid='DMAV_Toleranzstufen_V1_1.Toleranzstufen.Toleranzstufe.Identifikator', qname='odmav_dmav_toleranzstufen_v1_1.Toleranzstufe.Identifikator')
    geometrie = ili_field(models.CurvePolygonField(srid=2056, null=False, blank=False), oid='DMAV_Toleranzstufen_V1_1.Toleranzstufen.Toleranzstufe.Geometrie', qname='odmav_dmav_toleranzstufen_v1_1.Toleranzstufe.Geometrie')
    toleranzstufe = ili_field(models.ForeignKey('odmav_dmav_toleranzstufen_v1_1.ToleranzstufeToleranzstufeEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Toleranzstufen_V1_1.Toleranzstufen.Toleranzstufe.Toleranzstufe', qname='odmav_dmav_toleranzstufen_v1_1.Toleranzstufe.Toleranzstufe')
    fiktiv = ili_field(models.BooleanField(default=False), oid='DMAV_Toleranzstufen_V1_1.Toleranzstufen.Toleranzstufe.Fiktiv', qname='odmav_dmav_toleranzstufen_v1_1.Toleranzstufe.Fiktiv')
    entstehung = ili_field(models.ForeignKey('odmav_dmav_toleranzstufen_v1_1.TSNachfuehrung', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Toleranzstufen_V1_1.Toleranzstufen.Entstehung_Toleranzstufe.Entstehung', qname='odmav_dmav_toleranzstufen_v1_1.Toleranzstufe.Entstehung')

    class Meta:
        db_table = 'odmav_dmav_toleranzstufen_v1_1__toleranzstufe'
