"""Generated by ili2django. Do not edit manually."""

from django.contrib.gis.db import models
from django.utils.translation import gettext_lazy as _

from ili2django.choices import IliChoice, IliChoices
from ili2django.decorators import ili_field, interlis_model

@interlis_model(oid='INTERLIS.TIMESYSTEMS.CALENDAR', qname='odmav_interlis.CALENDAR')
class CALENDAR(models.Model):
    unit = ili_field(models.IntegerField(null=True, blank=True), oid='INTERLIS.TIMESYSTEMS.CALENDAR.Unit', qname='odmav_interlis.CALENDAR.Unit')

    class Meta:
        db_table = 'odmav_interlis__calendar'

@interlis_model(oid='INTERLIS.TIMESYSTEMS.TIMEOFDAYSYS', qname='odmav_interlis.TIMEOFDAYSYS')
class TIMEOFDAYSYS(models.Model):
    unit = ili_field(models.IntegerField(null=True, blank=True), oid='INTERLIS.TIMESYSTEMS.TIMEOFDAYSYS.Unit', qname='odmav_interlis.TIMEOFDAYSYS.Unit')

    class Meta:
        db_table = 'odmav_interlis__timeofdaysys'
