"""Generated by ili2django. Do not edit manually."""

from django.contrib.gis.db import models
from django.utils.translation import gettext_lazy as _

from ili2django.choices import IliChoice, IliChoices
from ili2django.decorators import ili_field, interlis_model

@interlis_model(oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Sprache', qname='odmav_dmav_gebaeudeadressen_v1_1.Sprache')
class SpracheValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Sprache.code', qname='odmav_dmav_gebaeudeadressen_v1_1.Sprache.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Sprache.label', qname='odmav_dmav_gebaeudeadressen_v1_1.Sprache.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['de', 'fr', 'it', 'rm']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_gebaeudeadressen_v1_1__sprache_value'

class SpracheValueChoices(IliChoices):
    DE = IliChoice('de', _('de'), order=0)
    FR = IliChoice('fr', _('fr'), order=1)
    IT = IliChoice('it', _('it'), order=2)
    RM = IliChoice('rm', _('rm'), order=3)

@interlis_model(oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Lokalisationsname.Sprache_ENUM', qname='odmav_dmav_gebaeudeadressen_v1_1.LokalisationsnameSpracheEnum')
class LokalisationsnameSpracheEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Lokalisationsname.Sprache_ENUM.code', qname='odmav_dmav_gebaeudeadressen_v1_1.LokalisationsnameSpracheEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Lokalisationsname.Sprache_ENUM.label', qname='odmav_dmav_gebaeudeadressen_v1_1.LokalisationsnameSpracheEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['de', 'fr', 'it', 'rm']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_gebaeudeadressen_v1_1__lokalisationsname__e783feadeb'

class LokalisationsnameSpracheEnumValueChoices(IliChoices):
    DE = IliChoice('de', _('de'), order=0)
    FR = IliChoice('fr', _('fr'), order=1)
    IT = IliChoice('it', _('it'), order=2)
    RM = IliChoice('rm', _('rm'), order=3)

@interlis_model(oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Lokalisation.Lokalisationsstatus_ENUM', qname='odmav_dmav_gebaeudeadressen_v1_1.LokalisationLokalisationsstatusEnum')
class LokalisationLokalisationsstatusEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Lokalisation.Lokalisationsstatus_ENUM.code', qname='odmav_dmav_gebaeudeadressen_v1_1.LokalisationLokalisationsstatusEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Lokalisation.Lokalisationsstatus_ENUM.label', qname='odmav_dmav_gebaeudeadressen_v1_1.LokalisationLokalisationsstatusEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['projektiert', 'real', 'vergangen']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_gebaeudeadressen_v1_1__lokalisation_lokal_c1c1577f24'

class LokalisationLokalisationsstatusEnumValueChoices(IliChoices):
    PROJEKTIERT = IliChoice('projektiert', _('projektiert'), order=0)
    REAL = IliChoice('real', _('real'), order=1)
    VERGANGEN = IliChoice('vergangen', _('vergangen'), order=2)

@interlis_model(oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Lokalisation.Lokalisationsart_ENUM', qname='odmav_dmav_gebaeudeadressen_v1_1.LokalisationLokalisationsartEnum')
class LokalisationLokalisationsartEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Lokalisation.Lokalisationsart_ENUM.code', qname='odmav_dmav_gebaeudeadressen_v1_1.LokalisationLokalisationsartEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Lokalisation.Lokalisationsart_ENUM.label', qname='odmav_dmav_gebaeudeadressen_v1_1.LokalisationLokalisationsartEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['BenanntesGebiet', 'Strasse', 'Platz']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_gebaeudeadressen_v1_1__lokalisation_lokal_d1b5c7ce74'

class LokalisationLokalisationsartEnumValueChoices(IliChoices):
    BENANNTES_GEBIET = IliChoice('BenanntesGebiet', _('BenanntesGebiet'), order=0)
    STRASSE = IliChoice('Strasse', _('Strasse'), order=1)
    PLATZ = IliChoice('Platz', _('Platz'), order=2)

@interlis_model(oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Lokalisation.Nummerierungsprinzip_ENUM', qname='odmav_dmav_gebaeudeadressen_v1_1.LokalisationNummerierungsprinzipEnum')
class LokalisationNummerierungsprinzipEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Lokalisation.Nummerierungsprinzip_ENUM.code', qname='odmav_dmav_gebaeudeadressen_v1_1.LokalisationNummerierungsprinzipEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Lokalisation.Nummerierungsprinzip_ENUM.label', qname='odmav_dmav_gebaeudeadressen_v1_1.LokalisationNummerierungsprinzipEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['keineNummern', 'beliebig', 'aufsteigend', 'ungeradelinks', 'geradelinks']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_gebaeudeadressen_v1_1__lokalisation_numme_e134997c94'

class LokalisationNummerierungsprinzipEnumValueChoices(IliChoices):
    KEINE_NUMMERN = IliChoice('keineNummern', _('keineNummern'), order=0)
    BELIEBIG = IliChoice('beliebig', _('beliebig'), order=1)
    AUFSTEIGEND = IliChoice('aufsteigend', _('aufsteigend'), order=2)
    UNGERADELINKS = IliChoice('ungeradelinks', _('ungeradelinks'), order=3)
    GERADELINKS = IliChoice('geradelinks', _('geradelinks'), order=4)

@interlis_model(oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Gebaeudename.Sprache_ENUM', qname='odmav_dmav_gebaeudeadressen_v1_1.GebaeudenameSpracheEnum')
class GebaeudenameSpracheEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Gebaeudename.Sprache_ENUM.code', qname='odmav_dmav_gebaeudeadressen_v1_1.GebaeudenameSpracheEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Gebaeudename.Sprache_ENUM.label', qname='odmav_dmav_gebaeudeadressen_v1_1.GebaeudenameSpracheEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['de', 'fr', 'it', 'rm']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_gebaeudeadressen_v1_1__gebaeudename_sprac_552ce1697e'

class GebaeudenameSpracheEnumValueChoices(IliChoices):
    DE = IliChoice('de', _('de'), order=0)
    FR = IliChoice('fr', _('fr'), order=1)
    IT = IliChoice('it', _('it'), order=2)
    RM = IliChoice('rm', _('rm'), order=3)

@interlis_model(oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Gebaeudebeschreibung.Sprache_ENUM', qname='odmav_dmav_gebaeudeadressen_v1_1.GebaeudebeschreibungSpracheEnum')
class GebaeudebeschreibungSpracheEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Gebaeudebeschreibung.Sprache_ENUM.code', qname='odmav_dmav_gebaeudeadressen_v1_1.GebaeudebeschreibungSpracheEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Gebaeudebeschreibung.Sprache_ENUM.label', qname='odmav_dmav_gebaeudeadressen_v1_1.GebaeudebeschreibungSpracheEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['de', 'fr', 'it', 'rm']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_gebaeudeadressen_v1_1__gebaeudebeschreibu_323934bcab'

class GebaeudebeschreibungSpracheEnumValueChoices(IliChoices):
    DE = IliChoice('de', _('de'), order=0)
    FR = IliChoice('fr', _('fr'), order=1)
    IT = IliChoice('it', _('it'), order=2)
    RM = IliChoice('rm', _('rm'), order=3)

@interlis_model(oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Gebaeudeeingang.Gebaeudestatus_ENUM', qname='odmav_dmav_gebaeudeadressen_v1_1.GebaeudeeingangGebaeudestatusEnum')
class GebaeudeeingangGebaeudestatusEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Gebaeudeeingang.Gebaeudestatus_ENUM.code', qname='odmav_dmav_gebaeudeadressen_v1_1.GebaeudeeingangGebaeudestatusEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Gebaeudeeingang.Gebaeudestatus_ENUM.label', qname='odmav_dmav_gebaeudeadressen_v1_1.GebaeudeeingangGebaeudestatusEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['projektiert', 'real', 'vergangen']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_gebaeudeadressen_v1_1__gebaeudeeingang_ge_c4295b3252'

class GebaeudeeingangGebaeudestatusEnumValueChoices(IliChoices):
    PROJEKTIERT = IliChoice('projektiert', _('projektiert'), order=0)
    REAL = IliChoice('real', _('real'), order=1)
    VERGANGEN = IliChoice('vergangen', _('vergangen'), order=2)

@interlis_model(oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Gebaeudeeingang.ImModul_ENUM', qname='odmav_dmav_gebaeudeadressen_v1_1.GebaeudeeingangImModulEnum')
class GebaeudeeingangImModulEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Gebaeudeeingang.ImModul_ENUM.code', qname='odmav_dmav_gebaeudeadressen_v1_1.GebaeudeeingangImModulEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Gebaeudeeingang.ImModul_ENUM.label', qname='odmav_dmav_gebaeudeadressen_v1_1.GebaeudeeingangImModulEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['Bodenbedeckung', 'Einzelobjekte']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_gebaeudeadressen_v1_1__gebaeudeeingang_im_5cb322650b'

class GebaeudeeingangImModulEnumValueChoices(IliChoices):
    BODENBEDECKUNG = IliChoice('Bodenbedeckung', _('Bodenbedeckung'), order=0)
    EINZELOBJEKTE = IliChoice('Einzelobjekte', _('Einzelobjekte'), order=1)

@interlis_model(oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.GANachfuehrung', qname='odmav_dmav_gebaeudeadressen_v1_1.GANachfuehrung')
class GANachfuehrung(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.GANachfuehrung.tid', qname='odmav_dmav_gebaeudeadressen_v1_1.GANachfuehrung.tid')
    nbident = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.GANachfuehrung.NBIdent', qname='odmav_dmav_gebaeudeadressen_v1_1.GANachfuehrung.NBIdent')
    identifikator = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.GANachfuehrung.Identifikator', qname='odmav_dmav_gebaeudeadressen_v1_1.GANachfuehrung.Identifikator')
    beschreibung = ili_field(models.CharField(max_length=60, null=False, blank=False), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.GANachfuehrung.Beschreibung', qname='odmav_dmav_gebaeudeadressen_v1_1.GANachfuehrung.Beschreibung')
    perimeter = ili_field(models.CurvePolygonField(srid=2056, null=True, blank=True), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.GANachfuehrung.Perimeter', qname='odmav_dmav_gebaeudeadressen_v1_1.GANachfuehrung.Perimeter')
    gueltiger_eintrag = ili_field(models.CharField(max_length=255, null=False, blank=False), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.GANachfuehrung.GueltigerEintrag', qname='odmav_dmav_gebaeudeadressen_v1_1.GANachfuehrung.GueltigerEintrag')

    class Meta:
        db_table = 'odmav_dmav_gebaeudeadressen_v1_1__ganachfuehrung'

@interlis_model(oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Lokalisationsname', qname='odmav_dmav_gebaeudeadressen_v1_1.Lokalisationsname')
class Lokalisationsname(models.Model):
    name = ili_field(models.CharField(max_length=60, null=False, blank=False), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Lokalisationsname.Name', qname='odmav_dmav_gebaeudeadressen_v1_1.Lokalisationsname.Name')
    name_kurz = ili_field(models.CharField(max_length=24, null=True, blank=True), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Lokalisationsname.NameKurz', qname='odmav_dmav_gebaeudeadressen_v1_1.Lokalisationsname.NameKurz')
    name_als_index = ili_field(models.CharField(max_length=16, null=True, blank=True), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Lokalisationsname.NameAlsIndex', qname='odmav_dmav_gebaeudeadressen_v1_1.Lokalisationsname.NameAlsIndex')
    sprache = ili_field(models.ForeignKey('odmav_dmav_gebaeudeadressen_v1_1.LokalisationsnameSpracheEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Lokalisationsname.Sprache', qname='odmav_dmav_gebaeudeadressen_v1_1.Lokalisationsname.Sprache')
    textposition = ili_field(models.MultiLineStringField(srid=2056, null=True, blank=True), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Lokalisationsname.Textposition', qname='odmav_dmav_gebaeudeadressen_v1_1.Lokalisationsname.Textposition')

    class Meta:
        db_table = 'odmav_dmav_gebaeudeadressen_v1_1__lokalisationsname'

@interlis_model(oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.BenanntesGebiet', qname='odmav_dmav_gebaeudeadressen_v1_1.BenanntesGebiet')
class BenanntesGebiet(models.Model):
    geometrie = ili_field(models.CurvePolygonField(srid=2056, null=False, blank=False), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.BenanntesGebiet.Geometrie', qname='odmav_dmav_gebaeudeadressen_v1_1.BenanntesGebiet.Geometrie')

    class Meta:
        db_table = 'odmav_dmav_gebaeudeadressen_v1_1__benanntes_gebiet'

@interlis_model(oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Strassenstueck', qname='odmav_dmav_gebaeudeadressen_v1_1.Strassenstueck')
class Strassenstueck(models.Model):
    geometrie = ili_field(models.LineStringField(srid=2056, null=False, blank=False), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Strassenstueck.Geometrie', qname='odmav_dmav_gebaeudeadressen_v1_1.Strassenstueck.Geometrie')
    ist_achse = ili_field(models.BooleanField(default=False), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Strassenstueck.IstAchse', qname='odmav_dmav_gebaeudeadressen_v1_1.Strassenstueck.IstAchse')

    class Meta:
        db_table = 'odmav_dmav_gebaeudeadressen_v1_1__strassenstueck'

@interlis_model(oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Lokalisation', qname='odmav_dmav_gebaeudeadressen_v1_1.Lokalisation')
class Lokalisation(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Lokalisation.tid', qname='odmav_dmav_gebaeudeadressen_v1_1.Lokalisation.tid')
    lokalisation_nummer = ili_field(models.CharField(max_length=12, null=True, blank=True), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Lokalisation.LokalisationNummer', qname='odmav_dmav_gebaeudeadressen_v1_1.Lokalisation.LokalisationNummer')
    attribute_provisorisch = ili_field(models.BooleanField(default=False), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Lokalisation.AttributeProvisorisch', qname='odmav_dmav_gebaeudeadressen_v1_1.Lokalisation.AttributeProvisorisch')
    ist_offizielle_bezeichnung = ili_field(models.BooleanField(default=False), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Lokalisation.IstOffizielleBezeichnung', qname='odmav_dmav_gebaeudeadressen_v1_1.Lokalisation.IstOffizielleBezeichnung')
    lokalisationsstatus = ili_field(models.ForeignKey('odmav_dmav_gebaeudeadressen_v1_1.LokalisationLokalisationsstatusEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Lokalisation.Lokalisationsstatus', qname='odmav_dmav_gebaeudeadressen_v1_1.Lokalisation.Lokalisationsstatus')
    in_aenderung = ili_field(models.BooleanField(default=False), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Lokalisation.InAenderung', qname='odmav_dmav_gebaeudeadressen_v1_1.Lokalisation.InAenderung')
    lokalisationsart = ili_field(models.ForeignKey('odmav_dmav_gebaeudeadressen_v1_1.LokalisationLokalisationsartEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Lokalisation.Lokalisationsart', qname='odmav_dmav_gebaeudeadressen_v1_1.Lokalisation.Lokalisationsart')
    nummerierungsprinzip = ili_field(models.ForeignKey('odmav_dmav_gebaeudeadressen_v1_1.LokalisationNummerierungsprinzipEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Lokalisation.Nummerierungsprinzip', qname='odmav_dmav_gebaeudeadressen_v1_1.Lokalisation.Nummerierungsprinzip')
    esid = ili_field(models.IntegerField(null=True, blank=True), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Lokalisation.ESID', qname='odmav_dmav_gebaeudeadressen_v1_1.Lokalisation.ESID')
    lokalisation_name = ili_field(models.MultiLineStringField(srid=2056, null=False, blank=False), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Lokalisation.LokalisationName', qname='odmav_dmav_gebaeudeadressen_v1_1.Lokalisation.LokalisationName')
    benanntes_gebiet = ili_field(models.MultiSurfaceField(srid=2056, null=True, blank=True), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Lokalisation.BenanntesGebiet', qname='odmav_dmav_gebaeudeadressen_v1_1.Lokalisation.BenanntesGebiet')
    strassenstueck = ili_field(models.MultiLineStringField(srid=2056, null=True, blank=True), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Lokalisation.Strassenstueck', qname='odmav_dmav_gebaeudeadressen_v1_1.Lokalisation.Strassenstueck')
    entstehung = ili_field(models.ForeignKey('odmav_dmav_gebaeudeadressen_v1_1.GANachfuehrung', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Entstehung_Lokalisation.Entstehung', qname='odmav_dmav_gebaeudeadressen_v1_1.Lokalisation.Entstehung')

    class Meta:
        db_table = 'odmav_dmav_gebaeudeadressen_v1_1__lokalisation'

@interlis_model(oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Gebaeudename', qname='odmav_dmav_gebaeudeadressen_v1_1.Gebaeudename')
class Gebaeudename(models.Model):
    name = ili_field(models.CharField(max_length=60, null=False, blank=False), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Gebaeudename.Name', qname='odmav_dmav_gebaeudeadressen_v1_1.Gebaeudename.Name')
    name_kurz = ili_field(models.CharField(max_length=24, null=True, blank=True), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Gebaeudename.NameKurz', qname='odmav_dmav_gebaeudeadressen_v1_1.Gebaeudename.NameKurz')
    name_als_index = ili_field(models.CharField(max_length=16, null=True, blank=True), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Gebaeudename.NameAlsIndex', qname='odmav_dmav_gebaeudeadressen_v1_1.Gebaeudename.NameAlsIndex')
    sprache = ili_field(models.ForeignKey('odmav_dmav_gebaeudeadressen_v1_1.GebaeudenameSpracheEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Gebaeudename.Sprache', qname='odmav_dmav_gebaeudeadressen_v1_1.Gebaeudename.Sprache')
    textposition = ili_field(models.MultiLineStringField(srid=2056, null=True, blank=True), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Gebaeudename.Textposition', qname='odmav_dmav_gebaeudeadressen_v1_1.Gebaeudename.Textposition')

    class Meta:
        db_table = 'odmav_dmav_gebaeudeadressen_v1_1__gebaeudename'

@interlis_model(oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Gebaeudebeschreibung', qname='odmav_dmav_gebaeudeadressen_v1_1.Gebaeudebeschreibung')
class Gebaeudebeschreibung(models.Model):
    beschreibung = ili_field(models.CharField(max_length=100, null=False, blank=False), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Gebaeudebeschreibung.Beschreibung', qname='odmav_dmav_gebaeudeadressen_v1_1.Gebaeudebeschreibung.Beschreibung')
    sprache = ili_field(models.ForeignKey('odmav_dmav_gebaeudeadressen_v1_1.GebaeudebeschreibungSpracheEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Gebaeudebeschreibung.Sprache', qname='odmav_dmav_gebaeudeadressen_v1_1.Gebaeudebeschreibung.Sprache')

    class Meta:
        db_table = 'odmav_dmav_gebaeudeadressen_v1_1__gebaeudebeschreibung'

@interlis_model(oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Gebaeudeeingang', qname='odmav_dmav_gebaeudeadressen_v1_1.Gebaeudeeingang')
class Gebaeudeeingang(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Gebaeudeeingang.tid', qname='odmav_dmav_gebaeudeadressen_v1_1.Gebaeudeeingang.tid')
    gebaeudestatus = ili_field(models.ForeignKey('odmav_dmav_gebaeudeadressen_v1_1.GebaeudeeingangGebaeudestatusEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Gebaeudeeingang.Gebaeudestatus', qname='odmav_dmav_gebaeudeadressen_v1_1.Gebaeudeeingang.Gebaeudestatus')
    in_aenderung = ili_field(models.BooleanField(default=False), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Gebaeudeeingang.InAenderung', qname='odmav_dmav_gebaeudeadressen_v1_1.Gebaeudeeingang.InAenderung')
    attribute_provisorisch = ili_field(models.BooleanField(default=False), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Gebaeudeeingang.AttributeProvisorisch', qname='odmav_dmav_gebaeudeadressen_v1_1.Gebaeudeeingang.AttributeProvisorisch')
    ist_offizielle_gebaeudeadresse = ili_field(models.BooleanField(default=False), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Gebaeudeeingang.IstOffizielleGebaeudeadresse', qname='odmav_dmav_gebaeudeadressen_v1_1.Gebaeudeeingang.IstOffizielleGebaeudeadresse')
    geometrie = ili_field(models.PointField(srid=2056, null=False, blank=False), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Gebaeudeeingang.Geometrie', qname='odmav_dmav_gebaeudeadressen_v1_1.Gebaeudeeingang.Geometrie')
    hoehe_ueber_grund = ili_field(models.IntegerField(null=True, blank=True), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Gebaeudeeingang.HoeheUeberGrund', qname='odmav_dmav_gebaeudeadressen_v1_1.Gebaeudeeingang.HoeheUeberGrund')
    hausnummer = ili_field(models.CharField(max_length=12, null=True, blank=True), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Gebaeudeeingang.Hausnummer', qname='odmav_dmav_gebaeudeadressen_v1_1.Gebaeudeeingang.Hausnummer')
    im_modul = ili_field(models.ForeignKey('odmav_dmav_gebaeudeadressen_v1_1.GebaeudeeingangImModulEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Gebaeudeeingang.ImModul', qname='odmav_dmav_gebaeudeadressen_v1_1.Gebaeudeeingang.ImModul')
    egid = ili_field(models.IntegerField(null=True, blank=True), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Gebaeudeeingang.EGID', qname='odmav_dmav_gebaeudeadressen_v1_1.Gebaeudeeingang.EGID')
    edid = ili_field(models.IntegerField(null=True, blank=True), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Gebaeudeeingang.EDID', qname='odmav_dmav_gebaeudeadressen_v1_1.Gebaeudeeingang.EDID')
    gebaeude_name = ili_field(models.MultiLineStringField(srid=2056, null=True, blank=True), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Gebaeudeeingang.GebaeudeName', qname='odmav_dmav_gebaeudeadressen_v1_1.Gebaeudeeingang.GebaeudeName')
    gebaeude_beschreibung = ili_field(models.JSONField(default=list, null=True, blank=True), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Gebaeudeeingang.GebaeudeBeschreibung', qname='odmav_dmav_gebaeudeadressen_v1_1.Gebaeudeeingang.GebaeudeBeschreibung')
    textposition = ili_field(models.MultiLineStringField(srid=2056, null=True, blank=True), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Gebaeudeeingang.Textposition', qname='odmav_dmav_gebaeudeadressen_v1_1.Gebaeudeeingang.Textposition')
    entstehung = ili_field(models.ForeignKey('odmav_dmav_gebaeudeadressen_v1_1.GANachfuehrung', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.Entstehung_Gebaeudeeingang.Entstehung', qname='odmav_dmav_gebaeudeadressen_v1_1.Gebaeudeeingang.Entstehung')
    lokalisation = ili_field(models.ForeignKey('odmav_dmav_gebaeudeadressen_v1_1.Lokalisation', on_delete=models.PROTECT, related_name='+', null=True, blank=True), oid='DMAV_Gebaeudeadressen_V1_1.Gebaeudeadressen.LokalisationGebaeudeeingang.Lokalisation', qname='odmav_dmav_gebaeudeadressen_v1_1.Gebaeudeeingang.Lokalisation')

    class Meta:
        db_table = 'odmav_dmav_gebaeudeadressen_v1_1__gebaeudeeingang'
