"""Generated by ili2django. Do not edit manually."""

from django.contrib.gis.db import models

from ili2django.decorators import ili_field, interlis_model

@interlis_model(oid='KGK_Bodenbedeckung_V1_0.Bodenbedeckung.BB_Linienart.Art_ENUM', qname='odmav_kgk_bodenbedeckung_v1_0.BB_LinienartArtEnum')
class BBLinienartArtEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='KGK_Bodenbedeckung_V1_0.Bodenbedeckung.BB_Linienart.Art_ENUM.code', qname='odmav_kgk_bodenbedeckung_v1_0.BB_LinienartArtEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='KGK_Bodenbedeckung_V1_0.Bodenbedeckung.BB_Linienart.Art_ENUM.label', qname='odmav_kgk_bodenbedeckung_v1_0.BB_LinienartArtEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['offen_weicher_Uebergang', 'harter_Uebergang', 'unterirdisch', 'unterdrueckt_virtuell']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_kgk_bodenbedeckung_v1_0__bblinienart_art_enum_value'

@interlis_model(oid='KGK_Bodenbedeckung_V1_0.Bodenbedeckung.Bodenbedeckung.Bodenbedeckungsart_ENUM', qname='odmav_kgk_bodenbedeckung_v1_0.BodenbedeckungBodenbedeckungsartEnum')
class BodenbedeckungBodenbedeckungsartEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='KGK_Bodenbedeckung_V1_0.Bodenbedeckung.Bodenbedeckung.Bodenbedeckungsart_ENUM.code', qname='odmav_kgk_bodenbedeckung_v1_0.BodenbedeckungBodenbedeckungsartEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='KGK_Bodenbedeckung_V1_0.Bodenbedeckung.Bodenbedeckung.Bodenbedeckungsart_ENUM.label', qname='odmav_kgk_bodenbedeckung_v1_0.BodenbedeckungBodenbedeckungsartEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['befestigt.Strasse_Weg.Strasse_Weg', 'befestigt.Strasse_Weg.Strasse', 'befestigt.Strasse_Weg.Fahrweg', 'befestigt.Strasse_Weg.Velo_Fussweg', 'befestigt.Wasserbecken.Wasserbecken', 'befestigt.Wasserbecken.Schwimmbassin', 'befestigt.uebrige_befestigte.uebrige_befestigte', 'befestigt.uebrige_befestigte.Sportanlage', 'humusiert.Gartenanlage.Gartenanlage', 'humusiert.Gartenanlage.Parkanlage', 'humusiert.Gartenanlage.Sportanlage', 'humusiert.Gartenanlage.Friedhof', 'humusiert.uebrige_humusierte.uebrige_humusierte', 'humusiert.uebrige_humusierte.Verkehrsteilerflaeche', 'humusiert.uebrige_humusierte.im_Bau']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_kgk_bodenbedeckung_v1_0__bodenbedeckung_bodenb_be474a1ca1'

@interlis_model(oid='KGK_Bodenbedeckung_V1_0.Bodenbedeckung.BB_Linienart', qname='odmav_kgk_bodenbedeckung_v1_0.BB_Linienart')
class BBLinienart(models.Model):
    verlauf = ili_field(models.LineStringField(srid=2056, null=False, blank=False), oid='KGK_Bodenbedeckung_V1_0.Bodenbedeckung.BB_Linienart.Verlauf', qname='odmav_kgk_bodenbedeckung_v1_0.BB_Linienart.Verlauf')
    art = ili_field(models.ForeignKey('odmav_kgk_bodenbedeckung_v1_0.BBLinienartArtEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='KGK_Bodenbedeckung_V1_0.Bodenbedeckung.BB_Linienart.Art', qname='odmav_kgk_bodenbedeckung_v1_0.BB_Linienart.Art')

    class Meta:
        db_table = 'odmav_kgk_bodenbedeckung_v1_0__bblinienart'

@interlis_model(oid='KGK_Bodenbedeckung_V1_0.Bodenbedeckung.Bodenbedeckung', qname='odmav_kgk_bodenbedeckung_v1_0.Bodenbedeckung')
class Bodenbedeckung(models.Model):
    bodenbedeckungsart = ili_field(models.ForeignKey('odmav_kgk_bodenbedeckung_v1_0.BodenbedeckungBodenbedeckungsartEnumValue', on_delete=models.PROTECT, related_name='+', null=True, blank=True), oid='KGK_Bodenbedeckung_V1_0.Bodenbedeckung.Bodenbedeckung.Bodenbedeckungsart', qname='odmav_kgk_bodenbedeckung_v1_0.Bodenbedeckung.Bodenbedeckungsart')
    linienattribute = ili_field(models.MultiLineStringField(srid=2056, null=True, blank=True), oid='KGK_Bodenbedeckung_V1_0.Bodenbedeckung.Bodenbedeckung.Linienattribute', qname='odmav_kgk_bodenbedeckung_v1_0.Bodenbedeckung.Linienattribute')

    class Meta:
        db_table = 'odmav_kgk_bodenbedeckung_v1_0__bodenbedeckung'
