"""Generated by ili2django. Do not edit manually."""

from django.contrib.gis.db import models
from django.utils.translation import gettext_lazy as _

from ili2django.choices import IliChoice, IliChoices
from ili2django.decorators import ili_field, interlis_model

@interlis_model(oid='KGK_Bodenbedeckung_V1_0.Bodenbedeckung.BB_Linienart.Art_ENUM', qname='odmav_kgk_bodenbedeckung_v1_0.BB_LinienartArtEnum')
class BBLinienartArtEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='KGK_Bodenbedeckung_V1_0.Bodenbedeckung.BB_Linienart.Art_ENUM.code', qname='odmav_kgk_bodenbedeckung_v1_0.BB_LinienartArtEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='KGK_Bodenbedeckung_V1_0.Bodenbedeckung.BB_Linienart.Art_ENUM.label', qname='odmav_kgk_bodenbedeckung_v1_0.BB_LinienartArtEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['offen_weicher_Uebergang', 'harter_Uebergang', 'unterirdisch', 'unterdrueckt_virtuell']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_kgk_bodenbedeckung_v1_0__bblinienart_art_enum_value'

class BBLinienartArtEnumValueChoices(IliChoices):
    OFFEN_WEICHER_UEBERGANG = IliChoice('offen_weicher_Uebergang', _('offen_weicher_Uebergang'), order=0)
    HARTER_UEBERGANG = IliChoice('harter_Uebergang', _('harter_Uebergang'), order=1)
    UNTERIRDISCH = IliChoice('unterirdisch', _('unterirdisch'), order=2)
    UNTERDRUECKT_VIRTUELL = IliChoice('unterdrueckt_virtuell', _('unterdrueckt_virtuell'), order=3)

@interlis_model(oid='KGK_Bodenbedeckung_V1_0.Bodenbedeckung.Bodenbedeckung.Bodenbedeckungsart_ENUM', qname='odmav_kgk_bodenbedeckung_v1_0.BodenbedeckungBodenbedeckungsartEnum')
class BodenbedeckungBodenbedeckungsartEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='KGK_Bodenbedeckung_V1_0.Bodenbedeckung.Bodenbedeckung.Bodenbedeckungsart_ENUM.code', qname='odmav_kgk_bodenbedeckung_v1_0.BodenbedeckungBodenbedeckungsartEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='KGK_Bodenbedeckung_V1_0.Bodenbedeckung.Bodenbedeckung.Bodenbedeckungsart_ENUM.label', qname='odmav_kgk_bodenbedeckung_v1_0.BodenbedeckungBodenbedeckungsartEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['befestigt.Strasse_Weg.Strasse_Weg', 'befestigt.Strasse_Weg.Strasse', 'befestigt.Strasse_Weg.Fahrweg', 'befestigt.Strasse_Weg.Velo_Fussweg', 'befestigt.Wasserbecken.Wasserbecken', 'befestigt.Wasserbecken.Schwimmbassin', 'befestigt.uebrige_befestigte.uebrige_befestigte', 'befestigt.uebrige_befestigte.Sportanlage', 'humusiert.Gartenanlage.Gartenanlage', 'humusiert.Gartenanlage.Parkanlage', 'humusiert.Gartenanlage.Sportanlage', 'humusiert.Gartenanlage.Friedhof', 'humusiert.uebrige_humusierte.uebrige_humusierte', 'humusiert.uebrige_humusierte.Verkehrsteilerflaeche', 'humusiert.uebrige_humusierte.im_Bau']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_kgk_bodenbedeckung_v1_0__bodenbedeckung_bodenb_be474a1ca1'

class BodenbedeckungBodenbedeckungsartEnumValueChoices(IliChoices):
    BEFESTIGT_STRASSE_WEG_STRASSE_WEG = IliChoice('befestigt.Strasse_Weg.Strasse_Weg', _('Strasse_Weg'), order=0)
    BEFESTIGT_STRASSE_WEG_STRASSE = IliChoice('befestigt.Strasse_Weg.Strasse', _('Strasse'), order=1)
    BEFESTIGT_STRASSE_WEG_FAHRWEG = IliChoice('befestigt.Strasse_Weg.Fahrweg', _('Fahrweg'), order=2)
    BEFESTIGT_STRASSE_WEG_VELO_FUSSWEG = IliChoice('befestigt.Strasse_Weg.Velo_Fussweg', _('Velo_Fussweg'), order=3)
    BEFESTIGT_WASSERBECKEN_WASSERBECKEN = IliChoice('befestigt.Wasserbecken.Wasserbecken', _('Wasserbecken'), order=4)
    BEFESTIGT_WASSERBECKEN_SCHWIMMBASSIN = IliChoice('befestigt.Wasserbecken.Schwimmbassin', _('Schwimmbassin'), order=5)
    BEFESTIGT_UEBRIGE_BEFESTIGTE_UEBRIGE_BEFESTIGTE = IliChoice('befestigt.uebrige_befestigte.uebrige_befestigte', _('uebrige_befestigte'), order=6)
    BEFESTIGT_UEBRIGE_BEFESTIGTE_SPORTANLAGE = IliChoice('befestigt.uebrige_befestigte.Sportanlage', _('Sportanlage'), order=7)
    HUMUSIERT_GARTENANLAGE_GARTENANLAGE = IliChoice('humusiert.Gartenanlage.Gartenanlage', _('Gartenanlage'), order=8)
    HUMUSIERT_GARTENANLAGE_PARKANLAGE = IliChoice('humusiert.Gartenanlage.Parkanlage', _('Parkanlage'), order=9)
    HUMUSIERT_GARTENANLAGE_SPORTANLAGE = IliChoice('humusiert.Gartenanlage.Sportanlage', _('Sportanlage'), order=10)
    HUMUSIERT_GARTENANLAGE_FRIEDHOF = IliChoice('humusiert.Gartenanlage.Friedhof', _('Friedhof'), order=11)
    HUMUSIERT_UEBRIGE_HUMUSIERTE_UEBRIGE_HUMUSIERTE = IliChoice('humusiert.uebrige_humusierte.uebrige_humusierte', _('uebrige_humusierte'), order=12)
    HUMUSIERT_UEBRIGE_HUMUSIERTE_VERKEHRSTEILERFLAECHE = IliChoice('humusiert.uebrige_humusierte.Verkehrsteilerflaeche', _('Verkehrsteilerflaeche'), order=13)
    HUMUSIERT_UEBRIGE_HUMUSIERTE_IM_BAU = IliChoice('humusiert.uebrige_humusierte.im_Bau', _('im_Bau'), order=14)

@interlis_model(oid='KGK_Bodenbedeckung_V1_0.Bodenbedeckung.BB_Linienart', qname='odmav_kgk_bodenbedeckung_v1_0.BB_Linienart')
class BBLinienart(models.Model):
    verlauf = ili_field(models.LineStringField(srid=2056, null=False, blank=False), oid='KGK_Bodenbedeckung_V1_0.Bodenbedeckung.BB_Linienart.Verlauf', qname='odmav_kgk_bodenbedeckung_v1_0.BB_Linienart.Verlauf')
    art = ili_field(models.ForeignKey('odmav_kgk_bodenbedeckung_v1_0.BBLinienartArtEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='KGK_Bodenbedeckung_V1_0.Bodenbedeckung.BB_Linienart.Art', qname='odmav_kgk_bodenbedeckung_v1_0.BB_Linienart.Art')

    class Meta:
        db_table = 'odmav_kgk_bodenbedeckung_v1_0__bblinienart'

@interlis_model(oid='KGK_Bodenbedeckung_V1_0.Bodenbedeckung.Bodenbedeckung', qname='odmav_kgk_bodenbedeckung_v1_0.Bodenbedeckung')
class Bodenbedeckung(models.Model):
    bodenbedeckungsart = ili_field(models.ForeignKey('odmav_kgk_bodenbedeckung_v1_0.BodenbedeckungBodenbedeckungsartEnumValue', on_delete=models.PROTECT, related_name='+', null=True, blank=True), oid='KGK_Bodenbedeckung_V1_0.Bodenbedeckung.Bodenbedeckung.Bodenbedeckungsart', qname='odmav_kgk_bodenbedeckung_v1_0.Bodenbedeckung.Bodenbedeckungsart')
    linienattribute = ili_field(models.MultiLineStringField(srid=2056, null=True, blank=True), oid='KGK_Bodenbedeckung_V1_0.Bodenbedeckung.Bodenbedeckung.Linienattribute', qname='odmav_kgk_bodenbedeckung_v1_0.Bodenbedeckung.Linienattribute')

    class Meta:
        db_table = 'odmav_kgk_bodenbedeckung_v1_0__bodenbedeckung'
