"""Generated by ili2django. Do not edit manually."""

from django.contrib.gis.db import models
from django.utils.translation import gettext_lazy as _

from ili2django.choices import IliChoice, IliChoices
from ili2django.decorators import ili_field, interlis_model

@interlis_model(oid='AdministrativeUnitsCH_V2.CHCantons.CHCanton.Code_ENUM', qname='odmav_administrative_units_ch_v2.CHCantonCodeEnum')
class CHCantonCodeEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='AdministrativeUnitsCH_V2.CHCantons.CHCanton.Code_ENUM.code', qname='odmav_administrative_units_ch_v2.CHCantonCodeEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='AdministrativeUnitsCH_V2.CHCantons.CHCanton.Code_ENUM.label', qname='odmav_administrative_units_ch_v2.CHCantonCodeEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['ZH', 'BE', 'LU', 'UR', 'SZ', 'OW', 'NW', 'GL', 'ZG', 'FR', 'SO', 'BS', 'BL', 'SH', 'AR', 'AI', 'SG', 'GR', 'AG', 'TG', 'TI', 'VD', 'VS', 'NE', 'GE', 'JU', 'FL', 'CH']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_administrative_units_ch_v2__chcanton_code_enum_value'

class CHCantonCodeEnumValueChoices(IliChoices):
    ZH = IliChoice('ZH', _('ZH'), order=0)
    BE = IliChoice('BE', _('BE'), order=1)
    LU = IliChoice('LU', _('LU'), order=2)
    UR = IliChoice('UR', _('UR'), order=3)
    SZ = IliChoice('SZ', _('SZ'), order=4)
    OW = IliChoice('OW', _('OW'), order=5)
    NW = IliChoice('NW', _('NW'), order=6)
    GL = IliChoice('GL', _('GL'), order=7)
    ZG = IliChoice('ZG', _('ZG'), order=8)
    FR = IliChoice('FR', _('FR'), order=9)
    SO = IliChoice('SO', _('SO'), order=10)
    BS = IliChoice('BS', _('BS'), order=11)
    BL = IliChoice('BL', _('BL'), order=12)
    SH = IliChoice('SH', _('SH'), order=13)
    AR = IliChoice('AR', _('AR'), order=14)
    AI = IliChoice('AI', _('AI'), order=15)
    SG = IliChoice('SG', _('SG'), order=16)
    GR = IliChoice('GR', _('GR'), order=17)
    AG = IliChoice('AG', _('AG'), order=18)
    TG = IliChoice('TG', _('TG'), order=19)
    TI = IliChoice('TI', _('TI'), order=20)
    VD = IliChoice('VD', _('VD'), order=21)
    VS = IliChoice('VS', _('VS'), order=22)
    NE = IliChoice('NE', _('NE'), order=23)
    GE = IliChoice('GE', _('GE'), order=24)
    JU = IliChoice('JU', _('JU'), order=25)
    FL = IliChoice('FL', _('FL'), order=26)
    CH = IliChoice('CH', _('CH'), order=27)

@interlis_model(oid='AdministrativeUnitsCH_V2.CHCantons.CHCanton', qname='odmav_administrative_units_ch_v2.CHCanton')
class CHCanton(models.Model):
    code = ili_field(models.ForeignKey('odmav_administrative_units_ch_v2.CHCantonCodeEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='AdministrativeUnitsCH_V2.CHCantons.CHCanton.Code', qname='odmav_administrative_units_ch_v2.CHCanton.Code')
    name = ili_field(models.TextField(null=True, blank=True), oid='AdministrativeUnitsCH_V2.CHCantons.CHCanton.Name', qname='odmav_administrative_units_ch_v2.CHCanton.Name')
    web = ili_field(models.CharField(max_length=1023, null=True, blank=True), oid='AdministrativeUnitsCH_V2.CHCantons.CHCanton.Web', qname='odmav_administrative_units_ch_v2.CHCanton.Web')
    upper_level_unit = ili_field(models.ForeignKey('odmav_administrative_units_v2.Country', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='AdministrativeUnitsCH_V2.CHCantons.Hierarchy.UpperLevelUnit', qname='odmav_administrative_units_ch_v2.CHCanton.UpperLevelUnit')

    class Meta:
        db_table = 'odmav_administrative_units_ch_v2__chcanton'

@interlis_model(oid='AdministrativeUnitsCH_V2.CHCantons.Hierarchy', qname='odmav_administrative_units_ch_v2.Hierarchy')
class CHCantonsHierarchy(models.Model):
    pass

    class Meta:
        db_table = 'odmav_administrative_units_ch_v2__chcantons_hierarchy'

@interlis_model(oid='AdministrativeUnitsCH_V2.CHDistricts.CHDistrict', qname='odmav_administrative_units_ch_v2.CHDistrict')
class CHDistrict(models.Model):
    short_name = ili_field(models.CharField(max_length=20, null=False, blank=False), oid='AdministrativeUnitsCH_V2.CHDistricts.CHDistrict.ShortName', qname='odmav_administrative_units_ch_v2.CHDistrict.ShortName')
    name = ili_field(models.TextField(null=True, blank=True), oid='AdministrativeUnitsCH_V2.CHDistricts.CHDistrict.Name', qname='odmav_administrative_units_ch_v2.CHDistrict.Name')
    web = ili_field(models.CharField(max_length=1023, null=False, blank=False), oid='AdministrativeUnitsCH_V2.CHDistricts.CHDistrict.Web', qname='odmav_administrative_units_ch_v2.CHDistrict.Web')
    upper_level_unit = ili_field(models.ForeignKey('odmav_administrative_units_ch_v2.CHCanton', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='AdministrativeUnitsCH_V2.CHDistricts.Hierarchy.UpperLevelUnit', qname='odmav_administrative_units_ch_v2.CHDistrict.UpperLevelUnit')

    class Meta:
        db_table = 'odmav_administrative_units_ch_v2__chdistrict'

@interlis_model(oid='AdministrativeUnitsCH_V2.CHDistricts.Hierarchy', qname='odmav_administrative_units_ch_v2.Hierarchy')
class CHDistrictsHierarchy(models.Model):
    pass

    class Meta:
        db_table = 'odmav_administrative_units_ch_v2__chdistricts_hierarchy'

@interlis_model(oid='AdministrativeUnitsCH_V2.CHMunicipalities.CHMunicipality', qname='odmav_administrative_units_ch_v2.CHMunicipality')
class CHMunicipality(models.Model):
    code = ili_field(models.IntegerField(null=False, blank=False), oid='AdministrativeUnitsCH_V2.CHMunicipalities.CHMunicipality.Code', qname='odmav_administrative_units_ch_v2.CHMunicipality.Code')
    name = ili_field(models.TextField(null=True, blank=True), oid='AdministrativeUnitsCH_V2.CHMunicipalities.CHMunicipality.Name', qname='odmav_administrative_units_ch_v2.CHMunicipality.Name')
    web = ili_field(models.CharField(max_length=1023, null=True, blank=True), oid='AdministrativeUnitsCH_V2.CHMunicipalities.CHMunicipality.Web', qname='odmav_administrative_units_ch_v2.CHMunicipality.Web')
    upper_level_unit = ili_field(models.ForeignKey('odmav_administrative_units_ch_v2.CHDistrict', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='AdministrativeUnitsCH_V2.CHMunicipalities.Hierarchy.UpperLevelUnit', qname='odmav_administrative_units_ch_v2.CHMunicipality.UpperLevelUnit')

    class Meta:
        db_table = 'odmav_administrative_units_ch_v2__chmunicipality'

@interlis_model(oid='AdministrativeUnitsCH_V2.CHMunicipalities.Hierarchy', qname='odmav_administrative_units_ch_v2.Hierarchy')
class CHMunicipalitiesHierarchy(models.Model):
    upper_level_unit = ili_field(models.ForeignKey('odmav_administrative_units_ch_v2.CHCanton', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='AdministrativeUnitsCH_V2.CHMunicipalities.Hierarchy.UpperLevelUnit', qname='odmav_administrative_units_ch_v2.Hierarchy.UpperLevelUnit')
    lower_level_unit = ili_field(models.JSONField(default=list, null=True, blank=True), oid='AdministrativeUnitsCH_V2.CHMunicipalities.Hierarchy.LowerLevelUnit', qname='odmav_administrative_units_ch_v2.Hierarchy.LowerLevelUnit')

    class Meta:
        db_table = 'odmav_administrative_units_ch_v2__chmunicipalities_hierarchy'

@interlis_model(oid='AdministrativeUnitsCH_V2.CHAdministrativeUnions.AdministrativeUnion', qname='odmav_administrative_units_ch_v2.AdministrativeUnion')
class AdministrativeUnion(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.AdministrativeUnitsCH_V2.CHAdministrativeUnions.AdministrativeUnion.tid', qname='odmav_administrative_units_ch_v2.AdministrativeUnion.tid')
    name = ili_field(models.TextField(null=True, blank=True), oid='AdministrativeUnitsCH_V2.CHAdministrativeUnions.AdministrativeUnion.Name', qname='odmav_administrative_units_ch_v2.AdministrativeUnion.Name')
    web = ili_field(models.CharField(max_length=1023, null=True, blank=True), oid='AdministrativeUnitsCH_V2.CHAdministrativeUnions.AdministrativeUnion.Web', qname='odmav_administrative_units_ch_v2.AdministrativeUnion.Web')
    description = ili_field(models.TextField(null=True, blank=True), oid='AdministrativeUnitsCH_V2.CHAdministrativeUnions.AdministrativeUnion.Description', qname='odmav_administrative_units_ch_v2.AdministrativeUnion.Description')

    class Meta:
        db_table = 'odmav_administrative_units_ch_v2__administrative_union'

@interlis_model(oid='AdministrativeUnitsCH_V2.CHAgencies.Agency', qname='odmav_administrative_units_ch_v2.Agency')
class Agency(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.AdministrativeUnitsCH_V2.CHAgencies.Agency.tid', qname='odmav_administrative_units_ch_v2.Agency.tid')
    name = ili_field(models.TextField(null=True, blank=True), oid='AdministrativeUnitsCH_V2.CHAgencies.Agency.Name', qname='odmav_administrative_units_ch_v2.Agency.Name')
    web = ili_field(models.CharField(max_length=1023, null=True, blank=True), oid='AdministrativeUnitsCH_V2.CHAgencies.Agency.Web', qname='odmav_administrative_units_ch_v2.Agency.Web')
    description = ili_field(models.TextField(null=True, blank=True), oid='AdministrativeUnitsCH_V2.CHAgencies.Agency.Description', qname='odmav_administrative_units_ch_v2.Agency.Description')

    class Meta:
        db_table = 'odmav_administrative_units_ch_v2__agency'
