"""Generated by ili2django. Do not edit manually."""

from django.contrib.gis.db import models
from django.utils.translation import gettext_lazy as _

from ili2django.choices import IliChoice, IliChoices
from ili2django.decorators import ili_field, interlis_model

@interlis_model(oid='KGK_Grundstuecke_V1_0.Grundstuecke.SelbstaendigesDauerndesRecht.ArtSDR_ENUM', qname='odmav_kgk_grundstuecke_v1_0.SelbstaendigesDauerndesRechtArtSDREnum')
class SelbstaendigesDauerndesRechtArtSDREnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='KGK_Grundstuecke_V1_0.Grundstuecke.SelbstaendigesDauerndesRecht.ArtSDR_ENUM.code', qname='odmav_kgk_grundstuecke_v1_0.SelbstaendigesDauerndesRechtArtSDREnum.code')
    label = ili_field(models.CharField(max_length=255), oid='KGK_Grundstuecke_V1_0.Grundstuecke.SelbstaendigesDauerndesRecht.ArtSDR_ENUM.label', qname='odmav_kgk_grundstuecke_v1_0.SelbstaendigesDauerndesRechtArtSDREnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['Baurecht', 'Quellenrecht', 'Konzession', 'weitere']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_kgk_grundstuecke_v1_0__selbstaendiges_dauernde_629d67933b'

class SelbstaendigesDauerndesRechtArtSDREnumValueChoices(IliChoices):
    BAURECHT = IliChoice('Baurecht', _('Baurecht'), order=0)
    QUELLENRECHT = IliChoice('Quellenrecht', _('Quellenrecht'), order=1)
    KONZESSION = IliChoice('Konzession', _('Konzession'), order=2)
    WEITERE = IliChoice('weitere', _('weitere'), order=3)

@interlis_model(oid='KGK_Grundstuecke_V1_0.Grundstuecke.SelbstaendigesDauerndesRecht', qname='odmav_kgk_grundstuecke_v1_0.SelbstaendigesDauerndesRecht')
class SelbstaendigesDauerndesRecht(models.Model):
    art_sdr = ili_field(models.ForeignKey('odmav_kgk_grundstuecke_v1_0.SelbstaendigesDauerndesRechtArtSDREnumValue', on_delete=models.PROTECT, related_name='+', null=True, blank=True), oid='KGK_Grundstuecke_V1_0.Grundstuecke.SelbstaendigesDauerndesRecht.ArtSDR', qname='odmav_kgk_grundstuecke_v1_0.SelbstaendigesDauerndesRecht.ArtSDR')

    class Meta:
        db_table = 'odmav_kgk_grundstuecke_v1_0__selbstaendiges_dauerndes_recht'
