"""Generated by ili2django. Do not edit manually."""

from django.contrib.gis.db import models
from django.utils.translation import gettext_lazy as _

from ili2django.choices import IliChoice, IliChoices
from ili2django.decorators import ili_field, interlis_model

@interlis_model(oid='DictionariesCH_V2.Dictionaries.Dictionary', qname='odmav_dictionaries_ch_v2.Dictionary')
class Dictionary(models.Model):
    pass

    class Meta:
        db_table = 'odmav_dictionaries_ch_v2__dictionary'
