"""Generated by ili2django. Do not edit manually."""

from django.contrib.gis.db import models
from django.utils.translation import gettext_lazy as _

from ili2django.choices import IliChoice, IliChoices
from ili2django.decorators import ili_field, interlis_model

@interlis_model(oid='KGKCGC_FPDS2_V1_1.FPDS2.Zustaendigkeit.Kanton_ENUM', qname='odmav_kgkcgc_fpds2_v1_1.ZustaendigkeitKantonEnum')
class ZustaendigkeitKantonEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='KGKCGC_FPDS2_V1_1.FPDS2.Zustaendigkeit.Kanton_ENUM.code', qname='odmav_kgkcgc_fpds2_v1_1.ZustaendigkeitKantonEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='KGKCGC_FPDS2_V1_1.FPDS2.Zustaendigkeit.Kanton_ENUM.label', qname='odmav_kgkcgc_fpds2_v1_1.ZustaendigkeitKantonEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['ZH', 'BE', 'LU', 'UR', 'SZ', 'OW', 'NW', 'GL', 'ZG', 'FR', 'SO', 'BS', 'BL', 'SH', 'AR', 'AI', 'SG', 'GR', 'AG', 'TG', 'TI', 'VD', 'VS', 'NE', 'GE', 'JU', 'FL', 'CH']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_kgkcgc_fpds2_v1_1__zustaendigkeit_kanton_enum_value'

class ZustaendigkeitKantonEnumValueChoices(IliChoices):
    ZH = IliChoice('ZH', _('ZH'), order=0)
    BE = IliChoice('BE', _('BE'), order=1)
    LU = IliChoice('LU', _('LU'), order=2)
    UR = IliChoice('UR', _('UR'), order=3)
    SZ = IliChoice('SZ', _('SZ'), order=4)
    OW = IliChoice('OW', _('OW'), order=5)
    NW = IliChoice('NW', _('NW'), order=6)
    GL = IliChoice('GL', _('GL'), order=7)
    ZG = IliChoice('ZG', _('ZG'), order=8)
    FR = IliChoice('FR', _('FR'), order=9)
    SO = IliChoice('SO', _('SO'), order=10)
    BS = IliChoice('BS', _('BS'), order=11)
    BL = IliChoice('BL', _('BL'), order=12)
    SH = IliChoice('SH', _('SH'), order=13)
    AR = IliChoice('AR', _('AR'), order=14)
    AI = IliChoice('AI', _('AI'), order=15)
    SG = IliChoice('SG', _('SG'), order=16)
    GR = IliChoice('GR', _('GR'), order=17)
    AG = IliChoice('AG', _('AG'), order=18)
    TG = IliChoice('TG', _('TG'), order=19)
    TI = IliChoice('TI', _('TI'), order=20)
    VD = IliChoice('VD', _('VD'), order=21)
    VS = IliChoice('VS', _('VS'), order=22)
    NE = IliChoice('NE', _('NE'), order=23)
    GE = IliChoice('GE', _('GE'), order=24)
    JU = IliChoice('JU', _('JU'), order=25)
    FL = IliChoice('FL', _('FL'), order=26)
    CH = IliChoice('CH', _('CH'), order=27)

@interlis_model(oid='KGKCGC_FPDS2_V1_1.FPDS2.Fixpunkt.Art_ENUM', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktArtEnum')
class FixpunktArtEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='KGKCGC_FPDS2_V1_1.FPDS2.Fixpunkt.Art_ENUM.code', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktArtEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='KGKCGC_FPDS2_V1_1.FPDS2.Fixpunkt.Art_ENUM.label', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktArtEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['LFP2', 'HFP2']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_kgkcgc_fpds2_v1_1__fixpunkt_art_enum_value'

class FixpunktArtEnumValueChoices(IliChoices):
    LFP2 = IliChoice('LFP2', _('LFP2'), order=0)
    HFP2 = IliChoice('HFP2', _('HFP2'), order=1)

@interlis_model(oid='KGKCGC_FPDS2_V1_1.FPDS2.Fixpunkt.Begehbarkeit_ENUM', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktBegehbarkeitEnum')
class FixpunktBegehbarkeitEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='KGKCGC_FPDS2_V1_1.FPDS2.Fixpunkt.Begehbarkeit_ENUM.code', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktBegehbarkeitEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='KGKCGC_FPDS2_V1_1.FPDS2.Fixpunkt.Begehbarkeit_ENUM.label', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktBegehbarkeitEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['begehbar', 'nicht_begehbar']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_kgkcgc_fpds2_v1_1__fixpunkt_begehbarkeit_enum_value'

class FixpunktBegehbarkeitEnumValueChoices(IliChoices):
    BEGEHBAR = IliChoice('begehbar', _('begehbar'), order=0)
    NICHT_BEGEHBAR = IliChoice('nicht_begehbar', _('nicht_begehbar'), order=1)

@interlis_model(oid='KGKCGC_FPDS2_V1_1.FPDS2.Fixpunkt.GNSSSichtbarkeit_ENUM', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktGNSSSichtbarkeitEnum')
class FixpunktGNSSSichtbarkeitEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='KGKCGC_FPDS2_V1_1.FPDS2.Fixpunkt.GNSSSichtbarkeit_ENUM.code', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktGNSSSichtbarkeitEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='KGKCGC_FPDS2_V1_1.FPDS2.Fixpunkt.GNSSSichtbarkeit_ENUM.label', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktGNSSSichtbarkeitEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['gut', 'mittel', 'schlecht', 'keine_Angabe']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_kgkcgc_fpds2_v1_1__fixpunkt_gnsssichtbarkeit_enum_value'

class FixpunktGNSSSichtbarkeitEnumValueChoices(IliChoices):
    GUT = IliChoice('gut', _('gut'), order=0)
    MITTEL = IliChoice('mittel', _('mittel'), order=1)
    SCHLECHT = IliChoice('schlecht', _('schlecht'), order=2)
    KEINE_ANGABE = IliChoice('keine_Angabe', _('keine_Angabe'), order=3)

@interlis_model(oid='KGKCGC_FPDS2_V1_1.FPDS2.Fixpunkt.ProtokollSprache_ENUM', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktProtokollSpracheEnum')
class FixpunktProtokollSpracheEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='KGKCGC_FPDS2_V1_1.FPDS2.Fixpunkt.ProtokollSprache_ENUM.code', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktProtokollSpracheEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='KGKCGC_FPDS2_V1_1.FPDS2.Fixpunkt.ProtokollSprache_ENUM.label', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktProtokollSpracheEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['deutsch', 'franzoesisch', 'italienisch']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_kgkcgc_fpds2_v1_1__fixpunkt_protokoll_sprache_enum_value'

class FixpunktProtokollSpracheEnumValueChoices(IliChoices):
    DEUTSCH = IliChoice('deutsch', _('deutsch'), order=0)
    FRANZOESISCH = IliChoice('franzoesisch', _('franzoesisch'), order=1)
    ITALIENISCH = IliChoice('italienisch', _('italienisch'), order=2)

@interlis_model(oid='KGKCGC_FPDS2_V1_1.FPDS2.Fixpunkt.Unterhaltsstrategie_ENUM', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktUnterhaltsstrategieEnum')
class FixpunktUnterhaltsstrategieEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='KGKCGC_FPDS2_V1_1.FPDS2.Fixpunkt.Unterhaltsstrategie_ENUM.code', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktUnterhaltsstrategieEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='KGKCGC_FPDS2_V1_1.FPDS2.Fixpunkt.Unterhaltsstrategie_ENUM.label', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktUnterhaltsstrategieEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['aktiv', 'passiv']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_kgkcgc_fpds2_v1_1__fixpunkt_unterhaltsstrategi_f1b0285a89'

class FixpunktUnterhaltsstrategieEnumValueChoices(IliChoices):
    AKTIV = IliChoice('aktiv', _('aktiv'), order=0)
    PASSIV = IliChoice('passiv', _('passiv'), order=1)

@interlis_model(oid='KGKCGC_FPDS2_V1_1.FPDS2.FixpunktVersion.Koordinatenbestimmung_ENUM', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktVersionKoordinatenbestimmungEnum')
class FixpunktVersionKoordinatenbestimmungEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='KGKCGC_FPDS2_V1_1.FPDS2.FixpunktVersion.Koordinatenbestimmung_ENUM.code', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktVersionKoordinatenbestimmungEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='KGKCGC_FPDS2_V1_1.FPDS2.FixpunktVersion.Koordinatenbestimmung_ENUM.label', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktVersionKoordinatenbestimmungEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['transformiert', 'gemessen_LV95']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_kgkcgc_fpds2_v1_1__fixpunkt_version_koordinate_afcdab710d'

class FixpunktVersionKoordinatenbestimmungEnumValueChoices(IliChoices):
    TRANSFORMIERT = IliChoice('transformiert', _('transformiert'), order=0)
    GEMESSEN_LV95 = IliChoice('gemessen_LV95', _('gemessen_LV95'), order=1)

@interlis_model(oid='KGKCGC_FPDS2_V1_1.FPDS2.FixpunktVersion.LageZuv_ENUM', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktVersionLageZuvEnum')
class FixpunktVersionLageZuvEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='KGKCGC_FPDS2_V1_1.FPDS2.FixpunktVersion.LageZuv_ENUM.code', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktVersionLageZuvEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='KGKCGC_FPDS2_V1_1.FPDS2.FixpunktVersion.LageZuv_ENUM.label', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktVersionLageZuvEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['ja', 'nein']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_kgkcgc_fpds2_v1_1__fixpunkt_version_lage_zuv_enum_value'

class FixpunktVersionLageZuvEnumValueChoices(IliChoices):
    JA = IliChoice('ja', _('ja'), order=0)
    NEIN = IliChoice('nein', _('nein'), order=1)

@interlis_model(oid='KGKCGC_FPDS2_V1_1.FPDS2.FixpunktVersion.Punktzeichen_ENUM', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktVersionPunktzeichenEnum')
class FixpunktVersionPunktzeichenEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='KGKCGC_FPDS2_V1_1.FPDS2.FixpunktVersion.Punktzeichen_ENUM.code', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktVersionPunktzeichenEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='KGKCGC_FPDS2_V1_1.FPDS2.FixpunktVersion.Punktzeichen_ENUM.label', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktVersionPunktzeichenEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['Bolzen_horizontal', 'Bolzen', 'Bolzen_mit_Stiftloch', 'Bronzeplatte', 'Kappenbolzen', 'Landesnivellement', 'Mast_Antenne', 'Niete', 'Nivellementsbolzen', 'Pyramide', 'Stein', 'Turm', 'unterirdische_Versicherung', 'weitere']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_kgkcgc_fpds2_v1_1__fixpunkt_version_punktzeich_77e2a5c49d'

class FixpunktVersionPunktzeichenEnumValueChoices(IliChoices):
    BOLZEN_HORIZONTAL = IliChoice('Bolzen_horizontal', _('Bolzen_horizontal'), order=0)
    BOLZEN = IliChoice('Bolzen', _('Bolzen'), order=1)
    BOLZEN_MIT_STIFTLOCH = IliChoice('Bolzen_mit_Stiftloch', _('Bolzen_mit_Stiftloch'), order=2)
    BRONZEPLATTE = IliChoice('Bronzeplatte', _('Bronzeplatte'), order=3)
    KAPPENBOLZEN = IliChoice('Kappenbolzen', _('Kappenbolzen'), order=4)
    LANDESNIVELLEMENT = IliChoice('Landesnivellement', _('Landesnivellement'), order=5)
    MAST_ANTENNE = IliChoice('Mast_Antenne', _('Mast_Antenne'), order=6)
    NIETE = IliChoice('Niete', _('Niete'), order=7)
    NIVELLEMENTSBOLZEN = IliChoice('Nivellementsbolzen', _('Nivellementsbolzen'), order=8)
    PYRAMIDE = IliChoice('Pyramide', _('Pyramide'), order=9)
    STEIN = IliChoice('Stein', _('Stein'), order=10)
    TURM = IliChoice('Turm', _('Turm'), order=11)
    UNTERIRDISCHE_VERSICHERUNG = IliChoice('unterirdische_Versicherung', _('unterirdische_Versicherung'), order=12)
    WEITERE = IliChoice('weitere', _('weitere'), order=13)

@interlis_model(oid='KGKCGC_FPDS2_V1_1.FPDS2.FixpunktVersion.Schutzart_ENUM', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktVersionSchutzartEnum')
class FixpunktVersionSchutzartEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='KGKCGC_FPDS2_V1_1.FPDS2.FixpunktVersion.Schutzart_ENUM.code', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktVersionSchutzartEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='KGKCGC_FPDS2_V1_1.FPDS2.FixpunktVersion.Schutzart_ENUM.label', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktVersionSchutzartEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['kein_Schutz', 'Schacht', 'ueberdeckt']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_kgkcgc_fpds2_v1_1__fixpunkt_version_schutzart_enum_value'

class FixpunktVersionSchutzartEnumValueChoices(IliChoices):
    KEIN_SCHUTZ = IliChoice('kein_Schutz', _('kein_Schutz'), order=0)
    SCHACHT = IliChoice('Schacht', _('Schacht'), order=1)
    UEBERDECKT = IliChoice('ueberdeckt', _('ueberdeckt'), order=2)

@interlis_model(oid='KGKCGC_FPDS2_V1_1.FPDS2.FixpunkteNachfuehrung.Status_ENUM', qname='odmav_kgkcgc_fpds2_v1_1.FixpunkteNachfuehrungStatusEnum')
class FixpunkteNachfuehrungStatusEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='KGKCGC_FPDS2_V1_1.FPDS2.FixpunkteNachfuehrung.Status_ENUM.code', qname='odmav_kgkcgc_fpds2_v1_1.FixpunkteNachfuehrungStatusEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='KGKCGC_FPDS2_V1_1.FPDS2.FixpunkteNachfuehrung.Status_ENUM.label', qname='odmav_kgkcgc_fpds2_v1_1.FixpunkteNachfuehrungStatusEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['in_Bearbeitung', 'abgeschlossen']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_kgkcgc_fpds2_v1_1__fixpunkte_nachfuehrung_stat_cca450912f'

class FixpunkteNachfuehrungStatusEnumValueChoices(IliChoices):
    IN_BEARBEITUNG = IliChoice('in_Bearbeitung', _('in_Bearbeitung'), order=0)
    ABGESCHLOSSEN = IliChoice('abgeschlossen', _('abgeschlossen'), order=1)

@interlis_model(oid='KGKCGC_FPDS2_V1_1.FPDS2.UebersichtGeodienst', qname='odmav_kgkcgc_fpds2_v1_1.UebersichtGeodienst')
class UebersichtGeodienst(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.KGKCGC_FPDS2_V1_1.FPDS2.UebersichtGeodienst.tid', qname='odmav_kgkcgc_fpds2_v1_1.UebersichtGeodienst.tid')
    bezeichnung = ili_field(models.CharField(max_length=30, null=False, blank=False), oid='KGKCGC_FPDS2_V1_1.FPDS2.UebersichtGeodienst.Bezeichnung', qname='odmav_kgkcgc_fpds2_v1_1.UebersichtGeodienst.Bezeichnung')
    url = ili_field(models.CharField(max_length=1023, null=False, blank=False), oid='KGKCGC_FPDS2_V1_1.FPDS2.UebersichtGeodienst.URL', qname='odmav_kgkcgc_fpds2_v1_1.UebersichtGeodienst.URL')

    class Meta:
        db_table = 'odmav_kgkcgc_fpds2_v1_1__uebersicht_geodienst'

@interlis_model(oid='KGKCGC_FPDS2_V1_1.FPDS2.UebersichtMassstab', qname='odmav_kgkcgc_fpds2_v1_1.UebersichtMassstab')
class UebersichtMassstab(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.KGKCGC_FPDS2_V1_1.FPDS2.UebersichtMassstab.tid', qname='odmav_kgkcgc_fpds2_v1_1.UebersichtMassstab.tid')
    massstabszahl = ili_field(models.FloatField(null=False, blank=False), oid='KGKCGC_FPDS2_V1_1.FPDS2.UebersichtMassstab.Massstabszahl', qname='odmav_kgkcgc_fpds2_v1_1.UebersichtMassstab.Massstabszahl')

    class Meta:
        db_table = 'odmav_kgkcgc_fpds2_v1_1__uebersicht_massstab'

@interlis_model(oid='KGKCGC_FPDS2_V1_1.FPDS2.Zustaendigkeit', qname='odmav_kgkcgc_fpds2_v1_1.Zustaendigkeit')
class Zustaendigkeit(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.KGKCGC_FPDS2_V1_1.FPDS2.Zustaendigkeit.tid', qname='odmav_kgkcgc_fpds2_v1_1.Zustaendigkeit.tid')
    kanton = ili_field(models.ForeignKey('odmav_kgkcgc_fpds2_v1_1.ZustaendigkeitKantonEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='KGKCGC_FPDS2_V1_1.FPDS2.Zustaendigkeit.Kanton', qname='odmav_kgkcgc_fpds2_v1_1.Zustaendigkeit.Kanton')
    name = ili_field(models.CharField(max_length=100, null=False, blank=False), oid='KGKCGC_FPDS2_V1_1.FPDS2.Zustaendigkeit.Name', qname='odmav_kgkcgc_fpds2_v1_1.Zustaendigkeit.Name')
    adresse = ili_field(models.CharField(max_length=50, null=True, blank=True), oid='KGKCGC_FPDS2_V1_1.FPDS2.Zustaendigkeit.Adresse', qname='odmav_kgkcgc_fpds2_v1_1.Zustaendigkeit.Adresse')

    class Meta:
        db_table = 'odmav_kgkcgc_fpds2_v1_1__zustaendigkeit'

@interlis_model(oid='KGKCGC_FPDS2_V1_1.FPDS2.Fixpunkt', qname='odmav_kgkcgc_fpds2_v1_1.Fixpunkt')
class Fixpunkt(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.KGKCGC_FPDS2_V1_1.FPDS2.Fixpunkt.tid', qname='odmav_kgkcgc_fpds2_v1_1.Fixpunkt.tid')
    art = ili_field(models.ForeignKey('odmav_kgkcgc_fpds2_v1_1.FixpunktArtEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='KGKCGC_FPDS2_V1_1.FPDS2.Fixpunkt.Art', qname='odmav_kgkcgc_fpds2_v1_1.Fixpunkt.Art')
    begehbarkeit = ili_field(models.ForeignKey('odmav_kgkcgc_fpds2_v1_1.FixpunktBegehbarkeitEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='KGKCGC_FPDS2_V1_1.FPDS2.Fixpunkt.Begehbarkeit', qname='odmav_kgkcgc_fpds2_v1_1.Fixpunkt.Begehbarkeit')
    bemerkung = ili_field(models.CharField(max_length=400, null=True, blank=True), oid='KGKCGC_FPDS2_V1_1.FPDS2.Fixpunkt.Bemerkung', qname='odmav_kgkcgc_fpds2_v1_1.Fixpunkt.Bemerkung')
    bildquelle1 = ili_field(models.CharField(max_length=1023, null=True, blank=True), oid='KGKCGC_FPDS2_V1_1.FPDS2.Fixpunkt.Bildquelle1', qname='odmav_kgkcgc_fpds2_v1_1.Fixpunkt.Bildquelle1')
    bildquelle2 = ili_field(models.CharField(max_length=1023, null=True, blank=True), oid='KGKCGC_FPDS2_V1_1.FPDS2.Fixpunkt.Bildquelle2', qname='odmav_kgkcgc_fpds2_v1_1.Fixpunkt.Bildquelle2')
    gnsssichtbarkeit = ili_field(models.ForeignKey('odmav_kgkcgc_fpds2_v1_1.FixpunktGNSSSichtbarkeitEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='KGKCGC_FPDS2_V1_1.FPDS2.Fixpunkt.GNSSSichtbarkeit', qname='odmav_kgkcgc_fpds2_v1_1.Fixpunkt.GNSSSichtbarkeit')
    inschrift = ili_field(models.CharField(max_length=8, null=True, blank=True), oid='KGKCGC_FPDS2_V1_1.FPDS2.Fixpunkt.Inschrift', qname='odmav_kgkcgc_fpds2_v1_1.Fixpunkt.Inschrift')
    nbident = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='KGKCGC_FPDS2_V1_1.FPDS2.Fixpunkt.NBIdent', qname='odmav_kgkcgc_fpds2_v1_1.Fixpunkt.NBIdent')
    nummer = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='KGKCGC_FPDS2_V1_1.FPDS2.Fixpunkt.Nummer', qname='odmav_kgkcgc_fpds2_v1_1.Fixpunkt.Nummer')
    protokoll_sprache = ili_field(models.ForeignKey('odmav_kgkcgc_fpds2_v1_1.FixpunktProtokollSpracheEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='KGKCGC_FPDS2_V1_1.FPDS2.Fixpunkt.ProtokollSprache', qname='odmav_kgkcgc_fpds2_v1_1.Fixpunkt.ProtokollSprache')
    symbol_ori = ili_field(models.FloatField(null=True, blank=True), oid='KGKCGC_FPDS2_V1_1.FPDS2.Fixpunkt.SymbolOri', qname='odmav_kgkcgc_fpds2_v1_1.Fixpunkt.SymbolOri')
    tsp = ili_field(models.BooleanField(default=False), oid='KGKCGC_FPDS2_V1_1.FPDS2.Fixpunkt.TSP', qname='odmav_kgkcgc_fpds2_v1_1.Fixpunkt.TSP')
    unterhaltsstrategie = ili_field(models.ForeignKey('odmav_kgkcgc_fpds2_v1_1.FixpunktUnterhaltsstrategieEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='KGKCGC_FPDS2_V1_1.FPDS2.Fixpunkt.Unterhaltsstrategie', qname='odmav_kgkcgc_fpds2_v1_1.Fixpunkt.Unterhaltsstrategie')
    ug = ili_field(models.ForeignKey('odmav_kgkcgc_fpds2_v1_1.UebersichtGeodienst', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='KGKCGC_FPDS2_V1_1.FPDS2.FP_UebersichtGeodienst.UG', qname='odmav_kgkcgc_fpds2_v1_1.Fixpunkt.UG')
    um = ili_field(models.ForeignKey('odmav_kgkcgc_fpds2_v1_1.UebersichtMassstab', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='KGKCGC_FPDS2_V1_1.FPDS2.FP_UebersichtMassstab.UM', qname='odmav_kgkcgc_fpds2_v1_1.Fixpunkt.UM')
    zs = ili_field(models.ForeignKey('odmav_kgkcgc_fpds2_v1_1.Zustaendigkeit', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='KGKCGC_FPDS2_V1_1.FPDS2.FP_Zustaendigkeit.ZS', qname='odmav_kgkcgc_fpds2_v1_1.Fixpunkt.ZS')

    class Meta:
        db_table = 'odmav_kgkcgc_fpds2_v1_1__fixpunkt'

@interlis_model(oid='KGKCGC_FPDS2_V1_1.FPDS2.FixpunktVersion', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktVersion')
class FixpunktVersion(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.KGKCGC_FPDS2_V1_1.FPDS2.FixpunktVersion.tid', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktVersion.tid')
    geometrie = ili_field(models.PointField(srid=2056, null=True, blank=True), oid='KGKCGC_FPDS2_V1_1.FPDS2.FixpunktVersion.Geometrie', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktVersion.Geometrie')
    untergegangen_am = ili_field(models.CharField(max_length=255, null=True, blank=True), oid='KGKCGC_FPDS2_V1_1.FPDS2.FixpunktVersion.UntergegangenAm', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktVersion.UntergegangenAm')
    hoehe_gen = ili_field(models.FloatField(null=True, blank=True), oid='KGKCGC_FPDS2_V1_1.FPDS2.FixpunktVersion.HoeheGen', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktVersion.HoeheGen')
    hoehe_geom = ili_field(models.FloatField(null=True, blank=True), oid='KGKCGC_FPDS2_V1_1.FPDS2.FixpunktVersion.HoeheGeom', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktVersion.HoeheGeom')
    hoehe_zuv = ili_field(models.TextField(null=True, blank=True), oid='KGKCGC_FPDS2_V1_1.FPDS2.FixpunktVersion.HoeheZuv', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktVersion.HoeheZuv')
    koordinatenbestimmung = ili_field(models.ForeignKey('odmav_kgkcgc_fpds2_v1_1.FixpunktVersionKoordinatenbestimmungEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='KGKCGC_FPDS2_V1_1.FPDS2.FixpunktVersion.Koordinatenbestimmung', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktVersion.Koordinatenbestimmung')
    lage_gen = ili_field(models.FloatField(null=False, blank=False), oid='KGKCGC_FPDS2_V1_1.FPDS2.FixpunktVersion.LageGen', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktVersion.LageGen')
    lage_zuv = ili_field(models.ForeignKey('odmav_kgkcgc_fpds2_v1_1.FixpunktVersionLageZuvEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='KGKCGC_FPDS2_V1_1.FPDS2.FixpunktVersion.LageZuv', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktVersion.LageZuv')
    punktzeichen = ili_field(models.ForeignKey('odmav_kgkcgc_fpds2_v1_1.FixpunktVersionPunktzeichenEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='KGKCGC_FPDS2_V1_1.FPDS2.FixpunktVersion.Punktzeichen', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktVersion.Punktzeichen')
    punktzeichenbeschreibung = ili_field(models.CharField(max_length=250, null=True, blank=True), oid='KGKCGC_FPDS2_V1_1.FPDS2.FixpunktVersion.Punktzeichenbeschreibung', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktVersion.Punktzeichenbeschreibung')
    schutzart = ili_field(models.ForeignKey('odmav_kgkcgc_fpds2_v1_1.FixpunktVersionSchutzartEnumValue', on_delete=models.PROTECT, related_name='+', null=True, blank=True), oid='KGKCGC_FPDS2_V1_1.FPDS2.FixpunktVersion.Schutzart', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktVersion.Schutzart')
    steinsatz = ili_field(models.CharField(max_length=50, null=True, blank=True), oid='KGKCGC_FPDS2_V1_1.FPDS2.FixpunktVersion.Steinsatz', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktVersion.Steinsatz')
    sekundaere_versicherung = ili_field(models.CharField(max_length=100, null=True, blank=True), oid='KGKCGC_FPDS2_V1_1.FPDS2.FixpunktVersion.SekundaereVersicherung', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktVersion.SekundaereVersicherung')
    fpn = ili_field(models.ForeignKey('odmav_kgkcgc_fpds2_v1_1.FixpunkteNachfuehrung', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='KGKCGC_FPDS2_V1_1.FPDS2.FPVersion_FPNachfuehrung.FPN', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktVersion.FPN')
    fp = ili_field(models.ForeignKey('odmav_kgkcgc_fpds2_v1_1.Fixpunkt', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='KGKCGC_FPDS2_V1_1.FPDS2.FP_FPVersion.FP', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktVersion.FP')

    class Meta:
        db_table = 'odmav_kgkcgc_fpds2_v1_1__fixpunkt_version'

@interlis_model(oid='KGKCGC_FPDS2_V1_1.FPDS2.FixpunktAktion', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktAktion')
class FixpunktAktion(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.KGKCGC_FPDS2_V1_1.FPDS2.FixpunktAktion.tid', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktAktion.tid')
    beschreibung = ili_field(models.CharField(max_length=60, null=False, blank=False), oid='KGKCGC_FPDS2_V1_1.FPDS2.FixpunktAktion.Beschreibung', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktAktion.Beschreibung')
    datum = ili_field(models.CharField(max_length=255, null=False, blank=False), oid='KGKCGC_FPDS2_V1_1.FPDS2.FixpunktAktion.Datum', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktAktion.Datum')
    fp = ili_field(models.ForeignKey('odmav_kgkcgc_fpds2_v1_1.Fixpunkt', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='KGKCGC_FPDS2_V1_1.FPDS2.FP_FPAktion.FP', qname='odmav_kgkcgc_fpds2_v1_1.FixpunktAktion.FP')

    class Meta:
        db_table = 'odmav_kgkcgc_fpds2_v1_1__fixpunkt_aktion'

@interlis_model(oid='KGKCGC_FPDS2_V1_1.FPDS2.FixpunkteNachfuehrung', qname='odmav_kgkcgc_fpds2_v1_1.FixpunkteNachfuehrung')
class FixpunkteNachfuehrung(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.KGKCGC_FPDS2_V1_1.FPDS2.FixpunkteNachfuehrung.tid', qname='odmav_kgkcgc_fpds2_v1_1.FixpunkteNachfuehrung.tid')
    bemerkung = ili_field(models.CharField(max_length=300, null=True, blank=True), oid='KGKCGC_FPDS2_V1_1.FPDS2.FixpunkteNachfuehrung.Bemerkung', qname='odmav_kgkcgc_fpds2_v1_1.FixpunkteNachfuehrung.Bemerkung')
    beschreibung = ili_field(models.CharField(max_length=30, null=False, blank=False), oid='KGKCGC_FPDS2_V1_1.FPDS2.FixpunkteNachfuehrung.Beschreibung', qname='odmav_kgkcgc_fpds2_v1_1.FixpunkteNachfuehrung.Beschreibung')
    gueltiger_eintrag = ili_field(models.CharField(max_length=255, null=True, blank=True), oid='KGKCGC_FPDS2_V1_1.FPDS2.FixpunkteNachfuehrung.GueltigerEintrag', qname='odmav_kgkcgc_fpds2_v1_1.FixpunkteNachfuehrung.GueltigerEintrag')
    datum_eroeffnung = ili_field(models.CharField(max_length=255, null=False, blank=False), oid='KGKCGC_FPDS2_V1_1.FPDS2.FixpunkteNachfuehrung.DatumEroeffnung', qname='odmav_kgkcgc_fpds2_v1_1.FixpunkteNachfuehrung.DatumEroeffnung')
    identifikator = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='KGKCGC_FPDS2_V1_1.FPDS2.FixpunkteNachfuehrung.Identifikator', qname='odmav_kgkcgc_fpds2_v1_1.FixpunkteNachfuehrung.Identifikator')
    nbident = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='KGKCGC_FPDS2_V1_1.FPDS2.FixpunkteNachfuehrung.NBIdent', qname='odmav_kgkcgc_fpds2_v1_1.FixpunkteNachfuehrung.NBIdent')
    status = ili_field(models.ForeignKey('odmav_kgkcgc_fpds2_v1_1.FixpunkteNachfuehrungStatusEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='KGKCGC_FPDS2_V1_1.FPDS2.FixpunkteNachfuehrung.Status', qname='odmav_kgkcgc_fpds2_v1_1.FixpunkteNachfuehrung.Status')

    class Meta:
        db_table = 'odmav_kgkcgc_fpds2_v1_1__fixpunkte_nachfuehrung'
