"""Generated by ili2django. Do not edit manually."""

from django.contrib.gis.db import models

from ili2django.decorators import ili_field, interlis_model

@interlis_model(oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Bodenbedeckungsart', qname='odmav_dmav_bodenbedeckung_v1_1.Bodenbedeckungsart')
class BodenbedeckungsartValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Bodenbedeckungsart.code', qname='odmav_dmav_bodenbedeckung_v1_1.Bodenbedeckungsart.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Bodenbedeckungsart.label', qname='odmav_dmav_bodenbedeckung_v1_1.Bodenbedeckungsart.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['Gebaeude', 'befestigt.Strasse_Weg', 'befestigt.Trottoir', 'befestigt.Verkehrsinsel', 'befestigt.Bahn', 'befestigt.Flugplatz', 'befestigt.Wasserbecken', 'befestigt.uebrige_befestigte', 'humusiert.Acker_Wiese_Weide', 'humusiert.Intensivkultur.Reben', 'humusiert.Intensivkultur.uebrige_Intensivkultur', 'humusiert.Gartenanlage', 'humusiert.Hoch_Flachmoor', 'humusiert.uebrige_humusierte', 'Gewaesser.stehendes_Gewaesser', 'Gewaesser.fliessendes_Gewaesser', 'Gewaesser.Schilfguertel', 'bestockt.geschlossener_Wald', 'bestockt.Wytweide.Wytweide_dicht', 'bestockt.Wytweide.Wytweide_offen', 'bestockt.uebrige_bestockte', 'vegetationslos.Fels', 'vegetationslos.Gletscher_Firn', 'vegetationslos.Geroell_Sand', 'vegetationslos.Abbau_Deponie', 'vegetationslos.uebrige_vegetationslose']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_bodenbedeckung_v1_1__bodenbedeckungsart_value'

@interlis_model(oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Bodenbedeckung.Qualitaetsstandard_ENUM', qname='odmav_dmav_bodenbedeckung_v1_1.BodenbedeckungQualitaetsstandardEnum')
class BodenbedeckungQualitaetsstandardEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Bodenbedeckung.Qualitaetsstandard_ENUM.code', qname='odmav_dmav_bodenbedeckung_v1_1.BodenbedeckungQualitaetsstandardEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Bodenbedeckung.Qualitaetsstandard_ENUM.label', qname='odmav_dmav_bodenbedeckung_v1_1.BodenbedeckungQualitaetsstandardEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['AV93', 'PN']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_bodenbedeckung_v1_1__bodenbedeckung_quali_16d2e446d7'

@interlis_model(oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Bodenbedeckung.Objektstatus_ENUM', qname='odmav_dmav_bodenbedeckung_v1_1.BodenbedeckungObjektstatusEnum')
class BodenbedeckungObjektstatusEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Bodenbedeckung.Objektstatus_ENUM.code', qname='odmav_dmav_bodenbedeckung_v1_1.BodenbedeckungObjektstatusEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Bodenbedeckung.Objektstatus_ENUM.label', qname='odmav_dmav_bodenbedeckung_v1_1.BodenbedeckungObjektstatusEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['projektiert', 'real', 'vergangen']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_bodenbedeckung_v1_1__bodenbedeckung_objek_6187e58196'

@interlis_model(oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.BBNachfuehrung', qname='odmav_dmav_bodenbedeckung_v1_1.BBNachfuehrung')
class BBNachfuehrung(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.BBNachfuehrung.tid', qname='odmav_dmav_bodenbedeckung_v1_1.BBNachfuehrung.tid')
    nbident = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.BBNachfuehrung.NBIdent', qname='odmav_dmav_bodenbedeckung_v1_1.BBNachfuehrung.NBIdent')
    identifikator = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.BBNachfuehrung.Identifikator', qname='odmav_dmav_bodenbedeckung_v1_1.BBNachfuehrung.Identifikator')
    beschreibung = ili_field(models.CharField(max_length=60, null=False, blank=False), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.BBNachfuehrung.Beschreibung', qname='odmav_dmav_bodenbedeckung_v1_1.BBNachfuehrung.Beschreibung')
    perimeter = ili_field(models.CurvePolygonField(srid=2056, null=True, blank=True), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.BBNachfuehrung.Perimeter', qname='odmav_dmav_bodenbedeckung_v1_1.BBNachfuehrung.Perimeter')
    gueltiger_eintrag = ili_field(models.CharField(max_length=255, null=False, blank=False), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.BBNachfuehrung.GueltigerEintrag', qname='odmav_dmav_bodenbedeckung_v1_1.BBNachfuehrung.GueltigerEintrag')

    class Meta:
        db_table = 'odmav_dmav_bodenbedeckung_v1_1__bbnachfuehrung'

@interlis_model(oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Objektnummer', qname='odmav_dmav_bodenbedeckung_v1_1.Objektnummer')
class Objektnummer(models.Model):
    nummer = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Objektnummer.Nummer', qname='odmav_dmav_bodenbedeckung_v1_1.Objektnummer.Nummer')
    textposition = ili_field(models.MultiLineStringField(srid=2056, null=True, blank=True), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Objektnummer.Textposition', qname='odmav_dmav_bodenbedeckung_v1_1.Objektnummer.Textposition')

    class Meta:
        db_table = 'odmav_dmav_bodenbedeckung_v1_1__objektnummer'

@interlis_model(oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Objektname', qname='odmav_dmav_bodenbedeckung_v1_1.Objektname')
class Objektname(models.Model):
    name = ili_field(models.CharField(max_length=60, null=False, blank=False), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Objektname.Name', qname='odmav_dmav_bodenbedeckung_v1_1.Objektname.Name')
    textposition = ili_field(models.MultiLineStringField(srid=2056, null=True, blank=True), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Objektname.Textposition', qname='odmav_dmav_bodenbedeckung_v1_1.Objektname.Textposition')

    class Meta:
        db_table = 'odmav_dmav_bodenbedeckung_v1_1__objektname'

@interlis_model(oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Bodenbedeckung', qname='odmav_dmav_bodenbedeckung_v1_1.Bodenbedeckung')
class Bodenbedeckung(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Bodenbedeckung.tid', qname='odmav_dmav_bodenbedeckung_v1_1.Bodenbedeckung.tid')
    geometrie = ili_field(models.CurvePolygonField(srid=2056, null=False, blank=False), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Bodenbedeckung.Geometrie', qname='odmav_dmav_bodenbedeckung_v1_1.Bodenbedeckung.Geometrie')
    qualitaetsstandard = ili_field(models.ForeignKey('odmav_dmav_bodenbedeckung_v1_1.BodenbedeckungQualitaetsstandardEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Bodenbedeckung.Qualitaetsstandard', qname='odmav_dmav_bodenbedeckung_v1_1.Bodenbedeckung.Qualitaetsstandard')
    bodenbedeckungsart = ili_field(models.ForeignKey('odmav_dmav_bodenbedeckung_v1_1.BodenbedeckungsartValue', on_delete=models.PROTECT, related_name='+', null=True, blank=True), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Bodenbedeckung.Bodenbedeckungsart', qname='odmav_dmav_bodenbedeckung_v1_1.Bodenbedeckung.Bodenbedeckungsart')
    fiktiv = ili_field(models.BooleanField(default=False), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Bodenbedeckung.Fiktiv', qname='odmav_dmav_bodenbedeckung_v1_1.Bodenbedeckung.Fiktiv')
    objektstatus = ili_field(models.ForeignKey('odmav_dmav_bodenbedeckung_v1_1.BodenbedeckungObjektstatusEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Bodenbedeckung.Objektstatus', qname='odmav_dmav_bodenbedeckung_v1_1.Bodenbedeckung.Objektstatus')
    objektnummer = ili_field(models.MultiLineStringField(srid=2056, null=True, blank=True), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Bodenbedeckung.Objektnummer', qname='odmav_dmav_bodenbedeckung_v1_1.Bodenbedeckung.Objektnummer')
    objektname = ili_field(models.MultiLineStringField(srid=2056, null=True, blank=True), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Bodenbedeckung.Objektname', qname='odmav_dmav_bodenbedeckung_v1_1.Bodenbedeckung.Objektname')
    egid = ili_field(models.IntegerField(null=True, blank=True), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Bodenbedeckung.EGID', qname='odmav_dmav_bodenbedeckung_v1_1.Bodenbedeckung.EGID')
    symbolposition = ili_field(models.MultiPointField(srid=2056, null=True, blank=True), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Bodenbedeckung.Symbolposition', qname='odmav_dmav_bodenbedeckung_v1_1.Bodenbedeckung.Symbolposition')
    entstehung = ili_field(models.ForeignKey('odmav_dmav_bodenbedeckung_v1_1.BBNachfuehrung', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Entstehung_Bodenbedeckung.Entstehung', qname='odmav_dmav_bodenbedeckung_v1_1.Bodenbedeckung.Entstehung')

    class Meta:
        db_table = 'odmav_dmav_bodenbedeckung_v1_1__bodenbedeckung'

@interlis_model(oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Messpunkt', qname='odmav_dmav_bodenbedeckung_v1_1.Messpunkt')
class Messpunkt(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Messpunkt.tid', qname='odmav_dmav_bodenbedeckung_v1_1.Messpunkt.tid')
    nummer = ili_field(models.CharField(max_length=12, null=True, blank=True), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Messpunkt.Nummer', qname='odmav_dmav_bodenbedeckung_v1_1.Messpunkt.Nummer')
    geometrie = ili_field(models.PointField(srid=2056, null=False, blank=False), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Messpunkt.Geometrie', qname='odmav_dmav_bodenbedeckung_v1_1.Messpunkt.Geometrie')
    hoehengeometrie = ili_field(models.FloatField(null=True, blank=True), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Messpunkt.Hoehengeometrie', qname='odmav_dmav_bodenbedeckung_v1_1.Messpunkt.Hoehengeometrie')
    lagegenauigkeit = ili_field(models.FloatField(null=False, blank=False), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Messpunkt.Lagegenauigkeit', qname='odmav_dmav_bodenbedeckung_v1_1.Messpunkt.Lagegenauigkeit')
    ist_lagezuverlaessig = ili_field(models.BooleanField(default=False), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Messpunkt.IstLagezuverlaessig', qname='odmav_dmav_bodenbedeckung_v1_1.Messpunkt.IstLagezuverlaessig')
    hoehengenauigkeit = ili_field(models.FloatField(null=True, blank=True), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Messpunkt.Hoehengenauigkeit', qname='odmav_dmav_bodenbedeckung_v1_1.Messpunkt.Hoehengenauigkeit')
    ist_hoehenzuverlaessig = ili_field(models.BooleanField(null=True, blank=True, default=None), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Messpunkt.IstHoehenzuverlaessig', qname='odmav_dmav_bodenbedeckung_v1_1.Messpunkt.IstHoehenzuverlaessig')
    ist_exakt_definiert = ili_field(models.BooleanField(default=False), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Messpunkt.IstExaktDefiniert', qname='odmav_dmav_bodenbedeckung_v1_1.Messpunkt.IstExaktDefiniert')
    entstehung = ili_field(models.ForeignKey('odmav_dmav_bodenbedeckung_v1_1.BBNachfuehrung', on_delete=models.PROTECT, related_name='+', null=True, blank=True), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Entstehung_Messpunkt.Entstehung', qname='odmav_dmav_bodenbedeckung_v1_1.Messpunkt.Entstehung')

    class Meta:
        db_table = 'odmav_dmav_bodenbedeckung_v1_1__messpunkt'
