"""Generated by ili2django. Do not edit manually."""

from django.contrib.gis.db import models
from django.utils.translation import gettext_lazy as _

from ili2django.choices import IliChoice, IliChoices
from ili2django.decorators import ili_field, interlis_model

@interlis_model(oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Bodenbedeckungsart', qname='odmav_dmav_bodenbedeckung_v1_1.Bodenbedeckungsart')
class BodenbedeckungsartValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Bodenbedeckungsart.code', qname='odmav_dmav_bodenbedeckung_v1_1.Bodenbedeckungsart.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Bodenbedeckungsart.label', qname='odmav_dmav_bodenbedeckung_v1_1.Bodenbedeckungsart.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['Gebaeude', 'befestigt.Strasse_Weg', 'befestigt.Trottoir', 'befestigt.Verkehrsinsel', 'befestigt.Bahn', 'befestigt.Flugplatz', 'befestigt.Wasserbecken', 'befestigt.uebrige_befestigte', 'humusiert.Acker_Wiese_Weide', 'humusiert.Intensivkultur.Reben', 'humusiert.Intensivkultur.uebrige_Intensivkultur', 'humusiert.Gartenanlage', 'humusiert.Hoch_Flachmoor', 'humusiert.uebrige_humusierte', 'Gewaesser.stehendes_Gewaesser', 'Gewaesser.fliessendes_Gewaesser', 'Gewaesser.Schilfguertel', 'bestockt.geschlossener_Wald', 'bestockt.Wytweide.Wytweide_dicht', 'bestockt.Wytweide.Wytweide_offen', 'bestockt.uebrige_bestockte', 'vegetationslos.Fels', 'vegetationslos.Gletscher_Firn', 'vegetationslos.Geroell_Sand', 'vegetationslos.Abbau_Deponie', 'vegetationslos.uebrige_vegetationslose']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_bodenbedeckung_v1_1__bodenbedeckungsart_value'

class BodenbedeckungsartValueChoices(IliChoices):
    GEBAEUDE = IliChoice('Gebaeude', _('Gebaeude'), order=0)
    BEFESTIGT_STRASSE_WEG = IliChoice('befestigt.Strasse_Weg', _('Strasse_Weg'), order=1)
    BEFESTIGT_TROTTOIR = IliChoice('befestigt.Trottoir', _('Trottoir'), order=2)
    BEFESTIGT_VERKEHRSINSEL = IliChoice('befestigt.Verkehrsinsel', _('Verkehrsinsel'), order=3)
    BEFESTIGT_BAHN = IliChoice('befestigt.Bahn', _('Bahn'), order=4)
    BEFESTIGT_FLUGPLATZ = IliChoice('befestigt.Flugplatz', _('Flugplatz'), order=5)
    BEFESTIGT_WASSERBECKEN = IliChoice('befestigt.Wasserbecken', _('Wasserbecken'), order=6)
    BEFESTIGT_UEBRIGE_BEFESTIGTE = IliChoice('befestigt.uebrige_befestigte', _('uebrige_befestigte'), order=7)
    HUMUSIERT_ACKER_WIESE_WEIDE = IliChoice('humusiert.Acker_Wiese_Weide', _('Acker_Wiese_Weide'), order=8)
    HUMUSIERT_INTENSIVKULTUR_REBEN = IliChoice('humusiert.Intensivkultur.Reben', _('Reben'), order=9)
    HUMUSIERT_INTENSIVKULTUR_UEBRIGE_INTENSIVKULTUR = IliChoice('humusiert.Intensivkultur.uebrige_Intensivkultur', _('uebrige_Intensivkultur'), order=10)
    HUMUSIERT_GARTENANLAGE = IliChoice('humusiert.Gartenanlage', _('Gartenanlage'), order=11)
    HUMUSIERT_HOCH_FLACHMOOR = IliChoice('humusiert.Hoch_Flachmoor', _('Hoch_Flachmoor'), order=12)
    HUMUSIERT_UEBRIGE_HUMUSIERTE = IliChoice('humusiert.uebrige_humusierte', _('uebrige_humusierte'), order=13)
    GEWAESSER_STEHENDES_GEWAESSER = IliChoice('Gewaesser.stehendes_Gewaesser', _('stehendes_Gewaesser'), order=14)
    GEWAESSER_FLIESSENDES_GEWAESSER = IliChoice('Gewaesser.fliessendes_Gewaesser', _('fliessendes_Gewaesser'), order=15)
    GEWAESSER_SCHILFGUERTEL = IliChoice('Gewaesser.Schilfguertel', _('Schilfguertel'), order=16)
    BESTOCKT_GESCHLOSSENER_WALD = IliChoice('bestockt.geschlossener_Wald', _('geschlossener_Wald'), order=17)
    BESTOCKT_WYTWEIDE_WYTWEIDE_DICHT = IliChoice('bestockt.Wytweide.Wytweide_dicht', _('Wytweide_dicht'), order=18)
    BESTOCKT_WYTWEIDE_WYTWEIDE_OFFEN = IliChoice('bestockt.Wytweide.Wytweide_offen', _('Wytweide_offen'), order=19)
    BESTOCKT_UEBRIGE_BESTOCKTE = IliChoice('bestockt.uebrige_bestockte', _('uebrige_bestockte'), order=20)
    VEGETATIONSLOS_FELS = IliChoice('vegetationslos.Fels', _('Fels'), order=21)
    VEGETATIONSLOS_GLETSCHER_FIRN = IliChoice('vegetationslos.Gletscher_Firn', _('Gletscher_Firn'), order=22)
    VEGETATIONSLOS_GEROELL_SAND = IliChoice('vegetationslos.Geroell_Sand', _('Geroell_Sand'), order=23)
    VEGETATIONSLOS_ABBAU_DEPONIE = IliChoice('vegetationslos.Abbau_Deponie', _('Abbau_Deponie'), order=24)
    VEGETATIONSLOS_UEBRIGE_VEGETATIONSLOSE = IliChoice('vegetationslos.uebrige_vegetationslose', _('uebrige_vegetationslose'), order=25)

@interlis_model(oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Bodenbedeckung.Qualitaetsstandard_ENUM', qname='odmav_dmav_bodenbedeckung_v1_1.BodenbedeckungQualitaetsstandardEnum')
class BodenbedeckungQualitaetsstandardEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Bodenbedeckung.Qualitaetsstandard_ENUM.code', qname='odmav_dmav_bodenbedeckung_v1_1.BodenbedeckungQualitaetsstandardEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Bodenbedeckung.Qualitaetsstandard_ENUM.label', qname='odmav_dmav_bodenbedeckung_v1_1.BodenbedeckungQualitaetsstandardEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['AV93', 'PN']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_bodenbedeckung_v1_1__bodenbedeckung_quali_16d2e446d7'

class BodenbedeckungQualitaetsstandardEnumValueChoices(IliChoices):
    AV93 = IliChoice('AV93', _('AV93'), order=0)
    PN = IliChoice('PN', _('PN'), order=1)

@interlis_model(oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Bodenbedeckung.Objektstatus_ENUM', qname='odmav_dmav_bodenbedeckung_v1_1.BodenbedeckungObjektstatusEnum')
class BodenbedeckungObjektstatusEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Bodenbedeckung.Objektstatus_ENUM.code', qname='odmav_dmav_bodenbedeckung_v1_1.BodenbedeckungObjektstatusEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Bodenbedeckung.Objektstatus_ENUM.label', qname='odmav_dmav_bodenbedeckung_v1_1.BodenbedeckungObjektstatusEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['projektiert', 'real', 'vergangen']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_bodenbedeckung_v1_1__bodenbedeckung_objek_6187e58196'

class BodenbedeckungObjektstatusEnumValueChoices(IliChoices):
    PROJEKTIERT = IliChoice('projektiert', _('projektiert'), order=0)
    REAL = IliChoice('real', _('real'), order=1)
    VERGANGEN = IliChoice('vergangen', _('vergangen'), order=2)

@interlis_model(oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.BBNachfuehrung', qname='odmav_dmav_bodenbedeckung_v1_1.BBNachfuehrung')
class BBNachfuehrung(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.BBNachfuehrung.tid', qname='odmav_dmav_bodenbedeckung_v1_1.BBNachfuehrung.tid')
    nbident = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.BBNachfuehrung.NBIdent', qname='odmav_dmav_bodenbedeckung_v1_1.BBNachfuehrung.NBIdent')
    identifikator = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.BBNachfuehrung.Identifikator', qname='odmav_dmav_bodenbedeckung_v1_1.BBNachfuehrung.Identifikator')
    beschreibung = ili_field(models.CharField(max_length=60, null=False, blank=False), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.BBNachfuehrung.Beschreibung', qname='odmav_dmav_bodenbedeckung_v1_1.BBNachfuehrung.Beschreibung')
    perimeter = ili_field(models.CurvePolygonField(srid=2056, null=True, blank=True), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.BBNachfuehrung.Perimeter', qname='odmav_dmav_bodenbedeckung_v1_1.BBNachfuehrung.Perimeter')
    gueltiger_eintrag = ili_field(models.CharField(max_length=255, null=False, blank=False), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.BBNachfuehrung.GueltigerEintrag', qname='odmav_dmav_bodenbedeckung_v1_1.BBNachfuehrung.GueltigerEintrag')

    class Meta:
        db_table = 'odmav_dmav_bodenbedeckung_v1_1__bbnachfuehrung'

@interlis_model(oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Objektnummer', qname='odmav_dmav_bodenbedeckung_v1_1.Objektnummer')
class Objektnummer(models.Model):
    nummer = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Objektnummer.Nummer', qname='odmav_dmav_bodenbedeckung_v1_1.Objektnummer.Nummer')
    textposition = ili_field(models.MultiLineStringField(srid=2056, null=True, blank=True), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Objektnummer.Textposition', qname='odmav_dmav_bodenbedeckung_v1_1.Objektnummer.Textposition')

    class Meta:
        db_table = 'odmav_dmav_bodenbedeckung_v1_1__objektnummer'

@interlis_model(oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Objektname', qname='odmav_dmav_bodenbedeckung_v1_1.Objektname')
class Objektname(models.Model):
    name = ili_field(models.CharField(max_length=60, null=False, blank=False), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Objektname.Name', qname='odmav_dmav_bodenbedeckung_v1_1.Objektname.Name')
    textposition = ili_field(models.MultiLineStringField(srid=2056, null=True, blank=True), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Objektname.Textposition', qname='odmav_dmav_bodenbedeckung_v1_1.Objektname.Textposition')

    class Meta:
        db_table = 'odmav_dmav_bodenbedeckung_v1_1__objektname'

@interlis_model(oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Bodenbedeckung', qname='odmav_dmav_bodenbedeckung_v1_1.Bodenbedeckung')
class Bodenbedeckung(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Bodenbedeckung.tid', qname='odmav_dmav_bodenbedeckung_v1_1.Bodenbedeckung.tid')
    geometrie = ili_field(models.CurvePolygonField(srid=2056, null=False, blank=False), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Bodenbedeckung.Geometrie', qname='odmav_dmav_bodenbedeckung_v1_1.Bodenbedeckung.Geometrie')
    qualitaetsstandard = ili_field(models.ForeignKey('odmav_dmav_bodenbedeckung_v1_1.BodenbedeckungQualitaetsstandardEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Bodenbedeckung.Qualitaetsstandard', qname='odmav_dmav_bodenbedeckung_v1_1.Bodenbedeckung.Qualitaetsstandard')
    bodenbedeckungsart = ili_field(models.ForeignKey('odmav_dmav_bodenbedeckung_v1_1.BodenbedeckungsartValue', on_delete=models.PROTECT, related_name='+', null=True, blank=True), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Bodenbedeckung.Bodenbedeckungsart', qname='odmav_dmav_bodenbedeckung_v1_1.Bodenbedeckung.Bodenbedeckungsart')
    fiktiv = ili_field(models.BooleanField(default=False), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Bodenbedeckung.Fiktiv', qname='odmav_dmav_bodenbedeckung_v1_1.Bodenbedeckung.Fiktiv')
    objektstatus = ili_field(models.ForeignKey('odmav_dmav_bodenbedeckung_v1_1.BodenbedeckungObjektstatusEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Bodenbedeckung.Objektstatus', qname='odmav_dmav_bodenbedeckung_v1_1.Bodenbedeckung.Objektstatus')
    objektnummer = ili_field(models.MultiLineStringField(srid=2056, null=True, blank=True), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Bodenbedeckung.Objektnummer', qname='odmav_dmav_bodenbedeckung_v1_1.Bodenbedeckung.Objektnummer')
    objektname = ili_field(models.MultiLineStringField(srid=2056, null=True, blank=True), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Bodenbedeckung.Objektname', qname='odmav_dmav_bodenbedeckung_v1_1.Bodenbedeckung.Objektname')
    egid = ili_field(models.IntegerField(null=True, blank=True), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Bodenbedeckung.EGID', qname='odmav_dmav_bodenbedeckung_v1_1.Bodenbedeckung.EGID')
    symbolposition = ili_field(models.MultiPointField(srid=2056, null=True, blank=True), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Bodenbedeckung.Symbolposition', qname='odmav_dmav_bodenbedeckung_v1_1.Bodenbedeckung.Symbolposition')
    entstehung = ili_field(models.ForeignKey('odmav_dmav_bodenbedeckung_v1_1.BBNachfuehrung', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Entstehung_Bodenbedeckung.Entstehung', qname='odmav_dmav_bodenbedeckung_v1_1.Bodenbedeckung.Entstehung')

    class Meta:
        db_table = 'odmav_dmav_bodenbedeckung_v1_1__bodenbedeckung'

@interlis_model(oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Messpunkt', qname='odmav_dmav_bodenbedeckung_v1_1.Messpunkt')
class Messpunkt(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Messpunkt.tid', qname='odmav_dmav_bodenbedeckung_v1_1.Messpunkt.tid')
    nummer = ili_field(models.CharField(max_length=12, null=True, blank=True), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Messpunkt.Nummer', qname='odmav_dmav_bodenbedeckung_v1_1.Messpunkt.Nummer')
    geometrie = ili_field(models.PointField(srid=2056, null=False, blank=False), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Messpunkt.Geometrie', qname='odmav_dmav_bodenbedeckung_v1_1.Messpunkt.Geometrie')
    hoehengeometrie = ili_field(models.FloatField(null=True, blank=True), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Messpunkt.Hoehengeometrie', qname='odmav_dmav_bodenbedeckung_v1_1.Messpunkt.Hoehengeometrie')
    lagegenauigkeit = ili_field(models.FloatField(null=False, blank=False), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Messpunkt.Lagegenauigkeit', qname='odmav_dmav_bodenbedeckung_v1_1.Messpunkt.Lagegenauigkeit')
    ist_lagezuverlaessig = ili_field(models.BooleanField(default=False), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Messpunkt.IstLagezuverlaessig', qname='odmav_dmav_bodenbedeckung_v1_1.Messpunkt.IstLagezuverlaessig')
    hoehengenauigkeit = ili_field(models.FloatField(null=True, blank=True), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Messpunkt.Hoehengenauigkeit', qname='odmav_dmav_bodenbedeckung_v1_1.Messpunkt.Hoehengenauigkeit')
    ist_hoehenzuverlaessig = ili_field(models.BooleanField(null=True, blank=True, default=None), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Messpunkt.IstHoehenzuverlaessig', qname='odmav_dmav_bodenbedeckung_v1_1.Messpunkt.IstHoehenzuverlaessig')
    ist_exakt_definiert = ili_field(models.BooleanField(default=False), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Messpunkt.IstExaktDefiniert', qname='odmav_dmav_bodenbedeckung_v1_1.Messpunkt.IstExaktDefiniert')
    entstehung = ili_field(models.ForeignKey('odmav_dmav_bodenbedeckung_v1_1.BBNachfuehrung', on_delete=models.PROTECT, related_name='+', null=True, blank=True), oid='DMAV_Bodenbedeckung_V1_1.Bodenbedeckung.Entstehung_Messpunkt.Entstehung', qname='odmav_dmav_bodenbedeckung_v1_1.Messpunkt.Entstehung')

    class Meta:
        db_table = 'odmav_dmav_bodenbedeckung_v1_1__messpunkt'
