"""Generated by ili2django. Do not edit manually."""

from django.contrib.gis.db import models

from ili2django.decorators import ili_field, interlis_model

@interlis_model(oid='DMAV_DauerndeBodenverschiebungen_V1_1.DauerndeBodenverschiebungen.DBVNachfuehrung', qname='odmav_dmav_dauernde_bodenverschiebungen_v1_1.DBVNachfuehrung')
class DBVNachfuehrung(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_DauerndeBodenverschiebungen_V1_1.DauerndeBodenverschiebungen.DBVNachfuehrung.tid', qname='odmav_dmav_dauernde_bodenverschiebungen_v1_1.DBVNachfuehrung.tid')
    nbident = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='DMAV_DauerndeBodenverschiebungen_V1_1.DauerndeBodenverschiebungen.DBVNachfuehrung.NBIdent', qname='odmav_dmav_dauernde_bodenverschiebungen_v1_1.DBVNachfuehrung.NBIdent')
    identifikator = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='DMAV_DauerndeBodenverschiebungen_V1_1.DauerndeBodenverschiebungen.DBVNachfuehrung.Identifikator', qname='odmav_dmav_dauernde_bodenverschiebungen_v1_1.DBVNachfuehrung.Identifikator')
    beschreibung = ili_field(models.CharField(max_length=60, null=False, blank=False), oid='DMAV_DauerndeBodenverschiebungen_V1_1.DauerndeBodenverschiebungen.DBVNachfuehrung.Beschreibung', qname='odmav_dmav_dauernde_bodenverschiebungen_v1_1.DBVNachfuehrung.Beschreibung')
    perimeter = ili_field(models.CurvePolygonField(srid=2056, null=True, blank=True), oid='DMAV_DauerndeBodenverschiebungen_V1_1.DauerndeBodenverschiebungen.DBVNachfuehrung.Perimeter', qname='odmav_dmav_dauernde_bodenverschiebungen_v1_1.DBVNachfuehrung.Perimeter')
    gueltiger_eintrag = ili_field(models.CharField(max_length=255, null=False, blank=False), oid='DMAV_DauerndeBodenverschiebungen_V1_1.DauerndeBodenverschiebungen.DBVNachfuehrung.GueltigerEintrag', qname='odmav_dmav_dauernde_bodenverschiebungen_v1_1.DBVNachfuehrung.GueltigerEintrag')
    genehmigt_am = ili_field(models.CharField(max_length=255, null=True, blank=True), oid='DMAV_DauerndeBodenverschiebungen_V1_1.DauerndeBodenverschiebungen.DBVNachfuehrung.GenehmigtAm', qname='odmav_dmav_dauernde_bodenverschiebungen_v1_1.DBVNachfuehrung.GenehmigtAm')

    class Meta:
        db_table = 'odmav_dmav_dauernde_bodenverschiebungen_v1_1__dbvnachfuehrung'

@interlis_model(oid='DMAV_DauerndeBodenverschiebungen_V1_1.DauerndeBodenverschiebungen.DauerndeBodenverschiebung', qname='odmav_dmav_dauernde_bodenverschiebungen_v1_1.DauerndeBodenverschiebung')
class DauerndeBodenverschiebung(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_DauerndeBodenverschiebungen_V1_1.DauerndeBodenverschiebungen.DauerndeBodenverschiebung.tid', qname='odmav_dmav_dauernde_bodenverschiebungen_v1_1.DauerndeBodenverschiebung.tid')
    nbident = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='DMAV_DauerndeBodenverschiebungen_V1_1.DauerndeBodenverschiebungen.DauerndeBodenverschiebung.NBIdent', qname='odmav_dmav_dauernde_bodenverschiebungen_v1_1.DauerndeBodenverschiebung.NBIdent')
    identifikator = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='DMAV_DauerndeBodenverschiebungen_V1_1.DauerndeBodenverschiebungen.DauerndeBodenverschiebung.Identifikator', qname='odmav_dmav_dauernde_bodenverschiebungen_v1_1.DauerndeBodenverschiebung.Identifikator')
    beschreibung = ili_field(models.CharField(max_length=60, null=True, blank=True), oid='DMAV_DauerndeBodenverschiebungen_V1_1.DauerndeBodenverschiebungen.DauerndeBodenverschiebung.Beschreibung', qname='odmav_dmav_dauernde_bodenverschiebungen_v1_1.DauerndeBodenverschiebung.Beschreibung')
    geometrie = ili_field(models.CurvePolygonField(srid=2056, null=False, blank=False), oid='DMAV_DauerndeBodenverschiebungen_V1_1.DauerndeBodenverschiebungen.DauerndeBodenverschiebung.Geometrie', qname='odmav_dmav_dauernde_bodenverschiebungen_v1_1.DauerndeBodenverschiebung.Geometrie')
    textposition = ili_field(models.MultiLineStringField(srid=2056, null=True, blank=True), oid='DMAV_DauerndeBodenverschiebungen_V1_1.DauerndeBodenverschiebungen.DauerndeBodenverschiebung.Textposition', qname='odmav_dmav_dauernde_bodenverschiebungen_v1_1.DauerndeBodenverschiebung.Textposition')
    entstehung = ili_field(models.ForeignKey('odmav_dmav_dauernde_bodenverschiebungen_v1_1.DBVNachfuehrung', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_DauerndeBodenverschiebungen_V1_1.DauerndeBodenverschiebungen.Entstehung_DauerndeBodenverschiebung.Entstehung', qname='odmav_dmav_dauernde_bodenverschiebungen_v1_1.DauerndeBodenverschiebung.Entstehung')
    untergang = ili_field(models.ForeignKey('odmav_dmav_dauernde_bodenverschiebungen_v1_1.DBVNachfuehrung', on_delete=models.PROTECT, related_name='+', null=True, blank=True), oid='DMAV_DauerndeBodenverschiebungen_V1_1.DauerndeBodenverschiebungen.Untergang_DauerndeBodenverschiebung.Untergang', qname='odmav_dmav_dauernde_bodenverschiebungen_v1_1.DauerndeBodenverschiebung.Untergang')

    class Meta:
        db_table = 'odmav_dmav_dauernde_bodenverschiebungen_v1_1__dauern_a65f13b6ab'
