"""Generated by ili2django. Do not edit manually."""

from django.contrib.gis.db import models
from django.utils.translation import gettext_lazy as _

from ili2django.choices import IliChoice, IliChoices
from ili2django.decorators import ili_field, interlis_model

@interlis_model(oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.LFPArt', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.LFPArt')
class LFPArtValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.LFPArt.code', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.LFPArt.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.LFPArt.label', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.LFPArt.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['LFP3', 'Hilfsfixpunkt']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_fixpunkte_avkategorie3_v1_1__lfpart_value'

class LFPArtValueChoices(IliChoices):
    LFP3 = IliChoice('LFP3', _('LFP3'), order=0)
    HILFSFIXPUNKT = IliChoice('Hilfsfixpunkt', _('Hilfsfixpunkt'), order=1)

@interlis_model(oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.Schutzart', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.Schutzart')
class SchutzartValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.Schutzart.code', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.Schutzart.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.Schutzart.label', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.Schutzart.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['keinSchutz', 'Schacht', 'ueberdeckt']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_fixpunkte_avkategorie3_v1_1__schutzart_value'

class SchutzartValueChoices(IliChoices):
    KEIN_SCHUTZ = IliChoice('keinSchutz', _('keinSchutz'), order=0)
    SCHACHT = IliChoice('Schacht', _('Schacht'), order=1)
    UEBERDECKT = IliChoice('ueberdeckt', _('ueberdeckt'), order=2)

@interlis_model(oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.Grenzpunktfunktion', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.Grenzpunktfunktion')
class GrenzpunktfunktionValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.Grenzpunktfunktion.code', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.Grenzpunktfunktion.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.Grenzpunktfunktion.label', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.Grenzpunktfunktion.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['keine', 'Grenzpunkt', 'Hoheitsgrenzpunkt']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_fixpunkte_avkategorie3_v1_1__grenzpunktfu_52dcabff44'

class GrenzpunktfunktionValueChoices(IliChoices):
    KEINE = IliChoice('keine', _('keine'), order=0)
    GRENZPUNKT = IliChoice('Grenzpunkt', _('Grenzpunkt'), order=1)
    HOHEITSGRENZPUNKT = IliChoice('Hoheitsgrenzpunkt', _('Hoheitsgrenzpunkt'), order=2)

@interlis_model(oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.LFP3.LFPArt_ENUM', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.LFP3LFPArtEnum')
class LFP3LFPArtEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.LFP3.LFPArt_ENUM.code', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.LFP3LFPArtEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.LFP3.LFPArt_ENUM.label', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.LFP3LFPArtEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['LFP3', 'Hilfsfixpunkt']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_fixpunkte_avkategorie3_v1_1__lfp3_lfpart_enum_value'

class LFP3LFPArtEnumValueChoices(IliChoices):
    LFP3 = IliChoice('LFP3', _('LFP3'), order=0)
    HILFSFIXPUNKT = IliChoice('Hilfsfixpunkt', _('Hilfsfixpunkt'), order=1)

@interlis_model(oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.LFP3.Punktzeichen_ENUM', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.LFP3PunktzeichenEnum')
class LFP3PunktzeichenEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.LFP3.Punktzeichen_ENUM.code', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.LFP3PunktzeichenEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.LFP3.Punktzeichen_ENUM.label', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.LFP3PunktzeichenEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['Stein', 'Kunststoffzeichen', 'Bolzen', 'Rohr', 'Pfahl', 'Kreuz', 'unversichert', 'weitere']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_fixpunkte_avkategorie3_v1_1__lfp3_punktze_d8402652b8'

class LFP3PunktzeichenEnumValueChoices(IliChoices):
    STEIN = IliChoice('Stein', _('Stein'), order=0)
    KUNSTSTOFFZEICHEN = IliChoice('Kunststoffzeichen', _('Kunststoffzeichen'), order=1)
    BOLZEN = IliChoice('Bolzen', _('Bolzen'), order=2)
    ROHR = IliChoice('Rohr', _('Rohr'), order=3)
    PFAHL = IliChoice('Pfahl', _('Pfahl'), order=4)
    KREUZ = IliChoice('Kreuz', _('Kreuz'), order=5)
    UNVERSICHERT = IliChoice('unversichert', _('unversichert'), order=6)
    WEITERE = IliChoice('weitere', _('weitere'), order=7)

@interlis_model(oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.LFP3.Grenzpunktfunktion_ENUM', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.LFP3GrenzpunktfunktionEnum')
class LFP3GrenzpunktfunktionEnumValue(models.Model):
    code = ili_field(models.CharField(max_length=255, unique=True), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.LFP3.Grenzpunktfunktion_ENUM.code', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.LFP3GrenzpunktfunktionEnum.code')
    label = ili_field(models.CharField(max_length=255), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.LFP3.Grenzpunktfunktion_ENUM.label', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.LFP3GrenzpunktfunktionEnum.label')
    order = models.IntegerField(default=0)
    __ili2django_values__ = ['keine', 'Grenzpunkt', 'Hoheitsgrenzpunkt']
    __ili2django_tree__ = False

    def __str__(self) -> str:
        return self.label or self.code

    class Meta:
        db_table = 'odmav_dmav_fixpunkte_avkategorie3_v1_1__lfp3_grenzpu_926306ca97'

class LFP3GrenzpunktfunktionEnumValueChoices(IliChoices):
    KEINE = IliChoice('keine', _('keine'), order=0)
    GRENZPUNKT = IliChoice('Grenzpunkt', _('Grenzpunkt'), order=1)
    HOHEITSGRENZPUNKT = IliChoice('Hoheitsgrenzpunkt', _('Hoheitsgrenzpunkt'), order=2)

@interlis_model(oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.LFP3Nachfuehrung', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.LFP3Nachfuehrung')
class LFP3Nachfuehrung(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.LFP3Nachfuehrung.tid', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.LFP3Nachfuehrung.tid')
    nbident = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.LFP3Nachfuehrung.NBIdent', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.LFP3Nachfuehrung.NBIdent')
    identifikator = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.LFP3Nachfuehrung.Identifikator', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.LFP3Nachfuehrung.Identifikator')
    beschreibung = ili_field(models.CharField(max_length=60, null=False, blank=False), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.LFP3Nachfuehrung.Beschreibung', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.LFP3Nachfuehrung.Beschreibung')
    perimeter = ili_field(models.CurvePolygonField(srid=2056, null=True, blank=True), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.LFP3Nachfuehrung.Perimeter', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.LFP3Nachfuehrung.Perimeter')
    gueltiger_eintrag = ili_field(models.CharField(max_length=255, null=False, blank=False), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.LFP3Nachfuehrung.GueltigerEintrag', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.LFP3Nachfuehrung.GueltigerEintrag')

    class Meta:
        db_table = 'odmav_dmav_fixpunkte_avkategorie3_v1_1__lfp3_nachfuehrung'

@interlis_model(oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.LFP3', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.LFP3')
class LFP3(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.LFP3.tid', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.LFP3.tid')
    nbident = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.LFP3.NBIdent', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.LFP3.NBIdent')
    nummer = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.LFP3.Nummer', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.LFP3.Nummer')
    lfpart = ili_field(models.ForeignKey('odmav_dmav_fixpunkte_avkategorie3_v1_1.LFP3LFPArtEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.LFP3.LFPArt', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.LFP3.LFPArt')
    geometrie = ili_field(models.PointField(srid=2056, null=False, blank=False), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.LFP3.Geometrie', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.LFP3.Geometrie')
    hoehengeometrie = ili_field(models.FloatField(null=True, blank=True), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.LFP3.Hoehengeometrie', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.LFP3.Hoehengeometrie')
    lagegenauigkeit = ili_field(models.FloatField(null=False, blank=False), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.LFP3.Lagegenauigkeit', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.LFP3.Lagegenauigkeit')
    ist_lagezuverlaessig = ili_field(models.BooleanField(default=False), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.LFP3.IstLagezuverlaessig', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.LFP3.IstLagezuverlaessig')
    hoehengenauigkeit = ili_field(models.FloatField(null=True, blank=True), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.LFP3.Hoehengenauigkeit', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.LFP3.Hoehengenauigkeit')
    ist_hoehenzuverlaessig = ili_field(models.BooleanField(null=True, blank=True, default=None), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.LFP3.IstHoehenzuverlaessig', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.LFP3.IstHoehenzuverlaessig')
    punktzeichen = ili_field(models.ForeignKey('odmav_dmav_fixpunkte_avkategorie3_v1_1.LFP3PunktzeichenEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.LFP3.Punktzeichen', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.LFP3.Punktzeichen')
    schutzart = ili_field(models.ForeignKey('odmav_dmav_fixpunkte_avkategorie3_v1_1.SchutzartValue', on_delete=models.PROTECT, related_name='+', null=True, blank=True), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.LFP3.Schutzart', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.LFP3.Schutzart')
    grenzpunktfunktion = ili_field(models.ForeignKey('odmav_dmav_fixpunkte_avkategorie3_v1_1.LFP3GrenzpunktfunktionEnumValue', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.LFP3.Grenzpunktfunktion', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.LFP3.Grenzpunktfunktion')
    ist_hoheitsgrenzstein_alt = ili_field(models.BooleanField(null=True, blank=True, default=None), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.LFP3.IstHoheitsgrenzsteinAlt', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.LFP3.IstHoheitsgrenzsteinAlt')
    aktiver_unterhalt = ili_field(models.BooleanField(default=False), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.LFP3.AktiverUnterhalt', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.LFP3.AktiverUnterhalt')
    symbol_ori = ili_field(models.FloatField(null=True, blank=True), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.LFP3.SymbolOri', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.LFP3.SymbolOri')
    textposition = ili_field(models.MultiLineStringField(srid=2056, null=True, blank=True), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.LFP3.Textposition', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.LFP3.Textposition')
    entstehung = ili_field(models.ForeignKey('odmav_dmav_fixpunkte_avkategorie3_v1_1.LFP3Nachfuehrung', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.Entstehung_LFP3.Entstehung', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.LFP3.Entstehung')

    class Meta:
        db_table = 'odmav_dmav_fixpunkte_avkategorie3_v1_1__lfp3'

@interlis_model(oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.HFP3Nachfuehrung', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.HFP3Nachfuehrung')
class HFP3Nachfuehrung(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.HFP3Nachfuehrung.tid', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.HFP3Nachfuehrung.tid')
    nbident = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.HFP3Nachfuehrung.NBIdent', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.HFP3Nachfuehrung.NBIdent')
    identifikator = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.HFP3Nachfuehrung.Identifikator', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.HFP3Nachfuehrung.Identifikator')
    beschreibung = ili_field(models.CharField(max_length=60, null=False, blank=False), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.HFP3Nachfuehrung.Beschreibung', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.HFP3Nachfuehrung.Beschreibung')
    perimeter = ili_field(models.CurvePolygonField(srid=2056, null=True, blank=True), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.HFP3Nachfuehrung.Perimeter', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.HFP3Nachfuehrung.Perimeter')
    gueltiger_eintrag = ili_field(models.CharField(max_length=255, null=False, blank=False), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.HFP3Nachfuehrung.GueltigerEintrag', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.HFP3Nachfuehrung.GueltigerEintrag')

    class Meta:
        db_table = 'odmav_dmav_fixpunkte_avkategorie3_v1_1__hfp3_nachfuehrung'

@interlis_model(oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.HFP3', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.HFP3')
class HFP3(models.Model):
    tid = ili_field(models.CharField(max_length=255, unique=True), oid='ili2py.DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.HFP3.tid', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.HFP3.tid')
    nbident = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.HFP3.NBIdent', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.HFP3.NBIdent')
    nummer = ili_field(models.CharField(max_length=12, null=False, blank=False), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.HFP3.Nummer', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.HFP3.Nummer')
    geometrie = ili_field(models.PointField(srid=2056, null=False, blank=False), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.HFP3.Geometrie', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.HFP3.Geometrie')
    hoehengeometrie = ili_field(models.FloatField(null=False, blank=False), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.HFP3.Hoehengeometrie', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.HFP3.Hoehengeometrie')
    lagegenauigkeit = ili_field(models.FloatField(null=False, blank=False), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.HFP3.Lagegenauigkeit', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.HFP3.Lagegenauigkeit')
    ist_lagezuverlaessig = ili_field(models.BooleanField(default=False), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.HFP3.IstLagezuverlaessig', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.HFP3.IstLagezuverlaessig')
    hoehengenauigkeit = ili_field(models.FloatField(null=False, blank=False), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.HFP3.Hoehengenauigkeit', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.HFP3.Hoehengenauigkeit')
    ist_hoehenzuverlaessig = ili_field(models.BooleanField(default=False), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.HFP3.IstHoehenzuverlaessig', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.HFP3.IstHoehenzuverlaessig')
    textposition = ili_field(models.MultiLineStringField(srid=2056, null=True, blank=True), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.HFP3.Textposition', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.HFP3.Textposition')
    entstehung = ili_field(models.ForeignKey('odmav_dmav_fixpunkte_avkategorie3_v1_1.HFP3Nachfuehrung', on_delete=models.PROTECT, related_name='+', null=False, blank=False), oid='DMAV_FixpunkteAVKategorie3_V1_1.FixpunkteAVKategorie3.Entstehung_HFP3.Entstehung', qname='odmav_dmav_fixpunkte_avkategorie3_v1_1.HFP3.Entstehung')

    class Meta:
        db_table = 'odmav_dmav_fixpunkte_avkategorie3_v1_1__hfp3'
